 ## ✅ Hands-on Advanced Pandas

In [6]:
import pandas as pd
import numpy as np

In [11]:
# read the files

df = pd.read_csv("telecom_churn.csv")

In [13]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [14]:
# filtering data bsed on conditions

# df[df[column name]< condition operator> value]

In [18]:
df['Churn'].value_counts()

Churn
False    2850
True      483
Name: count, dtype: int64

In [26]:
df[df['Churn']==True]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
10,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
15,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
21,CO,77,408,No,No,0,62.4,89,10.61,169.9,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
33,AZ,12,408,No,No,0,249.6,118,42.43,252.4,119,21.45,280.2,90,12.61,11.8,3,3.19,1,True
41,MD,135,408,Yes,Yes,41,173.1,85,29.43,203.9,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301,CA,84,415,No,No,0,280.0,113,47.60,202.2,90,17.19,156.8,103,7.06,10.4,4,2.81,0,True
3304,IL,71,510,Yes,No,0,186.1,114,31.64,198.6,140,16.88,206.5,80,9.29,13.8,5,3.73,4,True
3320,GA,122,510,Yes,No,0,140.0,101,23.80,196.4,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3322,MD,62,408,No,No,0,321.1,105,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True
3323,IN,117,415,No,No,0,118.4,126,20.13,249.3,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True

In [30]:
# filtering data based on multiple columns

df[(df['Churn']==True) & (df['Area code']==408)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
21,CO,77,408,No,No,0,62.4,89,10.61,169.9,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
33,AZ,12,408,No,No,0,249.6,118,42.43,252.4,119,21.45,280.2,90,12.61,11.8,3,3.19,1,True
41,MD,135,408,Yes,Yes,41,173.1,85,29.43,203.9,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
57,CO,121,408,No,Yes,30,198.4,129,33.73,75.3,77,6.40,181.2,77,8.15,5.8,3,1.57,3,True
77,NY,144,408,No,No,0,61.6,117,10.47,77.1,85,6.55,173.0,99,7.79,8.2,7,2.21,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3151,ME,56,408,No,No,0,221.9,112,37.72,278.2,122,23.65,288.1,85,12.96,7.1,5,1.92,0,True
3205,MS,111,408,No,No,0,294.7,90,50.10,294.6,72,25.04,260.1,121,11.70,10.8,3,2.92,1,True
3246,NC,77,408,Yes,Yes,44,103.2,117,17.54,236.3,86,20.09,203.5,101,9.16,11.9,2,3.21,0,True
3280,AR,76,408,No,No,0,107.3,140,18.24,238.2,133,20.25,271.8,116,12.23,10.0,3,2.70,4,True
3322,MD,62,408,No,No,0,321.1,105,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True

In [32]:
# cross tab : it gives calculations between two or more rows

pd.crosstab(df['Churn'], df['International plan'])

International plan    No  Yes
Churn
False               2664  186
True                 346  137

In [37]:
pd.crosstab(df['Churn'], [df['International plan'], df['Area code'], df['Voice mail plan']])

International plan   No                          Yes
Area code           408       415       510      408     415     510
Voice mail plan      No  Yes   No  Yes   No  Yes  No Yes  No Yes  No Yes
Churn
False               490  187  926  405  462  194  28  11  56  32  46  13
True                 77   13  156   18   69   13  23   9  46  16  32  11

In [40]:
pd.crosstab(df['Churn'], df['State'])

State,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,SD,TN,TX,UT,VA,VT,WA,WI,WV,WY
Churn,,,,,,,,,,,,,,,,,,,,,
False,49,72,44,60,25,57,62,49,52,55,...,52,48,54,62,72,65,52,71,96,68
True,3,8,11,4,9,9,12,5,9,8,...,8,5,18,10,5,8,14,7,10,9

In [ ]:
# groupby  : 

# df.groupby(grouping column)[columns to show].function()

In [156]:
column_to_show = ['Total day calls','Total night calls']

df.groupby('Churn')[column_to_show].mean()

       Total day calls  Total night calls
Churn
False       100.283158         100.058246
True        101.335404         100.399586

In [53]:
# internal process

df[(df['Churn']==False)].iloc[:, ['Total day calls', 'Total night calls']].mean()

Total day calls      100.283158
Total night calls    100.058246
dtype: float64

In [54]:
# another method for groupby :.agg


df.groupby('Area code').agg({'Total night calls': 'mean'})

           Total night calls
Area code
408                99.039379
415               100.398187
510               100.601190

In [55]:
df.groupby('Area code').agg({'Total day calls': 'min', 'Total night calls': 'mean'})

           Total day calls  Total night calls
Area code
408                     30          99.039379
415                      0         100.398187
510                      0         100.601190

In [58]:
df.groupby('Area code').agg({'Total day calls': np.min, 'Total night calls': np.mean})

C:\Users\DELL\AppData\Local\Temp\ipykernel_7176\1355513537.py:1: FutureWarning: The provided callable <function min at 0x000001E518F5E0C0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('Area code').agg({'Total day calls': np.min, 'Total night calls': np.mean})
C:\Users\DELL\AppData\Local\Temp\ipykernel_7176\1355513537.py:1: FutureWarning: The provided callable <function mean at 0x000001E518F5E980> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('Area code').agg({'Total day calls': np.min, 'Total night calls': np.mean})

           Total day calls  Total night calls
Area code
408                     30          99.039379
415                      0         100.398187
510                      0         100.601190

In [59]:
# groupby on multiple columns

In [61]:
df.groupby(['Churn','Area code']).agg({'Total day calls':np.max,'Total night calls':np.mean})

C:\Users\DELL\AppData\Local\Temp\ipykernel_7176\4269747296.py:1: FutureWarning: The provided callable <function max at 0x000001E518F5DF80> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['Churn','Area code']).agg({'Total day calls':np.max,'Total night calls':np.mean})
C:\Users\DELL\AppData\Local\Temp\ipykernel_7176\4269747296.py:1: FutureWarning: The provided callable <function mean at 0x000001E518F5E980> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['Churn','Area code']).agg({'Total day calls':np.max,'Total night calls':np.mean})

                 Total day calls  Total night calls
Churn Area code
False 408                    158          99.276536
      415                    163         100.294574
      510                    158         100.372028
True  408                    156          97.647541
      415                    165         101.021186
      510                    143         101.912000

In [62]:
# merge
# create random data.

In [73]:
std_details = {'id':[1,2,3,4,5],
               'name':['A','B','C','D','E'],
              'region':['N','S','W','W','S']}
stu_marks = {'id':[1,2,3,4,6],
               'sub':['py','matlab','C','R','java'],
              'marks':[10,13,14,16,13]}


df1 = pd.DataFrame(std_details)
df2 = pd.DataFrame(stu_marks)

In [74]:
df1

   id name region
0   1    A      N
1   2    B      S
2   3    C      W
3   4    D      W
4   5    E      S

In [75]:
df2

   id     sub  marks
0   1      py     10
1   2  matlab     13
2   3       C     14
3   4       R     16
4   6    java     13

In [76]:
# inner merge : default

pd.merge(df1, df2)

   id name region     sub  marks
0   1    A      N      py     10
1   2    B      S  matlab     13
2   3    C      W       C     14
3   4    D      W       R     16

In [77]:
# standard method

pd.merge(df1, df2, on = 'id')

   id name region     sub  marks
0   1    A      N      py     10
1   2    B      S  matlab     13
2   3    C      W       C     14
3   4    D      W       R     16

In [78]:
# left merge : fetch everything from left df but common one from right df

pd.merge(df1, df2, on = 'id', how='left')

   id name region     sub  marks
0   1    A      N      py   10.0
1   2    B      S  matlab   13.0
2   3    C      W       C   14.0
3   4    D      W       R   16.0
4   5    E      S     NaN    NaN

In [79]:
# right merge : fetch everything from right df but common one from left df

pd.merge(df1, df2, on = 'id', how='right')

   id name region     sub  marks
0   1    A      N      py     10
1   2    B      S  matlab     13
2   3    C      W       C     14
3   4    D      W       R     16
4   6  NaN    NaN    java     13

In [80]:
# outer : union of both the tables

pd.merge(df1, df2, on = 'id', how='outer')

   id name region     sub  marks
0   1    A      N      py   10.0
1   2    B      S  matlab   13.0
2   3    C      W       C   14.0
3   4    D      W       R   16.0
4   5    E      S     NaN    NaN
5   6  NaN    NaN    java   13.0

In [86]:
# when reference column names are diff in two tables

std_details1 = {'s_id':[1,2,3,4,5],
               'name':['A','B','C','D','E'],
              'region':['N','S','W','W','S']}
stu_marks1 = {'id':[1,2,3,4,6],
               'sub':['py','matlab','C','R','py'],
              'marks':[10,13,14,16,13]}


s1 = pd.DataFrame(std_details1)
s2 = pd.DataFrame(stu_marks1)

In [87]:
s1

   s_id name region
0     1    A      N
1     2    B      S
2     3    C      W
3     4    D      W
4     5    E      S

In [88]:
s2

   id     sub  marks
0   1      py     10
1   2  matlab     13
2   3       C     14
3   4       R     16
4   6      py     13

In [90]:
# pd.merge(df3,df4) : it will throw an error

In [91]:
pd.merge(s1, s2, left_on='s_id', right_on='id')

   s_id name region  id     sub  marks
0     1    A      N   1      py     10
1     2    B      S   2  matlab     13
2     3    C      W   3       C     14
3     4    D      W   4       R     16

In [92]:
pd.merge(s1, s2, left_on='s_id', right_on='id', how='left')

   s_id name region   id     sub  marks
0     1    A      N  1.0      py   10.0
1     2    B      S  2.0  matlab   13.0
2     3    C      W  3.0       C   14.0
3     4    D      W  4.0       R   16.0
4     5    E      S  NaN     NaN    NaN

In [94]:
pd.merge(s1, s2, left_on='s_id', right_on='id', how='right')

   s_id name region  id     sub  marks
0   1.0    A      N   1      py     10
1   2.0    B      S   2  matlab     13
2   3.0    C      W   3       C     14
3   4.0    D      W   4       R     16
4   NaN  NaN    NaN   6      py     13

In [95]:
pd.merge(s1, s2, left_on='s_id', right_on='id', how='outer')

   s_id name region   id     sub  marks
0   1.0    A      N  1.0      py   10.0
1   2.0    B      S  2.0  matlab   13.0
2   3.0    C      W  3.0       C   14.0
3   4.0    D      W  4.0       R   16.0
4   5.0    E      S  NaN     NaN    NaN
5   NaN  NaN    NaN  6.0      py   13.0

In [96]:
df1

   id name region
0   1    A      N
1   2    B      S
2   3    C      W
3   4    D      W
4   5    E      S

In [97]:
df2

   id     sub  marks
0   1      py     10
1   2  matlab     13
2   3       C     14
3   4       R     16
4   6    java     13

In [99]:
a = {'id':[1,2],
    'name':['A','B']
    }
b = {'id':[4,6],
    'name':['D','E']
    }


a1 = pd.DataFrame(a)
b1 = pd.DataFrame(b)

In [100]:
a1

   id name
0   1    A
1   2    B

In [101]:
b1

   id name
0   4    D
1   6    E

In [102]:
# combine df row wise


pd.concat([a1, b1], axis=0)

   id name
0   1    A
1   2    B
0   4    D
1   6    E

In [103]:
# combine df column wise

pd.concat([a1, b1], axis=1)

   id name  id name
0   1    A   4    D
1   2    B   6    E

In [104]:
# Task

In [105]:
df_emp = pd.read_csv("employees.csv")
df_emp

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# how many number of employees data we have ?

In [111]:
df_emp.shape[0]

1000

In [112]:
# provide data distribution of gender column in %

In [115]:
df_emp['Gender'].value_counts(normalize=True)*100

Gender
Female    50.409357
Male      49.590643
Name: proportion, dtype: float64

In [117]:
# which column is having highest null values, give count also

In [120]:
df_emp.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [121]:
# in column Teams what all diff unique categories are there ?

In [125]:
df_emp['Team'].nunique()

10

In [126]:
# what is last login time of a person having highest salary

In [137]:
df_emp.sort_values(by= 'Salary', ascending=False).iloc[0]['First Name']

'Katherine'

In [ ]:
# what is name of a person having least bonus

In [136]:
df_emp.sort_values(by= 'Bonus %', ascending=True).iloc[0]['First Name']

'Douglas'

In [138]:
df_emp.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [139]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [140]:
# convert one data type to another

In [144]:
df_emp['Senior Management'] = df_emp['Senior Management'].astype('bool')

In [145]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), float64(1), int64(1), object(5)
memory usage: 55.8+ KB

In [149]:
df_emp['Start Date'] = pd.to_datetime(df_emp['Start Date'])

In [150]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 55.8+ KB

In [151]:
df_emp['Start Date'].dt.year

0      1993
1      1996
2      1993
3      2005
4      1998
       ...
995    2014
996    1984
997    2013
998    2013
999    2012
Name: Start Date, Length: 1000, dtype: int32

In [152]:
df_emp['Start Date'].dt.day

0       6
1      31
2      23
3       4
4      24
       ..
995    23
996    31
997    20
998    20
999    15
Name: Start Date, Length: 1000, dtype: int32

In [154]:
df_emp['Start Date'].dt.month

0       8
1       3
2       4
3       3
4       1
       ..
995    11
996     1
997     5
998     4
999     5
Name: Start Date, Length: 1000, dtype: int32