In [1]:
## Pandas --> Python Data Analysis Library
## Pandas --> Used to handle datasets in the form of dataframes (originally in the form of excel or csv etc)

## How to import pandas library?

In [2]:
import pandas as pd

In [7]:
#https://drive.google.com/file/d/1WgDNC-uiVIlVDVoLWOmJgBocIN3v3ILs/view?usp=drive_link

## Load the data

In [9]:
# filename
# df=pd.read_csv("day.csv") 
# filepath
df=pd.read_csv(r"D:/Bootcamp - Python/Coding Practices/employees.csv")

In [10]:
## df.head(n) --> used to see top n rows of the data
df.head(2) #by default ->5

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-93,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN

In [11]:
## df.tail(n) --> Used to see last n rows of the data
df.tail(2) #by default ->5

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [15]:
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [16]:
# pd.set_option("display.max_rows", None)
# pd.set_option("display.max_columuns", None)

OptionError: No such keys(s): 'display.max_columuns'

In [13]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-93,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,08-08-02,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,08-12-80,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12-01-80,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,06-05-16,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12-07-86,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,09-05-95,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,03-08-12,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,07-01-92,10:08 PM,97950,13.873,False,Client Services
25,NaN,Male,10-08-12,1:12 AM,37076,18.576,NaN,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,NaN,07-11-91,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal
30,Christina,Female,08-06-02,1:19 PM,118780,9.096,True,Engineering
31,Joyce,NaN,2/20/2005,2:40 PM,88657,12.752,False,Product
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN
33,Jean,Female,12/18/1993,9:07 AM,119082,16.180,False,Business Development
34,Jerry,Male,01-10-04,12:56 PM,95734,19.096,False,Client Services
35,Theresa,Female,10-10-06,1:12 AM,85182,16.675,False,Sales
36,Rachel,Female,2/16/2009,8:47 PM,142032,12.599,False,Business Development
37,Linda,Female,10/19/1981,8:49 PM,57427,9.557,True,Client Services
38,Stephanie,Female,9/13/1986,1:52 AM,36844,5.574,True,Business Development
39,NaN,Male,1/29/2016,2:33 AM,122173,7.797,NaN,Client Services
40,Michael,Male,10-10-08,11:25 AM,99283,2.665,True,Distribution
41,Christine,NaN,6/28/2015,1:08 AM,66582,11.308,True,Business Development
42,Beverly,Female,09-09-98,8:26 PM,121918,15.835,False,Legal
43,Marilyn,Female,12-07-80,3:16 AM,73524,5.207,True,Marketing
44,Cynthia,Female,11/16/1988,6:54 PM,145146,7.482,True,Product
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
47,Kathy,Female,6/22/2005,4:51 AM,66820,9.000,True,Client Services
48,Clarence,Male,3/26/1996,5:57 AM,93581,6.083,True,Business Development
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales
50,Nancy,Female,9/23/2000,8:05 AM,94976,13.830,True,Engineering
51,NaN,NaN,12/17/2011,8:29 AM,41126,14.009,NaN,Sales
52,Todd,Male,2/18/1990,2:41 AM,49339,1.695,True,Human Resources
53,Alan,NaN,03-03-14,1:28 PM,40341,17.578,True,Finance
54,Sara,Female,8/15/2007,9:23 AM,83677,8.999,False,Engineering
55,Karen,Female,11/30/1999,7:46 AM,102488,17.653,True,Product
56,Carl,Male,05-03-06,5:55 PM,130276,16.084,True,Finance
57,Henry,Male,6/26/1996,1:44 AM,64715,15.107,True,Human Resources
58,Theresa,Female,04-11-10,7:18 AM,72670,1.481,True,Engineering
59,Irene,Female,05-07-97,9:32 AM,66851,11.279,False,Engineering
60,Paula,NaN,11/23/2005,2:01 PM,48866,4.271,False,Distribution
61,Denise,Female,11-06-01,12:03 PM,106862,3.699,False,Business Development
62,NaN,Female,06-12-07,5:25 PM,58112,19.414,NaN,Marketing
63,Matthew,Male,01-02-13,10:33 PM,35203,18.040,False,Human Resources
64,Kathleen,NaN,04-11-90,6:46 PM,77834,18.771,False,Business Development
65,Steve,Male,11-11-09,11:44 PM,61310,12.428,True,Distribution
66,Nancy,Female,12/15/2012,11:57 PM,125250,2.672,True,Business Development
67,Rachel,Female,8/16/1999,6:53 AM,51178,9.735,True,Finance
68,Jose,Male,10/30/2004,1:39 PM,84834,14.330,True,Finance
69,Irene,NaN,7/14/2015,4:31 PM,100863,4.382,True,Finance
70,Todd,NaN,06-10-03,2:26 PM,84692,6.617,False,Client Services
71,Johnny,Male,11-06-09,4:23 PM,118172,16.194,True,Sales
72,Bobby,Male,05-07-07,10:01 AM,54043,3.833,False,Product
73,Frances,Female,04-04-99,4:19 PM,90582,4.709,True,Sales
74,Thomas,Male,06-04-95,2:24 PM,62096,17.029,False,Marketing
75,Bonnie,Female,07-02-91,1:27 AM,104897,5.118,True,Human Resources
76,Margaret,Female,09-10-88,12:42 PM,131604,7.353,True,Distribution
77,Charles,Male,9/14/2004,8:13 PM,107391,1.260,True,Marketing
78,Robin,Female,06-04-83,3:15 PM,114797,5.965,True,Sales
79,Bonnie,Female,11/13/1988,3:30 PM,115814,4.990,False,Product
80,Gerald,NaN,3/17/1995,12:50 AM,137126,15.602,True,Sales
81,Christopher,Male,3/30/2008,10:52 AM,47369,14.822,False,Legal
82,Steven,Male,3/30/1980,9:20 PM,35095,8.379,True,Client Services
83,Shawn,Male,9/23/2005,2:55 AM,148115,6.539,True,Finance
84,Doris,Female,8/20/2004,5:51 AM,83072,7.511,False,Finance
85,Jeremy,Male,02-01-08,8:50 AM,100238,3.887,True,Client Services
86,Annie,NaN,9/29/2007,12:11 AM,103495,17.290,True,Business Development
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
88,Donna,Female,11/27/1991,1:59 PM,64088,6.155,True,Legal
89,Janice,Female,03-12-16,12:40 AM,51082,11.955,False,Legal
90,Janice,NaN,8/21/1997,5:12 AM,91719,11.583,True,Legal
91,James,NaN,1/26/2005,11:00 PM,128771,8.309,False,NaN
92,Linda,Female,5/25/2000,5:45 PM,119009,12.506,True,Business Development
93,Virginia,NaN,05-07-94,5:58 PM,111858,1.601,True,Legal
94,Harry,Male,8/26/1981,3:16 PM,130620,7.030,False,Legal
95,Heather,Female,07-11-98,2:17 PM,43026,14.166,False,Client Services
96,Cynthia,Female,3/21/1994,8:34 AM,142321,1.737,False,Finance
97,Laura,NaN,7/19/2014,9:23 PM,140371,10.620,True,Marketing
98,Tina,Female,6/16/2016,7:47 PM,100705,16.961,True,Marketing
99,Harold,Male,01-02-85,9:40 PM,77544,12.447,False,Business Development
100,Melissa,Female,6/21/2005,6:33 AM,48109,14.995,False,Finance
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
102,Jack,Male,01-12-97,5:51 AM,103902,12.159,False,Client Services
103,Phyllis,Female,10-11-96,9:30 PM,136984,8.932,True,Finance
104,John,Male,12/23/1989,7:01 AM,80740,19.305,False,Marketing
105,Kathy,Female,03-09-96,4:33 AM,91712,8.567,False,Finance
106,Paul,Male,08-04-93,7:25 PM,42146,3.046,False,Legal
107,Steven,Male,4/23/2013,10:12 PM,68680,16.565,False,Legal
108,Russell,NaN,05-05-88,7:57 AM,133980,12.396,True,Legal
109,Christopher,Male,4/22/2000,10:15 AM,37919,11.449,False,NaN
110,Shirley,Female,6/20/2001,10:39 PM,147113,16.135,False,Legal
111,Bonnie,Female,12/17/1999,3:12 PM,42153,8.454,True,Business Development
112,Willie,Male,11/27/2003,6:21 AM,64363,4.023,False,Marketing
113,Tina,Female,06-12-09,7:16 AM,114767,3.711,True,Engineering
114,Ashley,Female,08-04-02,11:00 AM,58698,6.811,True,Business Development
115,Pamela,Female,07-01-82,6:51 AM,54585,4.166,False,Product
116,NaN,Male,6/22/1991,8:58 PM,76189,18.988,NaN,Legal
117,Steven,Male,03-01-95,3:03 PM,109095,9.494,False,Finance
118,Andrea,Female,01-12-12,5:43 AM,120204,9.557,False,Business Development
119,Paul,Male,06-03-08,3:05 PM,41054,12.299,False,Marketing
120,Peter,Male,11/17/1994,6:15 PM,84885,15.402,False,Business Development
121,Kathleen,NaN,05-09-16,8:55 AM,119735,18.740,False,Product
122,Christina,Female,4/13/2012,2:04 PM,110169,13.892,True,Engineering
123,Helen,Female,11/29/2001,2:30 AM,73789,14.841,True,Product
124,Marilyn,Female,11/16/1983,8:29 AM,76078,2.401,True,Product
125,Patricia,Female,09-01-03,6:46 AM,49368,14.226,False,Human Resources
126,Michelle,Female,3/30/1984,6:43 PM,57325,17.179,True,Human Resources
127,William,Male,9/29/2002,4:09 PM,66521,5.830,False,Human Resources
128,Kenneth,Male,8/25/1987,9:16 PM,127654,16.439,True,Client Services
129,Antonio,Male,10/25/1988,1:50 PM,60866,13.101,True,Business Development
130,Shirley,Female,05-01-84,1:15 PM,41334,6.219,True,Human Resources
131,Rebecca,Female,07-10-92,12:23 AM,94231,17.517,False,Product
132,Carlos,Male,01-04-95,7:02 AM,146670,10.763,False,Human Resources
133,Lois,Female,12/25/1987,4:16 PM,106317,2.235,True,Client Services
134,Carolyn,Female,04-09-11,5:38 AM,109260,2.650,True,Business Development
135,Gloria,Female,6/29/2007,5:34 AM,134148,8.833,True,Legal
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
137,Adam,Male,5/21/2011,1:45 AM,95327,15.120,False,Distribution
138,Ashley,Female,5/25/2006,11:30 AM,112238,6.030,True,Engineering
139,NaN,Female,10-03-90,1:08 AM,132373,10.527,NaN,NaN
140,Shirley,Female,2/28/1981,1:23 PM,113850,1.854,False,Marketing
141,Adam,Male,12/24/1990,8:57 PM,110194,14.727,True,Product
142,Elizabeth,Female,10-09-03,5:53 PM,146129,5.687,False,Finance
143,Teresa,NaN,1/28/2016,10:55 AM,140013,8.689,True,Engineering
144,Nicole,NaN,03-05-82,2:28 PM,122717,12.452,False,Sales
145,Jennifer,Female,04-04-09,10:47 PM,71715,13.079,True,Client Services
146,Patricia,Female,11/25/1992,2:24 AM,95322,4.150,False,Product
147,Philip,Male,7/17/2008,1:30 PM,89227,3.996,False,Legal
148,Patrick,NaN,7/14/1991,2:24 AM,124488,14.837,True,Sales
149,NaN,Female,8/17/2014,2:00 PM,86230,8.578,NaN,Distribution
150,Sean,Male,05-04-96,8:59 PM,135490,19.934,False,Marketing
151,Brandon,NaN,11-03-97,8:17 PM,121333,15.295,False,Business Development
152,Ruth,Female,8/19/1999,4:03 AM,129297,8.067,True,Client Services
153,Victor,NaN,03-10-11,8:40 PM,84546,10.489,True,Finance
154,Rebecca,Female,11/15/1980,4:13 AM,85730,5.359,True,Product
155,Marie,Female,3/16/2003,12:12 AM,104058,17.695,True,Business Development
156,Howard,Male,4/27/1992,1:10 AM,105062,1.563,False,Human Resources
157,NaN,Female,7/27/2005,8:32 AM,79536,14.443,NaN,Product
158,Norma,Female,2/28/1999,8:45 PM,114412,8.756,True,Marketing
159,James,NaN,11/22/1983,10:52 PM,68501,14.316,False,Marketing
160,Kathy,Female,3/18/2000,7:26 PM,149563,16.991,True,Finance
161,Marilyn,NaN,8/22/1999,9:09 AM,103386,11.451,False,Distribution
162,Arthur,Male,4/13/1998,11:28 AM,89786,14.422,True,Legal
163,Terry,Male,09-03-90,9:15 PM,52226,19.135,False,Client Services
164,Mary,Female,8/13/1999,1:03 AM,134645,18.197,False,Business Development
165,NaN,Female,3/23/2014,1:28 PM,59148,9.061,NaN,Legal
166,NaN,Female,07-09-91,6:52 PM,42341,7.014,NaN,Sales
167,Christopher,Male,12/24/2011,12:22 PM,142178,17.984,True,Sales
168,Peter,NaN,09-03-87,5:59 PM,38989,7.017,True,Marketing
169,Michelle,Female,11-04-96,9:34 PM,53754,5.455,True,Product
170,Irene,Female,1/29/1992,11:36 AM,133772,19.020,True,Sales
171,Patrick,Male,8/17/2007,3:16 AM,143499,17.495,True,Engineering
172,Sara,Female,9/23/1991,6:17 PM,97058,9.402,False,Finance
173,Lillian,Female,12/21/2008,6:51 PM,85446,3.959,True,Engineering
174,NaN,NaN,9/18/2007,6:59 PM,40297,6.185,NaN,Client Services
175,Willie,Male,2/17/1998,8:20 PM,146651,1.451,True,Engineering
176,Victor,Male,01-08-03,1:02 PM,124486,10.166,False,Product
177,Wayne,Male,04-07-12,8:00 AM,102652,14.085,True,Distribution
178,Jane,Female,09-03-97,2:01 AM,144474,17.648,False,Product
179,Jessica,Female,10/23/1995,5:53 AM,68759,19.343,True,Finance
180,Mark,Male,04-12-08,5:40 PM,57286,5.025,True,Business Development
181,Randy,Male,11/14/1999,12:12 PM,58129,1.952,True,Distribution
182,Lillian,Female,6/19/1999,4:44 PM,123940,12.184,True,Business Development
183,Ruth,NaN,5/18/1999,5:56 AM,98233,2.518,True,Distribution
184,Jerry,Male,12/18/2003,6:46 AM,140810,9.177,True,Client Services
185,Sandra,Female,1/19/1983,7:25 AM,42090,8.842,True,Legal
186,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales
187,Roger,Male,11/19/2004,3:55 PM,51430,6.460,False,Marketing
188,Charles,Male,10/14/2000,9:40 PM,71749,15.931,False,Legal
189,Clarence,Male,05-02-98,3:16 AM,85700,1.215,False,Sales
190,Carol,Female,3/19/1996,3:39 AM,57783,9.129,False,Finance
191,Lois,Female,10/18/2013,4:51 PM,36946,6.652,False,Engineering
192,Barbara,NaN,05-03-03,7:32 PM,99326,16.475,True,Legal
193,Rebecca,Female,2/18/1995,6:50 AM,109259,4.443,True,Legal
194,Irene,Female,1/30/2004,8:25 PM,131038,8.996,False,Distribution
195,Ronald,Male,4/30/2014,2:19 PM,121068,12.757,True,Product
196,Steven,Male,11-10-85,10:53 AM,62719,19.127,False,Client Services
197,Carolyn,Female,11-06-12,3:51 AM,69268,3.031,False,Client Services
198,Maria,Female,12/27/1990,9:57 PM,36067,9.640,True,Product
199,Jonathan,Male,7/17/2009,8:15 AM,130581,16.736,True,NaN
200,Gary,Male,08-12-87,12:04 AM,89661,8.525,False,Finance
201,Kimberly,Female,7/15/1997,5:57 AM,36643,7.953,False,Marketing
202,Roger,Male,11-08-82,2:32 AM,140558,5.084,True,Sales
203,Diana,Female,01-04-13,7:53 AM,103521,2.784,True,Business Development
204,Willie,Male,06-06-06,9:45 AM,55281,4.935,True,Marketing
205,Brandon,Male,3/27/2006,5:54 PM,115711,8.012,True,Finance
206,Patricia,Female,12-06-12,4:01 AM,114079,8.399,True,Client Services
207,Katherine,Female,11/14/1999,8:15 AM,57531,1.767,False,Client Services
208,Jonathan,Male,10-12-87,2:59 AM,141069,4.903,False,Human Resources
209,Emily,Female,9/20/2007,11:25 AM,89434,11.295,False,Engineering
210,Ruth,Female,08-12-86,7:29 PM,44639,9.148,True,Legal
211,Linda,Female,6/24/2006,12:04 PM,110967,19.612,True,Human Resources
212,Lisa,Female,11-02-09,9:42 AM,115387,1.821,False,Client Services
213,Evelyn,Female,5/24/1980,11:10 PM,81673,15.364,True,Engineering
214,Julie,Female,7/23/1989,1:52 PM,109588,3.550,False,Engineering
215,Mary,Female,5/30/2009,11:41 PM,92544,3.800,False,Client Services
216,Matthew,Male,7/31/2013,8:04 AM,142373,2.462,False,Marketing
217,Douglas,Male,09-03-99,4:00 PM,83341,1.015,True,Client Services
218,Gregory,NaN,6/15/1992,5:08 AM,98865,10.628,True,Finance
219,Billy,Male,3/13/1995,12:05 PM,120444,7.768,True,Finance
220,NaN,Female,6/17/1991,12:49 PM,71945,5.560,NaN,Marketing
221,Gregory,Male,1/29/2000,6:01 AM,109564,3.845,False,Legal
222,Jason,Male,10/17/1999,10:09 PM,78417,3.067,False,Finance
223,Daniel,Male,4/30/2010,3:48 AM,106947,15.866,True,Legal
224,Sarah,Female,9/14/1995,7:50 AM,87298,2.311,False,Distribution
225,Harry,Male,10-01-15,7:47 PM,64579,15.266,True,Sales
226,Kathy,Female,4/19/1995,12:46 AM,50905,9.404,True,Finance
227,Todd,Male,4/13/1999,10:31 AM,59728,11.226,True,Client Services
228,Bobby,Male,9/23/1994,1:29 AM,51685,17.445,True,Engineering
229,Jeremy,Male,06-08-00,12:15 AM,49542,1.679,True,Distribution
230,George,NaN,2/24/1988,11:29 AM,38375,8.999,False,Legal
231,Diane,Female,4/18/1993,3:22 AM,64084,17.018,False,Product
232,Marilyn,Female,04-04-97,9:28 PM,147663,10.263,False,Human Resources
233,Kathryn,Female,02-04-04,1:47 PM,73935,14.752,False,Sales
234,Irene,Female,02-04-82,5:26 PM,40837,12.182,True,Client Services
235,Norma,Female,02-11-15,11:44 PM,94393,3.643,True,Engineering
236,Laura,Female,04-02-06,1:57 PM,42087,2.624,False,Product
237,Cheryl,Female,9/23/2008,2:57 AM,52080,9.375,False,Legal
238,Kevin,Male,3/25/1982,7:31 AM,35061,5.128,False,Legal
239,Lillian,NaN,05-12-16,3:43 PM,64164,17.612,False,Human Resources
240,Phyllis,NaN,4/21/1984,7:05 PM,94088,19.107,False,Distribution
241,Walter,Male,07-06-83,11:54 PM,127813,5.961,False,Finance
242,Robert,Male,10/27/1990,7:15 PM,38041,18.428,True,Engineering
243,Jimmy,Male,10-07-86,5:53 PM,126310,5.413,True,Product
244,Clarence,Male,10-08-96,12:53 PM,142561,8.866,False,Client Services
245,Victor,Male,04-11-91,7:44 AM,70817,17.138,False,Engineering
246,Fred,NaN,12-02-84,2:03 PM,59937,12.045,True,Human Resources
247,Brenda,NaN,7/27/2010,11:07 PM,106115,3.742,True,Product
248,Justin,Male,12-06-92,5:58 PM,82782,4.366,True,Distribution
249,Betty,Female,06-12-02,3:59 AM,104896,19.550,True,Business Development
250,Randy,NaN,02-06-86,3:04 PM,133943,8.940,True,Sales
251,Sharon,NaN,03-01-90,3:46 AM,83658,6.513,False,Business Development
252,Ralph,Male,11-11-04,1:35 AM,71896,4.232,True,Marketing
253,NaN,NaN,4/28/2003,3:01 AM,113732,10.391,NaN,Sales
254,Edward,Male,5/27/1985,10:13 PM,110485,7.995,False,Client Services
255,Denise,Female,3/20/2009,7:57 AM,115118,5.108,False,Human Resources
256,Debra,Female,3/13/1998,11:16 PM,48696,4.750,False,Legal
257,NaN,Male,11/25/1999,6:16 AM,42676,15.517,NaN,Sales
258,Michael,Male,1/24/2002,3:04 AM,43586,12.659,False,NaN
259,Henry,Male,02-06-95,8:34 AM,89258,15.585,True,Human Resources
260,Gloria,Female,3/27/2007,1:44 AM,90730,2.491,False,Distribution
261,Marie,Female,08-06-95,1:58 PM,100308,13.677,False,Product
262,Anne,Female,7/16/1986,2:08 PM,69134,3.723,True,Engineering
263,Sarah,NaN,11/21/1985,1:08 PM,58295,14.603,True,Engineering
264,Stephanie,Female,3/24/1983,11:15 AM,50141,13.218,True,Human Resources
265,Roy,Male,9/23/2004,1:31 PM,101941,3.450,False,Client Services
266,NaN,Female,08-05-09,8:14 AM,115145,14.063,NaN,Distribution
267,NaN,Male,02-04-05,1:01 PM,40451,16.044,NaN,Distribution
268,Irene,Female,03-03-82,8:26 AM,56526,5.810,True,Finance
269,NaN,Female,08-02-92,8:35 PM,145316,18.517,NaN,Human Resources
270,Thomas,Male,04-06-11,1:04 PM,103235,9.554,True,Human Resources
271,Frank,NaN,11/20/2001,10:18 AM,58563,12.062,True,Marketing
272,Fred,Male,2/20/1980,2:25 AM,74129,18.225,False,Product
273,Nicholas,Male,04-12-94,8:21 PM,74669,1.113,True,Product
274,Howard,Male,10-05-82,7:22 AM,97490,5.460,True,Marketing
275,Debra,Female,2/22/1994,10:25 PM,104250,18.456,True,Business Development
276,Christine,Female,07-03-89,4:01 AM,94345,11.996,False,Finance
277,Brenda,NaN,5/29/1991,6:32 AM,82439,19.062,False,Sales
278,Betty,Female,6/28/2005,6:03 PM,51613,12.984,False,Distribution
279,Ruby,Female,11-08-00,7:35 PM,105946,1.139,False,Business Development
280,Kevin,Male,07-12-97,2:07 AM,46080,9.635,False,Business Development
281,Arthur,Male,01-01-14,7:46 PM,134610,6.147,True,Human Resources
282,Carl,NaN,02-07-14,3:57 AM,125104,12.345,False,Client Services
283,Todd,Male,03-11-09,3:43 AM,107281,1.612,True,Engineering
284,Brenda,Female,10-06-05,9:33 PM,141521,4.337,False,Client Services
285,Judy,Female,9/16/1997,12:10 AM,65931,2.304,False,Human Resources
286,Todd,Male,02-02-84,10:13 AM,69989,10.985,True,Finance
287,Lois,Female,11-09-11,7:06 AM,147183,9.999,True,Client Services
288,Walter,NaN,12/21/1999,10:33 PM,66757,18.099,False,Distribution
289,Jessica,Female,9/27/1985,1:35 PM,75145,6.388,True,Legal
290,Jeremy,Male,6/14/1988,6:20 PM,129460,13.657,True,NaN
291,Tammy,Female,11-11-84,10:30 AM,132839,17.463,True,Client Services
292,Anne,Female,03-07-00,6:45 AM,44537,18.284,True,Client Services
293,Jesse,Male,10/25/1999,3:35 PM,118733,9.653,False,Marketing
294,Virginia,Female,10/20/1999,6:23 AM,46905,19.154,False,Distribution
295,Jesse,Male,03-02-81,7:26 PM,79582,3.873,False,Legal
296,Jeremy,NaN,11-10-96,1:49 PM,55394,3.180,True,Sales
297,Daniel,Male,9/15/2007,10:16 PM,123811,7.664,True,Human Resources
298,Patrick,NaN,8/30/2004,11:43 AM,137314,4.542,True,Marketing
299,Emily,Female,1/13/1988,6:42 AM,36711,19.028,True,Human Resources
300,Alan,Male,6/26/1988,3:54 AM,111786,3.592,True,Engineering
301,James,Male,07-11-15,8:52 PM,72257,13.023,False,Engineering
302,Adam,Male,07-05-07,11:59 AM,71276,5.027,True,Human Resources
303,Joan,NaN,7/25/1980,12:22 PM,38712,3.657,False,Client Services
304,Jeremy,Male,08-12-81,12:05 AM,46930,18.702,True,Finance
305,Margaret,Female,02-06-93,1:05 PM,125220,3.733,False,Marketing
306,Mark,Male,04-01-84,1:21 PM,121477,17.440,True,Business Development
307,Marilyn,Female,9/26/1981,2:23 AM,86386,2.937,False,Distribution
308,Cheryl,Female,09-08-09,10:16 AM,81308,2.196,True,Legal
309,Benjamin,Male,09-11-84,6:37 AM,84810,15.794,False,Marketing
310,Harold,Male,2/20/1990,11:00 PM,66775,2.158,True,Legal
311,Ernest,NaN,1/18/2002,1:51 AM,72145,13.448,True,Finance
312,Gerald,Male,4/16/2001,10:09 PM,121604,1.923,True,Sales

In [18]:
df.shape #--> (No. of rows, No. of columns)

(730, 16)

In [19]:
df.columns ##--> Return list of all the columns present in the data

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [17]:
## Information summary of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [21]:
#Object is string column

In [19]:
## Fetch one column from the dataframe
df["Gender"]

0        Male
1        Male
2      Female
3        Male
4        Male
5        Male
6      Female
7      Female
8      Female
9      Female
10     Female
11     Female
12       Male
13       Male
14     Female
15     Female
16       Male
17       Male
18     Female
19     Female
20        NaN
21       Male
22        NaN
23       Male
24       Male
25       Male
26       Male
27        NaN
28       Male
29       Male
30     Female
31        NaN
32       Male
33     Female
34       Male
35     Female
36     Female
37     Female
38     Female
39       Male
40       Male
41        NaN
42     Female
43     Female
44     Female
45       Male
46       Male
47     Female
48       Male
49        NaN
50     Female
51        NaN
52       Male
53        NaN
54     Female
55     Female
56       Male
57       Male
58     Female
59     Female
60        NaN
61     Female
62     Female
63       Male
64        NaN
65       Male
66     Female
67     Female
68       Male
69        NaN
70        NaN
71       Male
72       Male
73     Female
74       Male
75     Female
76     Female
77       Male
78     Female
79     Female
80        NaN
81       Male
82       Male
83       Male
84     Female
85       Male
86        NaN
87     Female
88     Female
89     Female
90        NaN
91        NaN
92     Female
93        NaN
94       Male
95     Female
96     Female
97        NaN
98     Female
99       Male
100    Female
101      Male
102      Male
103    Female
104      Male
105    Female
106      Male
107      Male
108       NaN
109      Male
110    Female
111    Female
112      Male
113    Female
114    Female
115    Female
116      Male
117      Male
118    Female
119      Male
120      Male
121       NaN
122    Female
123    Female
124    Female
125    Female
126    Female
127      Male
128      Male
129      Male
130    Female
131    Female
132      Male
133    Female
134    Female
135    Female
136      Male
137      Male
138    Female
139    Female
140    Female
141      Male
142    Female
143       NaN
144       NaN
145    Female
146    Female
147      Male
148       NaN
149    Female
150      Male
151       NaN
152    Female
153       NaN
154    Female
155    Female
156      Male
157    Female
158    Female
159       NaN
160    Female
161       NaN
162      Male
163      Male
164    Female
165    Female
166    Female
167      Male
168       NaN
169    Female
170    Female
171      Male
172    Female
173    Female
174       NaN
175      Male
176      Male
177      Male
178    Female
179    Female
180      Male
181      Male
182    Female
183       NaN
184      Male
185    Female
186    Female
187      Male
188      Male
189      Male
190    Female
191    Female
192       NaN
193    Female
194    Female
195      Male
196      Male
197    Female
198    Female
199      Male
200      Male
201    Female
202      Male
203    Female
204      Male
205      Male
206    Female
207    Female
208      Male
209    Female
210    Female
211    Female
212    Female
213    Female
214    Female
215    Female
216      Male
217      Male
218       NaN
219      Male
220    Female
221      Male
222      Male
223      Male
224    Female
225      Male
226    Female
227      Male
228      Male
229      Male
230       NaN
231    Female
232    Female
233    Female
234    Female
235    Female
236    Female
237    Female
238      Male
239       NaN
240       NaN
241      Male
242      Male
243      Male
244      Male
245      Male
246       NaN
247       NaN
248      Male
249    Female
250       NaN
251       NaN
252      Male
253       NaN
254      Male
255    Female
256    Female
257      Male
258      Male
259      Male
260    Female
261    Female
262    Female
263       NaN
264    Female
265      Male
266    Female
267      Male
268    Female
269    Female
270      Male
271       NaN
272      Male
273      Male
274      Male
275    Female
276    Female
277       NaN
278    Female
279    Female
280      Male
281      Male
282       NaN
283      Male
284    Female
285    Female
286      Male
287    Female
288       NaN
289    Female
290      Male
291    Female
292    Female
293      Male
294    Female
295      Male
296       NaN
297      Male
298       NaN
299    Female
300      Male
301      Male
302      Male
303       NaN
304      Male
305    Female
306      Male
307    Female
308    Female
309      Male
310      Male
311       NaN
312      Male
313    Female
314      Male
315       NaN
316    Female
317    Female
318      Male
319    Female
320    Female
321    Female
322      Male
323    Female
324    Female
325      Male
326      Male
327      Male
328      Male
329      Male
330      Male
331    Female
332      Male
333    Female
334      Male
335      Male
336      Male
337      Male
338      Male
339      Male
340      Male
341      Male
342    Female
343      Male
344      Male
345      Male
346      Male
347    Female
348      Male
349    Female
350       NaN
351    Female
352      Male
353      Male
354    Female
355    Female
356    Female
357      Male
358      Male
359    Female
360    Female
361    Female
362      Male
363       NaN
364      Male
365       NaN
366       NaN
367      Male
368    Female
369    Female
370    Female
371      Male
372      Male
373      Male
374    Female
375       NaN
376      Male
377      Male
378      Male
379    Female
380       NaN
381      Male
382    Female
383      Male
384      Male
385    Female
386    Female
387      Male
388    Female
389       NaN
390       NaN
391    Female
392      Male
393       NaN
394    Female
395    Female
396    Female
397      Male
398    Female
399    Female
400       NaN
401    Female
402       NaN
403      Male
404       NaN
405    Female
406    Female
407       NaN
408      Male
409      Male
410      Male
411      Male
412    Female
413      Male
414      Male
415       NaN
416      Male
417       NaN
418    Female
419    Female
420      Male
421      Male
422      Male
423    Female
424       NaN
425    Female
426      Male
427      Male
428      Male
429    Female
430    Female
431      Male
432       NaN
433    Female
434    Female
435      Male
436    Female
437    Female
438      Male
439      Male
440      Male
441    Female
442    Female
443    Female
444      Male
445      Male
446    Female
447      Male
448      Male
449    Female
450      Male
451       NaN
452      Male
453    Female
454      Male
455    Female
456       NaN
457    Female
458      Male
459       NaN
460    Female
461      Male
462      Male
463      Male
464      Male
465    Female
466      Male
467    Female
468    Female
469      Male
470      Male
471    Female
472      Male
473      Male
474      Male
475    Female
476    Female
477      Male
478      Male
479      Male
480    Female
481    Female
482       NaN
483    Female
484      Male
485    Female
486      Male
487    Female
488      Male
489    Female
490    Female
491       NaN
492      Male
493      Male
494    Female
495      Male
496      Male
497      Male
498    Female
499       NaN
500    Female
501      Male
502    Female
503      Male
504    Female
505      Male
506      Male
507      Male
508      Male
509    Female
510      Male
511      Male
512    Female
513      Male
514       NaN
515      Male
516    Female
517    Female
518    Female
519      Male
520      Male
521       NaN
522    Female
523    Female
524       NaN
525      Male
526    Female
527       NaN
528       NaN
529      Male
530    Female
531    Female
532    Female
533      Male
534       NaN
535    Female
536      Male
537    Female
538      Male
539      Male
540    Female
541    Female
542    Female
543    Female
544      Male
545       NaN
546      Male
547    Female
548    Female
549    Female
550      Male
551      Male
552    Female
553    Female
554       NaN
555    Female
556      Male
557    Female
558    Female
559    Female
560      Male
561    Female
562       NaN
563      Male
564      Male
565    Female
566      Male
567    Female
568    Female
569    Female
570    Female
571      Male
572      Male
573    Female
574    Female
575      Male
576      Male
577      Male
578    Female
579      Male
580      Male
581      Male
582      Male
583    Female
584      Male
585    Female
586    Female
587    Female
588    Female
589    Female
590    Female
591    Female
592      Male
593    Female
594      Male
595    Female
596      Male
597    Female
598    Female
599    Female
600       NaN
601       NaN
602       NaN
603       NaN
604      Male
605    Female
606    Female
607      Male
608    Female
609      Male
610      Male
611       NaN
612       NaN
613       NaN
614      Male
615      Male
616    Female
617    Female
618      Male
619    Female
620      Male
621      Male
622    Female
623    Female
624      Male
625    Female
626    Female
627    Female
628       NaN
629    Female
630      Male
631       NaN
632    Female
633    Female
634      Male
635      Male
636    Female
637      Male
638    Female
639       NaN
640    Female
641    Female
642       NaN
643      Male
644    Female
645       NaN
646    Female
647      Male
648      Male
649    Female
650    Female
651    Female
652      Male
653    Female
654      Male
655      Male
656    Female
657    Female
658    Female
659       NaN
660       NaN
661      Male
662    Female
663    Female
664      Male
665      Male
666       NaN
667       NaN
668      Male
669       NaN
670    Female
671    Female
672      Male
673      Male
674      Male
675    Female
676    Female
677    Female
678    Female
679    Female
680      Male
681      Male
682    Female
683       NaN
684    Female
685      Male
686       NaN
687      Male
688      Male
689       NaN
690      Male
691    Female
692      Male
693    Female
694    Female
695    Female
696      Male
697      Male
698       NaN
699       NaN
700      Male
701       NaN
702    Female
703       NaN
704      Male
705      Male
706      Male
707    Female
708      Male
709      Male
710      Male
711    Female
712       NaN
713    Female
714      Male
715      Male
716      Male
717       NaN
718      Male
719      Male
720    Female
721      Male
722      Male
723       NaN
724    Female
725      Male
726      Male
727      Male
728    Female
729      Male
730    Female
731    Female
732      Male
733      Male
734    Female
735    Female
736    Female
737      Male
738      Male
739      Male
740       NaN
741    Female
742      Male
743      Male
744       NaN
745      Male
746    Female
747      Male
748    Female
749       NaN
750       NaN
751    Female
752      Male
753      Male
754    Female
755    Female
756      Male
757      Male
758       NaN
759    Female
760      Male
761    Female
762      Male
763    Female
764      Male
765       NaN
766      Male
767    Female
768    Female
769       NaN
770    Female
771      Male
772    Female
773      Male
774    Female
775    Female
776      Male
777    Female
778      Male
779    Female
780      Male
781      Male
782      Male
783       NaN
784    Female
785    Female
786    Female
787      Male
788       NaN
789    Female
790      Male
791      Male
792       NaN
793    Female
794    Female
795       NaN
796    Female
797    Female
798      Male
799      Male
800      Male
801      Male
802    Female
803    Female
804      Male
805      Male
806    Female
807    Female
808    Female
809      Male
810      Male
811    Female
812      Male
813    Female
814    Female
815       NaN
816    Female
817    Female
818    Female
819      Male
820      Male
821    Female
822    Female
823      Male
824    Female
825       NaN
826       NaN
827       NaN
828    Female
829      Male
830      Male
831      Male
832      Male
833      Male
834       NaN
835      Male
836    Female
837      Male
838      Male
839    Female
840    Female
841    Female
842    Female
843    Female
844       NaN
845    Female
846      Male
847       NaN
848      Male
849      Male
850      Male
851      Male
852    Female
853    Female
854      Male
855       NaN
856       NaN
857    Female
858      Male
859    Female
860      Male
861      Male
862      Male
863      Male
864      Male
865    Female
866    Female
867      Male
868    Female
869      Male
870       NaN
871      Male
872    Female
873      Male
874    Female
875    Female
876       NaN
877      Male
878    Female
879    Female
880       NaN
881    Female
882       NaN
883    Female
884    Female
885      Male
886      Male
887      Male
888    Female
889    Female
890      Male
891      Male
892      Male
893      Male
894    Female
895       NaN
896      Male
897       NaN
898    Female
899      Male
900    Female
901    Female
902      Male
903    Female
904    Female
905    Female
906    Female
907    Female
908    Female
909      Male
910    Female
911      Male
912      Male
913    Female
914    Female
915      Male
916    Female
917      Male
918      Male
919      Male
920    Female
921      Male
922      Male
923       NaN
924    Female
925    Female
926    Female
927      Male
928      Male
929    Female
930    Female
931      Male
932    Female
933    Female
934      Male
935    Female
936    Female
937       NaN
938       NaN
939       NaN
940      Male
941      Male
942    Female
943      Male
944      Male
945       NaN
946    Female
947      Male
948    Female
949      Male
950    Female
951    Female
952    Female
953      Male
954      Male
955    Female
956    Female
957      Male
958    Female
959      Male
960      Male
961       NaN
962      Male
963    Female
964      Male
965    Female
966      Male
967      Male
968    Female
969    Female
970    Female
971      Male
972       NaN
973      Male
974      Male
975    Female
976    Female
977    Female
978      Male
979      Male
980    Female
981      Male
982    Female
983      Male
984    Female
985       NaN
986    Female
987    Female
988    Female
989       NaN
990    Female
991    Female
992      Male
993    Female
994      Male
995       NaN
996      Male
997      Male
998      Male
999      Male
Name: Gender, dtype: object

In [20]:
# This method only works if space is not there in column name
df.Gender

0        Male
1        Male
2      Female
3        Male
4        Male
5        Male
6      Female
7      Female
8      Female
9      Female
10     Female
11     Female
12       Male
13       Male
14     Female
15     Female
16       Male
17       Male
18     Female
19     Female
20        NaN
21       Male
22        NaN
23       Male
24       Male
25       Male
26       Male
27        NaN
28       Male
29       Male
30     Female
31        NaN
32       Male
33     Female
34       Male
35     Female
36     Female
37     Female
38     Female
39       Male
40       Male
41        NaN
42     Female
43     Female
44     Female
45       Male
46       Male
47     Female
48       Male
49        NaN
50     Female
51        NaN
52       Male
53        NaN
54     Female
55     Female
56       Male
57       Male
58     Female
59     Female
60        NaN
61     Female
62     Female
63       Male
64        NaN
65       Male
66     Female
67     Female
68       Male
69        NaN
70        NaN
71       Male
72       Male
73     Female
74       Male
75     Female
76     Female
77       Male
78     Female
79     Female
80        NaN
81       Male
82       Male
83       Male
84     Female
85       Male
86        NaN
87     Female
88     Female
89     Female
90        NaN
91        NaN
92     Female
93        NaN
94       Male
95     Female
96     Female
97        NaN
98     Female
99       Male
100    Female
101      Male
102      Male
103    Female
104      Male
105    Female
106      Male
107      Male
108       NaN
109      Male
110    Female
111    Female
112      Male
113    Female
114    Female
115    Female
116      Male
117      Male
118    Female
119      Male
120      Male
121       NaN
122    Female
123    Female
124    Female
125    Female
126    Female
127      Male
128      Male
129      Male
130    Female
131    Female
132      Male
133    Female
134    Female
135    Female
136      Male
137      Male
138    Female
139    Female
140    Female
141      Male
142    Female
143       NaN
144       NaN
145    Female
146    Female
147      Male
148       NaN
149    Female
150      Male
151       NaN
152    Female
153       NaN
154    Female
155    Female
156      Male
157    Female
158    Female
159       NaN
160    Female
161       NaN
162      Male
163      Male
164    Female
165    Female
166    Female
167      Male
168       NaN
169    Female
170    Female
171      Male
172    Female
173    Female
174       NaN
175      Male
176      Male
177      Male
178    Female
179    Female
180      Male
181      Male
182    Female
183       NaN
184      Male
185    Female
186    Female
187      Male
188      Male
189      Male
190    Female
191    Female
192       NaN
193    Female
194    Female
195      Male
196      Male
197    Female
198    Female
199      Male
200      Male
201    Female
202      Male
203    Female
204      Male
205      Male
206    Female
207    Female
208      Male
209    Female
210    Female
211    Female
212    Female
213    Female
214    Female
215    Female
216      Male
217      Male
218       NaN
219      Male
220    Female
221      Male
222      Male
223      Male
224    Female
225      Male
226    Female
227      Male
228      Male
229      Male
230       NaN
231    Female
232    Female
233    Female
234    Female
235    Female
236    Female
237    Female
238      Male
239       NaN
240       NaN
241      Male
242      Male
243      Male
244      Male
245      Male
246       NaN
247       NaN
248      Male
249    Female
250       NaN
251       NaN
252      Male
253       NaN
254      Male
255    Female
256    Female
257      Male
258      Male
259      Male
260    Female
261    Female
262    Female
263       NaN
264    Female
265      Male
266    Female
267      Male
268    Female
269    Female
270      Male
271       NaN
272      Male
273      Male
274      Male
275    Female
276    Female
277       NaN
278    Female
279    Female
280      Male
281      Male
282       NaN
283      Male
284    Female
285    Female
286      Male
287    Female
288       NaN
289    Female
290      Male
291    Female
292    Female
293      Male
294    Female
295      Male
296       NaN
297      Male
298       NaN
299    Female
300      Male
301      Male
302      Male
303       NaN
304      Male
305    Female
306      Male
307    Female
308    Female
309      Male
310      Male
311       NaN
312      Male
313    Female
314      Male
315       NaN
316    Female
317    Female
318      Male
319    Female
320    Female
321    Female
322      Male
323    Female
324    Female
325      Male
326      Male
327      Male
328      Male
329      Male
330      Male
331    Female
332      Male
333    Female
334      Male
335      Male
336      Male
337      Male
338      Male
339      Male
340      Male
341      Male
342    Female
343      Male
344      Male
345      Male
346      Male
347    Female
348      Male
349    Female
350       NaN
351    Female
352      Male
353      Male
354    Female
355    Female
356    Female
357      Male
358      Male
359    Female
360    Female
361    Female
362      Male
363       NaN
364      Male
365       NaN
366       NaN
367      Male
368    Female
369    Female
370    Female
371      Male
372      Male
373      Male
374    Female
375       NaN
376      Male
377      Male
378      Male
379    Female
380       NaN
381      Male
382    Female
383      Male
384      Male
385    Female
386    Female
387      Male
388    Female
389       NaN
390       NaN
391    Female
392      Male
393       NaN
394    Female
395    Female
396    Female
397      Male
398    Female
399    Female
400       NaN
401    Female
402       NaN
403      Male
404       NaN
405    Female
406    Female
407       NaN
408      Male
409      Male
410      Male
411      Male
412    Female
413      Male
414      Male
415       NaN
416      Male
417       NaN
418    Female
419    Female
420      Male
421      Male
422      Male
423    Female
424       NaN
425    Female
426      Male
427      Male
428      Male
429    Female
430    Female
431      Male
432       NaN
433    Female
434    Female
435      Male
436    Female
437    Female
438      Male
439      Male
440      Male
441    Female
442    Female
443    Female
444      Male
445      Male
446    Female
447      Male
448      Male
449    Female
450      Male
451       NaN
452      Male
453    Female
454      Male
455    Female
456       NaN
457    Female
458      Male
459       NaN
460    Female
461      Male
462      Male
463      Male
464      Male
465    Female
466      Male
467    Female
468    Female
469      Male
470      Male
471    Female
472      Male
473      Male
474      Male
475    Female
476    Female
477      Male
478      Male
479      Male
480    Female
481    Female
482       NaN
483    Female
484      Male
485    Female
486      Male
487    Female
488      Male
489    Female
490    Female
491       NaN
492      Male
493      Male
494    Female
495      Male
496      Male
497      Male
498    Female
499       NaN
500    Female
501      Male
502    Female
503      Male
504    Female
505      Male
506      Male
507      Male
508      Male
509    Female
510      Male
511      Male
512    Female
513      Male
514       NaN
515      Male
516    Female
517    Female
518    Female
519      Male
520      Male
521       NaN
522    Female
523    Female
524       NaN
525      Male
526    Female
527       NaN
528       NaN
529      Male
530    Female
531    Female
532    Female
533      Male
534       NaN
535    Female
536      Male
537    Female
538      Male
539      Male
540    Female
541    Female
542    Female
543    Female
544      Male
545       NaN
546      Male
547    Female
548    Female
549    Female
550      Male
551      Male
552    Female
553    Female
554       NaN
555    Female
556      Male
557    Female
558    Female
559    Female
560      Male
561    Female
562       NaN
563      Male
564      Male
565    Female
566      Male
567    Female
568    Female
569    Female
570    Female
571      Male
572      Male
573    Female
574    Female
575      Male
576      Male
577      Male
578    Female
579      Male
580      Male
581      Male
582      Male
583    Female
584      Male
585    Female
586    Female
587    Female
588    Female
589    Female
590    Female
591    Female
592      Male
593    Female
594      Male
595    Female
596      Male
597    Female
598    Female
599    Female
600       NaN
601       NaN
602       NaN
603       NaN
604      Male
605    Female
606    Female
607      Male
608    Female
609      Male
610      Male
611       NaN
612       NaN
613       NaN
614      Male
615      Male
616    Female
617    Female
618      Male
619    Female
620      Male
621      Male
622    Female
623    Female
624      Male
625    Female
626    Female
627    Female
628       NaN
629    Female
630      Male
631       NaN
632    Female
633    Female
634      Male
635      Male
636    Female
637      Male
638    Female
639       NaN
640    Female
641    Female
642       NaN
643      Male
644    Female
645       NaN
646    Female
647      Male
648      Male
649    Female
650    Female
651    Female
652      Male
653    Female
654      Male
655      Male
656    Female
657    Female
658    Female
659       NaN
660       NaN
661      Male
662    Female
663    Female
664      Male
665      Male
666       NaN
667       NaN
668      Male
669       NaN
670    Female
671    Female
672      Male
673      Male
674      Male
675    Female
676    Female
677    Female
678    Female
679    Female
680      Male
681      Male
682    Female
683       NaN
684    Female
685      Male
686       NaN
687      Male
688      Male
689       NaN
690      Male
691    Female
692      Male
693    Female
694    Female
695    Female
696      Male
697      Male
698       NaN
699       NaN
700      Male
701       NaN
702    Female
703       NaN
704      Male
705      Male
706      Male
707    Female
708      Male
709      Male
710      Male
711    Female
712       NaN
713    Female
714      Male
715      Male
716      Male
717       NaN
718      Male
719      Male
720    Female
721      Male
722      Male
723       NaN
724    Female
725      Male
726      Male
727      Male
728    Female
729      Male
730    Female
731    Female
732      Male
733      Male
734    Female
735    Female
736    Female
737      Male
738      Male
739      Male
740       NaN
741    Female
742      Male
743      Male
744       NaN
745      Male
746    Female
747      Male
748    Female
749       NaN
750       NaN
751    Female
752      Male
753      Male
754    Female
755    Female
756      Male
757      Male
758       NaN
759    Female
760      Male
761    Female
762      Male
763    Female
764      Male
765       NaN
766      Male
767    Female
768    Female
769       NaN
770    Female
771      Male
772    Female
773      Male
774    Female
775    Female
776      Male
777    Female
778      Male
779    Female
780      Male
781      Male
782      Male
783       NaN
784    Female
785    Female
786    Female
787      Male
788       NaN
789    Female
790      Male
791      Male
792       NaN
793    Female
794    Female
795       NaN
796    Female
797    Female
798      Male
799      Male
800      Male
801      Male
802    Female
803    Female
804      Male
805      Male
806    Female
807    Female
808    Female
809      Male
810      Male
811    Female
812      Male
813    Female
814    Female
815       NaN
816    Female
817    Female
818    Female
819      Male
820      Male
821    Female
822    Female
823      Male
824    Female
825       NaN
826       NaN
827       NaN
828    Female
829      Male
830      Male
831      Male
832      Male
833      Male
834       NaN
835      Male
836    Female
837      Male
838      Male
839    Female
840    Female
841    Female
842    Female
843    Female
844       NaN
845    Female
846      Male
847       NaN
848      Male
849      Male
850      Male
851      Male
852    Female
853    Female
854      Male
855       NaN
856       NaN
857    Female
858      Male
859    Female
860      Male
861      Male
862      Male
863      Male
864      Male
865    Female
866    Female
867      Male
868    Female
869      Male
870       NaN
871      Male
872    Female
873      Male
874    Female
875    Female
876       NaN
877      Male
878    Female
879    Female
880       NaN
881    Female
882       NaN
883    Female
884    Female
885      Male
886      Male
887      Male
888    Female
889    Female
890      Male
891      Male
892      Male
893      Male
894    Female
895       NaN
896      Male
897       NaN
898    Female
899      Male
900    Female
901    Female
902      Male
903    Female
904    Female
905    Female
906    Female
907    Female
908    Female
909      Male
910    Female
911      Male
912      Male
913    Female
914    Female
915      Male
916    Female
917      Male
918      Male
919      Male
920    Female
921      Male
922      Male
923       NaN
924    Female
925    Female
926    Female
927      Male
928      Male
929    Female
930    Female
931      Male
932    Female
933    Female
934      Male
935    Female
936    Female
937       NaN
938       NaN
939       NaN
940      Male
941      Male
942    Female
943      Male
944      Male
945       NaN
946    Female
947      Male
948    Female
949      Male
950    Female
951    Female
952    Female
953      Male
954      Male
955    Female
956    Female
957      Male
958    Female
959      Male
960      Male
961       NaN
962      Male
963    Female
964      Male
965    Female
966      Male
967      Male
968    Female
969    Female
970    Female
971      Male
972       NaN
973      Male
974      Male
975    Female
976    Female
977    Female
978      Male
979      Male
980    Female
981      Male
982    Female
983      Male
984    Female
985       NaN
986    Female
987    Female
988    Female
989       NaN
990    Female
991    Female
992      Male
993    Female
994      Male
995       NaN
996      Male
997      Male
998      Male
999      Male
Name: Gender, dtype: object

In [21]:
## Fetch more than one column
df[["Gender","Salary","Team"]]
# [] --> indexing
# [] --> list of columns

     Gender  Salary                  Team
0      Male   97308             Marketing
1      Male   61933                   NaN
2    Female  130590               Finance
3      Male  138705               Finance
4      Male  101004       Client Services
5      Male  115163                 Legal
6    Female   65476               Product
7    Female   45906               Finance
8    Female   95570           Engineering
9    Female  139852  Business Development
10   Female   63241                   NaN
11   Female  102508                 Legal
12     Male  112807       Human Resources
13     Male  109831                 Sales
14   Female   41426               Finance
15   Female   59414               Product
16     Male   90370       Human Resources
17     Male  111737               Product
18   Female  132940       Client Services
19   Female   81014               Product
20      NaN   64714                 Legal
21     Male  100612             Marketing
22      NaN   90816       Client Services
23     Male  125792                   NaN
24     Male   97950       Client Services
25     Male   37076       Client Services
26     Male   37598             Marketing
27      NaN  122367                 Legal
28     Male  124008       Client Services
29     Male   79529                 Legal
30   Female  118780           Engineering
31      NaN   88657               Product
32     Male  122340                   NaN
33   Female  119082  Business Development
34     Male   95734       Client Services
35   Female   85182                 Sales
36   Female  142032  Business Development
37   Female   57427       Client Services
38   Female   36844  Business Development
39     Male  122173       Client Services
40     Male   99283          Distribution
41      NaN   66582  Business Development
42   Female  121918                 Legal
43   Female   73524             Marketing
44   Female  145146               Product
45     Male   88010                 Sales
46     Male  114796               Finance
47   Female   66820       Client Services
48     Male   93581  Business Development
49      NaN  113590                 Sales
50   Female   94976           Engineering
51      NaN   41126                 Sales
52     Male   49339       Human Resources
53      NaN   40341               Finance
54   Female   83677           Engineering
55   Female  102488               Product
56     Male  130276               Finance
57     Male   64715       Human Resources
58   Female   72670           Engineering
59   Female   66851           Engineering
60      NaN   48866          Distribution
61   Female  106862  Business Development
62   Female   58112             Marketing
63     Male   35203       Human Resources
64      NaN   77834  Business Development
65     Male   61310          Distribution
66   Female  125250  Business Development
67   Female   51178               Finance
68     Male   84834               Finance
69      NaN  100863               Finance
70      NaN   84692       Client Services
71     Male  118172                 Sales
72     Male   54043               Product
73   Female   90582                 Sales
74     Male   62096             Marketing
75   Female  104897       Human Resources
76   Female  131604          Distribution
77     Male  107391             Marketing
78   Female  114797                 Sales
79   Female  115814               Product
80      NaN  137126                 Sales
81     Male   47369                 Legal
82     Male   35095       Client Services
83     Male  148115               Finance
84   Female   83072               Finance
85     Male  100238       Client Services
86      NaN  103495  Business Development
87   Female  144887                 Sales
88   Female   64088                 Legal
89   Female   51082                 Legal
90      NaN   91719                 Legal
91      NaN  128771                   NaN
92   Female  119009  Business Development
93      NaN  111858                 Legal
94     Male  130620                 Legal
95   Female   43026       Client Services
96   Female  142321               Finance
97      NaN  140371             Marketing
98   Female  100705             Marketing
99     Male   77544  Business Development
100  Female   48109               Finance
101    Male   61602             Marketing
102    Male  103902       Client Services
103  Female  136984               Finance
104    Male   80740             Marketing
105  Female   91712               Finance
106    Male   42146                 Legal
107    Male   68680                 Legal
108     NaN  133980                 Legal
109    Male   37919                   NaN
110  Female  147113                 Legal
111  Female   42153  Business Development
112    Male   64363             Marketing
113  Female  114767           Engineering
114  Female   58698  Business Development
115  Female   54585               Product
116    Male   76189                 Legal
117    Male  109095               Finance
118  Female  120204  Business Development
119    Male   41054             Marketing
120    Male   84885  Business Development
121     NaN  119735               Product
122  Female  110169           Engineering
123  Female   73789               Product
124  Female   76078               Product
125  Female   49368       Human Resources
126  Female   57325       Human Resources
127    Male   66521       Human Resources
128    Male  127654       Client Services
129    Male   60866  Business Development
130  Female   41334       Human Resources
131  Female   94231               Product
132    Male  146670       Human Resources
133  Female  106317       Client Services
134  Female  109260  Business Development
135  Female  134148                 Legal
136    Male   43542                 Legal
137    Male   95327          Distribution
138  Female  112238           Engineering
139  Female  132373                   NaN
140  Female  113850             Marketing
141    Male  110194               Product
142  Female  146129               Finance
143     NaN  140013           Engineering
144     NaN  122717                 Sales
145  Female   71715       Client Services
146  Female   95322               Product
147    Male   89227                 Legal
148     NaN  124488                 Sales
149  Female   86230          Distribution
150    Male  135490             Marketing
151     NaN  121333  Business Development
152  Female  129297       Client Services
153     NaN   84546               Finance
154  Female   85730               Product
155  Female  104058  Business Development
156    Male  105062       Human Resources
157  Female   79536               Product
158  Female  114412             Marketing
159     NaN   68501             Marketing
160  Female  149563               Finance
161     NaN  103386          Distribution
162    Male   89786                 Legal
163    Male   52226       Client Services
164  Female  134645  Business Development
165  Female   59148                 Legal
166  Female   42341                 Sales
167    Male  142178                 Sales
168     NaN   38989             Marketing
169  Female   53754               Product
170  Female  133772                 Sales
171    Male  143499           Engineering
172  Female   97058               Finance
173  Female   85446           Engineering
174     NaN   40297       Client Services
175    Male  146651           Engineering
176    Male  124486               Product
177    Male  102652          Distribution
178  Female  144474               Product
179  Female   68759               Finance
180    Male   57286  Business Development
181    Male   58129          Distribution
182  Female  123940  Business Development
183     NaN   98233          Distribution
184    Male  140810       Client Services
185  Female   42090                 Legal
186  Female  149654                 Sales
187    Male   51430             Marketing
188    Male   71749                 Legal
189    Male   85700                 Sales
190  Female   57783               Finance
191  Female   36946           Engineering
192     NaN   99326                 Legal
193  Female  109259                 Legal
194  Female  131038          Distribution
195    Male  121068               Product
196    Male   62719       Client Services
197  Female   69268       Client Services
198  Female   36067               Product
199    Male  130581                   NaN
200    Male   89661               Finance
201  Female   36643             Marketing
202    Male  140558                 Sales
203  Female  103521  Business Development
204    Male   55281             Marketing
205    Male  115711               Finance
206  Female  114079       Client Services
207  Female   57531       Client Services
208    Male  141069       Human Resources
209  Female   89434           Engineering
210  Female   44639                 Legal
211  Female  110967       Human Resources
212  Female  115387       Client Services
213  Female   81673           Engineering
214  Female  109588           Engineering
215  Female   92544       Client Services
216    Male  142373             Marketing
217    Male   83341       Client Services
218     NaN   98865               Finance
219    Male  120444               Finance
220  Female   71945             Marketing
221    Male  109564                 Legal
222    Male   78417               Finance
223    Male  106947                 Legal
224  Female   87298          Distribution
225    Male   64579                 Sales
226  Female   50905               Finance
227    Male   59728       Client Services
228    Male   51685           Engineering
229    Male   49542          Distribution
230     NaN   38375                 Legal
231  Female   64084               Product
232  Female  147663       Human Resources
233  Female   73935                 Sales
234  Female   40837       Client Services
235  Female   94393           Engineering
236  Female   42087               Product
237  Female   52080                 Legal
238    Male   35061                 Legal
239     NaN   64164       Human Resources
240     NaN   94088          Distribution
241    Male  127813               Finance
242    Male   38041           Engineering
243    Male  126310               Product
244    Male  142561       Client Services
245    Male   70817           Engineering
246     NaN   59937       Human Resources
247     NaN  106115               Product
248    Male   82782          Distribution
249  Female  104896  Business Development
250     NaN  133943                 Sales
251     NaN   83658  Business Development
252    Male   71896             Marketing
253     NaN  113732                 Sales
254    Male  110485       Client Services
255  Female  115118       Human Resources
256  Female   48696                 Legal
257    Male   42676                 Sales
258    Male   43586                   NaN
259    Male   89258       Human Resources
260  Female   90730          Distribution
261  Female  100308               Product
262  Female   69134           Engineering
263     NaN   58295           Engineering
264  Female   50141       Human Resources
265    Male  101941       Client Services
266  Female  115145          Distribution
267    Male   40451          Distribution
268  Female   56526               Finance
269  Female  145316       Human Resources
270    Male  103235       Human Resources
271     NaN   58563             Marketing
272    Male   74129               Product
273    Male   74669               Product
274    Male   97490             Marketing
275  Female  104250  Business Development
276  Female   94345               Finance
277     NaN   82439                 Sales
278  Female   51613          Distribution
279  Female  105946  Business Development
280    Male   46080  Business Development
281    Male  134610       Human Resources
282     NaN  125104       Client Services
283    Male  107281           Engineering
284  Female  141521       Client Services
285  Female   65931       Human Resources
286    Male   69989               Finance
287  Female  147183       Client Services
288     NaN   66757          Distribution
289  Female   75145                 Legal
290    Male  129460                   NaN
291  Female  132839       Client Services
292  Female   44537       Client Services
293    Male  118733             Marketing
294  Female   46905          Distribution
295    Male   79582                 Legal
296     NaN   55394                 Sales
297    Male  123811       Human Resources
298     NaN  137314             Marketing
299  Female   36711       Human Resources
300    Male  111786           Engineering
301    Male   72257           Engineering
302    Male   71276       Human Resources
303     NaN   38712       Client Services
304    Male   46930               Finance
305  Female  125220             Marketing
306    Male  121477  Business Development
307  Female   86386          Distribution
308  Female   81308                 Legal
309    Male   84810             Marketing
310    Male   66775                 Legal
311     NaN   72145               Finance
312    Male  121604                 Sales
313  Female  109510                 Legal
314    Male  112117                   NaN
315     NaN  108127       Client Services
316  Female  123711               Product
317  Female  132381  Business Development
318    Male  148225               Finance
319  Female  145988             Marketing
320  Female   62960                 Sales
321  Female   56926                 Sales
322    Male   41428               Product
323  Female  115658                 Sales
324  Female   76707  Business Development
325    Male   60388       Client Services
326    Male   45150               Product
327    Male   58755             Marketing
328    Male   76076               Finance
329    Male   87760           Engineering
330    Male  135119       Client Services
331  Female   36759             Marketing
332    Male  121723               Product
333  Female  110061       Client Services
334    Male   85074       Client Services
335    Male   85799               Finance
336    Male   75150                 Legal
337    Male   91344                 Sales
338    Male   86326               Product
339    Male   98753       Human Resources
340    Male  113060                 Sales
341    Male   77327               Finance
342  Female   62666               Product
343    Male   96633           Engineering
344    Male   58248  Business Development
345    Male   83706       Human Resources
346    Male   74086       Human Resources
347  Female   95389                 Sales
348    Male  129968               Finance
349  Female  140347                 Sales
350     NaN   41549                 Sales
351  Female   74287                 Sales
352    Male   69906           Engineering
353    Male   65078             Marketing
354  Female  106406                 Legal
355  Female  115913                 Legal
356  Female   38092          Distribution
357    Male  121160           Engineering
358    Male   90429               Product
359  Female   64207       Client Services
360  Female   80688                 Sales
361  Female   55044                 Sales
362    Male   72893          Distribution
363     NaN   96978               Finance
364    Male   97364               Product
365     NaN  140885       Human Resources
366     NaN   58520       Client Services
367    Male   66067                   NaN
368  Female  147183  Business Development
369  Female   87721               Product
370  Female  144001  Business Development
371    Male   91133                 Sales
372    Male   67827           Engineering
373    Male   81839                 Sales
374  Female   81444          Distribution
375     NaN  137661                 Sales
376    Male  112548           Engineering
377    Male  111249       Human Resources
378    Male  114334               Product
379  Female  118906             Marketing
380     NaN   72979                 Sales
381    Male   64172           Engineering
382  Female  107024                   NaN
383    Male   50167               Product
384    Male  106995               Product
385  Female   70492       Client Services
386  Female  125881                 Sales
387    Male  123294       Client Services
388  Female  131045               Product
389     NaN   97635       Client Services
390     NaN   94493                 Sales
391  Female  140502                 Sales
392    Male  106310       Client Services
393     NaN   46240           Engineering
394  Female  111163               Product
395  Female   93753                 Sales
396  Female   63494       Human Resources
397    Male  116693          Distribution
398  Female   85215       Human Resources
399  Female   86439               Finance
400     NaN   62913             Marketing
401  Female   38872  Business Development
402     NaN  124655           Engineering
403    Male  113506             Marketing
404     NaN  109980                 Sales
405  Female   91522               Finance
406  Female   42214  Business Development
407     NaN   83159          Distribution
408    Male  144082       Client Services
409    Male   47885       Human Resources
410    Male  126232                 Sales
411    Male  134598  Business Development
412  Female   66604                 Legal
413    Male  115194             Marketing
414    Male   49101  Business Development
415     NaN   67811               Finance
416    Male  111043          Distribution
417     NaN   37748       Human Resources
418  Female   36403               Finance
419  Female  140136  Business Development
420    Male  121508               Finance
421    Male   79906                 Sales
422    Male  123144               Product
423  Female   46953       Client Services
424     NaN   79443       Human Resources
425  Female   51395               Finance
426    Male  134408       Human Resources
427    Male   71853                 Sales
428    Male   68028               Finance
429  Female  149903       Human Resources
430  Female   79123          Distribution
431    Male  104014                 Legal
432     NaN  121160       Client Services
433  Female   65362                 Legal
434  Female   50701                   NaN
435    Male  144709          Distribution
436  Female   53061               Finance
437  Female   36697                 Sales
438    Male   69244                   NaN
439    Male  101036       Human Resources
440    Male   52119       Client Services
441  Female   46666  Business Development
442  Female   73437               Finance
443  Female   86318                 Sales
444    Male   76409          Distribution
445    Male   71642                   NaN
446  Female   67150             Marketing
447    Male  142208           Engineering
448    Male   81183       Client Services
449  Female  107163       Human Resources
450    Male   55038                 Legal
451     NaN  140002             Marketing
452    Male  146812             Marketing
453  Female   40119       Human Resources
454    Male  136602             Marketing
455  Female   69579       Human Resources
456     NaN  101457           Engineering
457  Female  121232                 Legal
458    Male  102626               Finance
459     NaN  137171             Marketing
460  Female   88276                 Legal
461    Male   43354             Marketing
462    Male  125556           Engineering
463    Male   59862               Product
464    Male   74640             Marketing
465  Female   52875                 Legal
466    Male   58789                 Sales
467  Female  122897           Engineering
468  Female  136032             Marketing
469    Male  141958                 Legal
470    Male  139917          Distribution
471  Female  147635       Human Resources
472    Male   68230       Client Services
473    Male  124365  Business Development
474    Male  104749           Engineering

In [22]:
df[["Gender","Salary","Team"]].head(5)

   Gender  Salary             Team
0    Male   97308        Marketing
1    Male   61933              NaN
2  Female  130590          Finance
3    Male  138705          Finance
4    Male  101004  Client Services

In [30]:
df.head(5)["Salary"]

0     97308
1     61933
2    130590
3    138705
4    101004
Name: Salary, dtype: int64

In [29]:
# To check the count of  values in any column
# It does not include nan or missing values

df["Gender"].count()

df["Salary"].count()

np.int64(1000)

In [27]:
df[["Gender","Salary","Team"]].count()

Gender     855
Salary    1000
Team       957
dtype: int64

In [25]:
df.count()

First Name            933
Gender                855
Start Date           1000
Last Login Time      1000
Salary               1000
Bonus %              1000
Senior Management     933
Team                  957
dtype: int64

In [32]:
# To check the count of unique values in any column

df["Gender"].nunique()

2

In [35]:
df[["Gender","Team","Salary"]].nunique()

Gender      2
Team       10
Salary    995
dtype: int64

In [31]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [37]:
# To check the unique values in any column

df["Team"].unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

In [38]:
# frequency count of unique values in each column

df["Team"].value_counts(dropna=False)

Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
NaN                      43
Name: count, dtype: int64

In [34]:
#nunique --> count of unique values in any column or complete dataframe
#count --> overall count of values in any column or complete dataframe
#unique --> unique values in any column
#value_counts --> frequency count of all unique values in any column

In [40]:
for i in ["Gender","Team","Senior Management"]:
    print("--------------------",i,"-------------------------")
    print(df[i].value_counts())
    print("Unique Values", df[i].unique())

-------------------- Gender -------------------------
Gender
Female    431
Male      424
Name: count, dtype: int64
Unique Values ['Male' 'Female' nan]
-------------------- Team -------------------------
Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: count, dtype: int64
Unique Values ['Marketing' nan 'Finance' 'Client Services' 'Legal' 'Product'
 'Engineering' 'Business Development' 'Human Resources' 'Sales'
 'Distribution']
-------------------- Senior Management -------------------------
Senior Management
True     468
False    465
Name: count, dtype: int64
Unique Values [True False nan]

### Statistical Operations

In [43]:
df["Salary"].max()

149908

In [45]:
df["Salary"].idxmax()

644

In [47]:
df["Salary"].min()

35013

In [48]:
df["Salary"].idxmin()

576

In [51]:
df["Salary"].mean()

np.float64(90662.181)

In [50]:
df["Salary"].median()

90428.0

In [52]:
df["Salary"].std() # Standard Deviation

32923.693342022234

In [53]:
df["Salary"].var() # Variance

1083969583.279519

In [54]:
round(df["Salary"].var(),2)

1083969583.28

In [58]:
df["Bonus %"].round(2)

0       6.94
1       4.17
2      11.86
3       9.34
4       1.39
5      10.12
6      10.01
7      11.60
8      18.52
9       7.52
10     15.13
11     12.64
12     17.49
13      5.83
14     14.54
15      1.26
16      7.37
17      6.41
18     19.08
19      1.89
20      4.93
21     13.64
22     18.82
23      5.04
24     13.87
25     18.58
26      7.76
27      5.22
28     13.46
29      7.01
30      9.10
31     12.75
32      6.42
33     16.18
34     19.10
35     16.68
36     12.60
37      9.56
38      5.57
39      7.80
40      2.66
41     11.31
42     15.84
43      5.21
44      7.48
45     13.89
46      6.80
47      9.00
48      6.08
49      3.06
50     13.83
51     14.01
52      1.70
53     17.58
54      9.00
55     17.65
56     16.08
57     15.11
58      1.48
59     11.28
60      4.27
61      3.70
62     19.41
63     18.04
64     18.77
65     12.43
66      2.67
67      9.74
68     14.33
69      4.38
70      6.62
71     16.19
72      3.83
73      4.71
74     17.03
75      5.12
76      7.35
77      1.26
78      5.96
79      4.99
80     15.60
81     14.82
82      8.38
83      6.54
84      7.51
85      3.89
86     17.29
87      8.28
88      6.16
89     11.96
90     11.58
91      8.31
92     12.51
93      1.60
94      7.03
95     14.17
96      1.74
97     10.62
98     16.96
99     12.45
100    15.00
101    11.85
102    12.16
103     8.93
104    19.30
105     8.57
106     3.05
107    16.57
108    12.40
109    11.45
110    16.14
111     8.45
112     4.02
113     3.71
114     6.81
115     4.17
116    18.99
117     9.49
118     9.56
119    12.30
120    15.40
121    18.74
122    13.89
123    14.84
124     2.40
125    14.23
126    17.18
127     5.83
128    16.44
129    13.10
130     6.22
131    17.52
132    10.76
133     2.24
134     2.65
135     8.83
136    19.69
137    15.12
138     6.03
139    10.53
140     1.85
141    14.73
142     5.69
143     8.69
144    12.45
145    13.08
146     4.15
147     4.00
148    14.84
149     8.58
150    19.93
151    15.30
152     8.07
153    10.49
154     5.36
155    17.70
156     1.56
157    14.44
158     8.76
159    14.32
160    16.99
161    11.45
162    14.42
163    19.14
164    18.20
165     9.06
166     7.01
167    17.98
168     7.02
169     5.46
170    19.02
171    17.50
172     9.40
173     3.96
174     6.18
175     1.45
176    10.17
177    14.08
178    17.65
179    19.34
180     5.03
181     1.95
182    12.18
183     2.52
184     9.18
185     8.84
186     1.82
187     6.46
188    15.93
189     1.22
190     9.13
191     6.65
192    16.48
193     4.44
194     9.00
195    12.76
196    19.13
197     3.03
198     9.64
199    16.74
200     8.52
201     7.95
202     5.08
203     2.78
204     4.93
205     8.01
206     8.40
207     1.77
208     4.90
209    11.30
210     9.15
211    19.61
212     1.82
213    15.36
214     3.55
215     3.80
216     2.46
217     1.01
218    10.63
219     7.77
220     5.56
221     3.84
222     3.07
223    15.87
224     2.31
225    15.27
226     9.40
227    11.23
228    17.44
229     1.68
230     9.00
231    17.02
232    10.26
233    14.75
234    12.18
235     3.64
236     2.62
237     9.38
238     5.13
239    17.61
240    19.11
241     5.96
242    18.43
243     5.41
244     8.87
245    17.14
246    12.04
247     3.74
248     4.37
249    19.55
250     8.94
251     6.51
252     4.23
253    10.39
254     8.00
255     5.11
256     4.75
257    15.52
258    12.66
259    15.58
260     2.49
261    13.68
262     3.72
263    14.60
264    13.22
265     3.45
266    14.06
267    16.04
268     5.81
269    18.52
270     9.55
271    12.06
272    18.23
273     1.11
274     5.46
275    18.46
276    12.00
277    19.06
278    12.98
279     1.14
280     9.64
281     6.15
282    12.34
283     1.61
284     4.34
285     2.30
286    10.98
287    10.00
288    18.10
289     6.39
290    13.66
291    17.46
292    18.28
293     9.65
294    19.15
295     3.87
296     3.18
297     7.66
298     4.54
299    19.03
300     3.59
301    13.02
302     5.03
303     3.66
304    18.70
305     3.73
306    17.44
307     2.94
308     2.20
309    15.79
310     2.16
311    13.45
312     1.92
313    13.46
314     6.34
315    15.86
316    10.97
317     8.34
318     1.84
319    18.24
320    14.36
321     7.51
322    14.37
323     3.04
324     6.03
325    17.89
326    12.08
327     5.10
328     5.32
329    14.99
330     7.89
331    17.27
332    18.64
333     7.49
334     1.84
335    19.93
336    12.18
337     4.04
338    10.72
339    16.44
340     2.85
341    11.58
342    10.25
343     4.99
344     3.91
345     6.96
346     5.78
347    14.22
348    19.90
349     8.72
350     3.95
351    10.75
352     4.84
353     3.10
354     1.78
355    12.12
356     5.67
357     7.84
358     4.45
359     7.82
360    18.89
361     4.08
362     9.56
363    13.86
364     3.60
365     1.11
366    16.23
367    10.96
368     8.75
369    12.48
370     2.19
371     5.14
372    19.72
373    12.07
374     3.17
375     4.80
376     4.66
377    10.57
378     9.67
379     4.54
380     5.66
381    10.89
382    12.18
383     2.36
384    15.72
385     8.90
386    16.70
387    19.89
388    11.31
389    10.41
390    13.44
391     9.99
392     4.03
393     6.98
394     5.03
395     7.09
396    19.39
397    13.84
398     7.42
399     7.80
400    18.24
401     9.30
402    14.27
403    19.64
404     8.86
405     7.56
406    17.54
407     9.55
408     1.62
409    19.28
410     6.19
411    11.70
412    14.61
413     5.86
414    11.90
415    12.70
416     5.97
417     9.05
418     2.66
419     3.12
420    19.33
421    18.02
422    16.26
423    17.44
424    14.64
425     2.38
426     3.56
427     8.04
428     7.87
429     5.63
430    19.42
431     7.08
432    12.99
433     7.13
434    14.23
435    10.07
436    11.86
437    11.20
438     6.22
439     2.83
440    11.34
441     1.89
442     2.52
443    18.49
444     7.01
445     1.50
446    15.85
447    11.20
448    17.07
449     3.66
450    19.69
451    19.49
452     1.96
453     4.34
454    10.43
455    18.03
456     6.66
457    16.62
458    15.84
459     5.57
460    14.25
461    13.95
462     8.00
463     3.27
464    18.64
465     4.19
466     5.46
467     8.22
468    10.70
469     9.08
470    11.47
471    14.69
472     8.05
473     8.46
474    11.36
475     7.94
476     8.46
477     9.70
478    18.36
479    18.79
480    15.97
481     1.08
482     3.38
483     3.10
484    11.12
485     1.98
486     2.02
487    15.92
488    19.94
489    19.73
490     7.46
491     6.52
492    18.84
493    13.27
494     7.25
495     2.12
496     5.44
497     7.12
498     4.55
499    14.76
500    11.13
501     9.76
502     1.76
503     4.89
504    10.49
505    13.25
506     6.50
507    18.65
508    15.59
509     6.22
510    17.07
511     8.13
512    19.70
513    19.62
514    18.11
515    10.46
516    15.98
517     4.00
518    18.00
519     3.18
520     8.41
521    17.97
522    14.86
523    15.03
524    14.51
525     9.54
526     8.70
527     1.02
528     7.18
529     7.25
530    14.60
531    10.15
532    10.28
533    13.77
534    12.29
535     8.20
536     4.90
537    13.47
538     3.49
539     3.46
540     4.82
541     7.85
542    14.08
543     2.37
544    13.32
545     9.05
546     3.67
547    10.37
548     3.31
549     3.19
550    16.30
551    19.12
552    11.90
553    13.85
554     6.01
555    18.45
556     6.64
557    18.11
558    13.30
559     6.51
560     2.10
561     8.57
562    18.86
563    14.84
564     7.56
565    17.33
566    12.99
567    12.60
568    19.14
569     6.77
570     1.43
571    18.62
572    16.69
573     5.44
574     7.42
575     5.81
576    14.88
577    11.39
578     1.44
579     1.19
580    18.09
581    15.12
582    10.20
583    13.51
584    18.27
585     2.75
586     7.58
587     8.94
588     2.42
589     9.66
590    13.35
591     7.81
592    15.22
593     4.64
594     2.08
595     3.51
596     6.75
597     8.29
598    11.51
599    10.92
600    15.75
601     9.86
602    15.70
603    12.49
604    15.43
605     2.14
606    10.26
607    12.74
608    17.27
609    15.91
610    10.08
611    12.52
612     7.10
613    11.38
614    11.51
615     6.08
616    12.93
617     1.45
618     1.27
619    19.06
620     8.40
621    18.82
622     9.00
623     9.60
624    12.20
625     8.70
626     2.93
627    16.64
628     1.70
629    19.51
630     2.62
631     1.87
632     6.88
633     6.50
634    19.29
635    13.05
636     2.92
637    18.40
638     1.43
639    19.39
640     3.76
641     5.20
642    15.11
643     9.77
644    18.91
645    10.16
646    19.78
647     5.32
648    15.86
649    14.06
650    11.75
651    17.37
652     1.02
653    16.92
654    11.41
655    13.61
656    17.11
657    11.37
658    13.59
659     4.78
660     6.66
661     4.22
662     4.66
663    12.87
664    12.46
665     3.64
666     7.78
667    14.77
668    17.10
669    11.88
670    14.78
671     3.96
672    10.98
673    16.25
674     1.93
675    12.79
676     9.80
677    15.77
678     2.68
679     3.34
680    14.30
681    17.40
682     5.27
683     6.61
684    10.48
685    19.39
686    18.70
687     8.99
688    17.82
689    17.26
690    13.93
691     3.69
692     8.16
693     2.78
694    13.33
695     5.15
696    11.59
697     9.80
698     8.22
699    10.38
700     7.93
701    11.71
702     6.98
703     9.77
704    11.21
705    15.19
706    18.47
707     7.84
708     1.20
709    12.05
710    17.10
711    16.55
712    15.74
713     9.85
714    12.92
715    13.13
716    13.81
717    11.52
718     7.97
719    13.00
720    18.68
721    11.63
722     5.20
723    11.42
724    13.47
725     1.88
726    13.00
727    12.94
728    19.11
729    18.89
730    18.67
731    12.77
732     1.43
733     3.66
734     1.40
735     6.84
736    11.72
737    14.62
738    12.74
739    14.74
740     3.53
741    15.94
742     2.84
743    13.81
744     5.19
745    14.62
746     1.03
747    16.56
748    19.63
749     9.71
750    16.38
751     3.37
752    18.34
753     5.48
754     2.03
755     4.00
756    10.62
757     7.78
758     7.62
759    10.90
760     4.02
761    10.01
762     3.95
763     3.02
764    15.34
765    11.48
766     9.70
767    18.77
768     9.66
769     9.85
770    13.18
771    12.03
772    18.02
773    10.74
774    10.87
775     6.06
776    18.78
777     4.51
778     5.27
779    17.80
780    16.84
781     9.13
782    17.68
783    13.59
784     3.45
785     8.94
786     2.58
787     4.14
788    16.35
789     6.29
790    11.06
791    19.60
792     9.56
793    13.71
794    10.29
795     3.32
796    12.80
797    19.85
798    17.95
799     2.71
800    11.52
801    17.50
802    13.62
803    19.08
804    10.66
805    15.08
806     6.08
807     2.09
808     3.46
809    19.75
810     7.23
811     6.82
812     5.48
813    19.77
814     3.22
815     4.00
816     4.07
817     4.08
818    10.05
819    17.86
820     5.18
821    12.25
822     7.27
823     9.49
824     2.15
825     5.89
826     5.66
827     7.49
828     7.86
829     2.10
830    19.91
831     7.59
832    19.47
833     9.33
834     2.07
835     2.28
836    13.49
837    15.80
838     9.15
839    16.81
840     4.92
841    19.50
842    19.26
843     8.96
844     8.74
845    11.68
846    15.57
847     4.71
848     2.88
849     9.19
850     6.00
851    16.16
852    17.34
853    11.39
854    10.41
855     2.28
856    12.21
857     7.94
858     9.63
859    19.24
860    14.66
861    18.86
862    18.54
863     6.84
864     6.01
865    16.31
866    14.25
867     7.74
868    13.66
869     7.99
870    18.75
871     2.47
872    19.33
873     4.30
874     3.52
875     9.21
876     8.22
877    13.82
878     8.06
879    19.13
880     8.38
881     6.32
882    14.34
883    18.02
884    18.53
885     9.16
886    14.84
887    15.41
888    11.93
889     1.55
890     7.10
891     8.48
892     2.71
893     5.68
894     7.64
895    16.97
896     3.94
897    10.15
898    15.21
899    16.32
900    18.18
901     6.91
902     6.32
903    14.96
904     6.16
905     4.36
906    17.67
907    10.08
908     3.28
909     6.47
910     8.88
911    15.53
912     1.02
913     6.17
914     5.27
915     6.72
916     7.70
917     6.34
918    19.48
919     8.96
920     9.83
921    18.90
922     3.41
923     4.38
924     9.62
925    19.39
926    19.49
927    16.01
928     2.67
929     1.08
930     2.39
931     3.77
932     2.01
933     3.80
934     3.79
935    12.09
936    10.06
937    18.42
938     2.66
939     2.15
940     8.61
941    15.65
942     6.54
943     2.73
944     1.90
945    17.43
946    16.94
947     5.33
948    11.05
949     8.23
950    10.83
951     9.66
952    11.91
953    14.08
954     1.15
955    11.18
956     8.12
957    15.90
958     9.63
959     5.85
960    18.09
961     3.05
962    16.92
963    17.94
964    12.39
965    18.39
966     9.15
967    19.57
968    11.67
969    17.31
970    15.40
971     5.37
972    11.16
973    11.10
974    16.45
975    12.47
976     4.20
977     5.95
978    11.18
979    13.20
980     8.86
981    19.28
982     8.64
983    11.74
984    13.04
985     1.91
986    18.00
987    10.33
988    11.21
989     3.79
990    10.98
991    11.05
992    11.62
993    19.04
994     4.48
995    16.66
996    19.68
997     1.42
998    11.98
999    10.17
Name: Bonus %, dtype: float64

In [61]:
## Statistical Summary of the data
df.describe()

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [64]:
df[["Bonus %","Salary"]].describe().T[["max","min"]]

                max        min
Bonus %      19.944      1.015
Salary   149908.000  35013.000

In [70]:
df[df["Bonus %"]>19]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
34,Jerry,Male,01-10-04,12:56 PM,95734,19.096,False,Client Services
62,NaN,Female,06-12-07,5:25 PM,58112,19.414,NaN,Marketing
104,John,Male,12/23/1989,7:01 AM,80740,19.305,False,Marketing
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
150,Sean,Male,05-04-96,8:59 PM,135490,19.934,False,Marketing
163,Terry,Male,09-03-90,9:15 PM,52226,19.135,False,Client Services
170,Irene,Female,1/29/1992,11:36 AM,133772,19.020,True,Sales
179,Jessica,Female,10/23/1995,5:53 AM,68759,19.343,True,Finance
196,Steven,Male,11-10-85,10:53 AM,62719,19.127,False,Client Services
211,Linda,Female,6/24/2006,12:04 PM,110967,19.612,True,Human Resources
240,Phyllis,NaN,4/21/1984,7:05 PM,94088,19.107,False,Distribution
249,Betty,Female,06-12-02,3:59 AM,104896,19.550,True,Business Development
277,Brenda,NaN,5/29/1991,6:32 AM,82439,19.062,False,Sales
294,Virginia,Female,10/20/1999,6:23 AM,46905,19.154,False,Distribution
299,Emily,Female,1/13/1988,6:42 AM,36711,19.028,True,Human Resources
335,Robert,Male,11/18/2014,5:00 AM,85799,19.930,False,Finance
348,Philip,Male,08-02-89,11:21 AM,129968,19.897,False,Finance
372,Albert,Male,02-01-97,4:20 PM,67827,19.717,True,Engineering
387,Robert,Male,10/29/1994,4:26 AM,123294,19.894,False,Client Services
396,Rose,Female,07-06-02,3:57 PM,63494,19.385,True,Human Resources
403,Craig,Male,02-08-84,4:45 AM,113506,19.642,False,Marketing
409,Jeremy,Male,5/29/1994,6:24 AM,47885,19.276,True,Human Resources
420,Justin,Male,5/22/1986,6:30 AM,121508,19.334,True,Finance
430,Andrea,Female,10-01-10,11:54 AM,79123,19.422,False,Distribution
450,Willie,Male,8/22/2009,1:03 PM,55038,19.691,False,Legal
451,Terry,NaN,7/15/2016,12:29 AM,140002,19.490,True,Marketing
488,Robert,Male,03-11-07,11:20 AM,135882,19.944,False,Legal
489,Sharon,Female,07-01-11,9:50 AM,46007,19.731,True,Client Services
512,Wanda,Female,04-06-93,3:11 AM,78883,19.695,False,NaN
513,Jimmy,Male,11/19/2013,7:29 PM,63549,19.624,False,NaN
551,Philip,Male,7/18/1985,6:36 AM,122319,19.122,False,Engineering
568,Susan,Female,4/18/1986,9:31 AM,90829,19.142,False,Marketing
619,Beverly,Female,10/22/1990,2:45 PM,59070,19.064,True,Engineering
629,Debra,Female,03-12-83,12:19 PM,74911,19.513,False,Marketing
634,Carl,Male,3/30/1987,5:59 PM,75598,19.289,False,NaN
639,Amanda,NaN,08-11-91,2:15 PM,46665,19.391,True,Client Services
646,Elizabeth,Female,2/21/2010,7:02 AM,79145,19.780,False,Finance
685,NaN,Male,10/20/1989,9:37 AM,88086,19.387,NaN,Finance
728,Dorothy,Female,10-08-08,12:22 AM,82744,19.111,True,Client Services
748,Martha,Female,7/17/1997,11:11 PM,94963,19.626,True,Business Development
791,Joseph,Male,11-04-82,9:46 PM,126010,19.601,False,Legal
797,Rose,Female,12/31/1982,6:50 PM,145001,19.850,False,Engineering
803,Lois,Female,7/28/2012,11:39 AM,53954,19.075,False,Product
809,George,Male,9/27/1995,5:04 PM,36749,19.754,False,Finance
813,Evelyn,Female,02-10-02,4:44 AM,123621,19.767,True,Marketing
830,Michael,Male,8/31/2002,1:20 AM,81206,19.908,True,Distribution
832,Keith,Male,02-12-03,3:02 PM,120672,19.467,False,Legal
841,Ruby,Female,8/13/2006,6:27 PM,48354,19.501,False,Business Development
842,Sandra,Female,02-07-98,12:39 PM,132327,19.264,False,Product
859,Robin,Female,10-01-12,2:44 AM,41808,19.239,False,Business Development
872,Brenda,Female,1/18/2015,4:39 PM,73749,19.332,False,Business Development
879,Amy,Female,5/20/2009,6:26 AM,75415,19.132,False,Client Services
918,Ryan,Male,4/27/1999,3:41 AM,85858,19.475,False,Client Services
925,NaN,Female,8/23/2000,4:19 PM,95866,19.388,NaN,Sales
926,Judith,Female,03-01-04,7:32 AM,109324,19.488,False,Distribution
967,Thomas,Male,03-12-16,3:10 PM,105681,19.572,False,Engineering
981,James,Male,1/15/1993,5:19 PM,148985,19.280,False,Legal
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [74]:
# & --> and condition

df[(df["Bonus %"]>19) & (df["Team"]=="Finance")]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
179,Jessica,Female,10/23/1995,5:53 AM,68759,19.343,True,Finance
335,Robert,Male,11/18/2014,5:00 AM,85799,19.930,False,Finance
348,Philip,Male,08-02-89,11:21 AM,129968,19.897,False,Finance
420,Justin,Male,5/22/1986,6:30 AM,121508,19.334,True,Finance
646,Elizabeth,Female,2/21/2010,7:02 AM,79145,19.780,False,Finance
685,NaN,Male,10/20/1989,9:37 AM,88086,19.387,NaN,Finance
809,George,Male,9/27/1995,5:04 PM,36749,19.754,False,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [76]:
# | --> or condition

df[(df["Bonus %"]>19) | (df["Gender"]=="Female")]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,08-08-02,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,08-12-80,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,06-05-16,6:09 AM,59414,1.256,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
30,Christina,Female,08-06-02,1:19 PM,118780,9.096,True,Engineering
33,Jean,Female,12/18/1993,9:07 AM,119082,16.180,False,Business Development
34,Jerry,Male,01-10-04,12:56 PM,95734,19.096,False,Client Services
35,Theresa,Female,10-10-06,1:12 AM,85182,16.675,False,Sales
36,Rachel,Female,2/16/2009,8:47 PM,142032,12.599,False,Business Development
37,Linda,Female,10/19/1981,8:49 PM,57427,9.557,True,Client Services
38,Stephanie,Female,9/13/1986,1:52 AM,36844,5.574,True,Business Development
42,Beverly,Female,09-09-98,8:26 PM,121918,15.835,False,Legal
43,Marilyn,Female,12-07-80,3:16 AM,73524,5.207,True,Marketing
44,Cynthia,Female,11/16/1988,6:54 PM,145146,7.482,True,Product
47,Kathy,Female,6/22/2005,4:51 AM,66820,9.000,True,Client Services
50,Nancy,Female,9/23/2000,8:05 AM,94976,13.830,True,Engineering
54,Sara,Female,8/15/2007,9:23 AM,83677,8.999,False,Engineering
55,Karen,Female,11/30/1999,7:46 AM,102488,17.653,True,Product
58,Theresa,Female,04-11-10,7:18 AM,72670,1.481,True,Engineering
59,Irene,Female,05-07-97,9:32 AM,66851,11.279,False,Engineering
61,Denise,Female,11-06-01,12:03 PM,106862,3.699,False,Business Development
62,NaN,Female,06-12-07,5:25 PM,58112,19.414,NaN,Marketing
66,Nancy,Female,12/15/2012,11:57 PM,125250,2.672,True,Business Development
67,Rachel,Female,8/16/1999,6:53 AM,51178,9.735,True,Finance
73,Frances,Female,04-04-99,4:19 PM,90582,4.709,True,Sales
75,Bonnie,Female,07-02-91,1:27 AM,104897,5.118,True,Human Resources
76,Margaret,Female,09-10-88,12:42 PM,131604,7.353,True,Distribution
78,Robin,Female,06-04-83,3:15 PM,114797,5.965,True,Sales
79,Bonnie,Female,11/13/1988,3:30 PM,115814,4.990,False,Product
84,Doris,Female,8/20/2004,5:51 AM,83072,7.511,False,Finance
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
88,Donna,Female,11/27/1991,1:59 PM,64088,6.155,True,Legal
89,Janice,Female,03-12-16,12:40 AM,51082,11.955,False,Legal
92,Linda,Female,5/25/2000,5:45 PM,119009,12.506,True,Business Development
95,Heather,Female,07-11-98,2:17 PM,43026,14.166,False,Client Services
96,Cynthia,Female,3/21/1994,8:34 AM,142321,1.737,False,Finance
98,Tina,Female,6/16/2016,7:47 PM,100705,16.961,True,Marketing
100,Melissa,Female,6/21/2005,6:33 AM,48109,14.995,False,Finance
103,Phyllis,Female,10-11-96,9:30 PM,136984,8.932,True,Finance
104,John,Male,12/23/1989,7:01 AM,80740,19.305,False,Marketing
105,Kathy,Female,03-09-96,4:33 AM,91712,8.567,False,Finance
110,Shirley,Female,6/20/2001,10:39 PM,147113,16.135,False,Legal
111,Bonnie,Female,12/17/1999,3:12 PM,42153,8.454,True,Business Development
113,Tina,Female,06-12-09,7:16 AM,114767,3.711,True,Engineering
114,Ashley,Female,08-04-02,11:00 AM,58698,6.811,True,Business Development
115,Pamela,Female,07-01-82,6:51 AM,54585,4.166,False,Product
118,Andrea,Female,01-12-12,5:43 AM,120204,9.557,False,Business Development
122,Christina,Female,4/13/2012,2:04 PM,110169,13.892,True,Engineering
123,Helen,Female,11/29/2001,2:30 AM,73789,14.841,True,Product
124,Marilyn,Female,11/16/1983,8:29 AM,76078,2.401,True,Product
125,Patricia,Female,09-01-03,6:46 AM,49368,14.226,False,Human Resources
126,Michelle,Female,3/30/1984,6:43 PM,57325,17.179,True,Human Resources
130,Shirley,Female,05-01-84,1:15 PM,41334,6.219,True,Human Resources
131,Rebecca,Female,07-10-92,12:23 AM,94231,17.517,False,Product
133,Lois,Female,12/25/1987,4:16 PM,106317,2.235,True,Client Services
134,Carolyn,Female,04-09-11,5:38 AM,109260,2.650,True,Business Development
135,Gloria,Female,6/29/2007,5:34 AM,134148,8.833,True,Legal
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
138,Ashley,Female,5/25/2006,11:30 AM,112238,6.030,True,Engineering
139,NaN,Female,10-03-90,1:08 AM,132373,10.527,NaN,NaN
140,Shirley,Female,2/28/1981,1:23 PM,113850,1.854,False,Marketing
142,Elizabeth,Female,10-09-03,5:53 PM,146129,5.687,False,Finance
145,Jennifer,Female,04-04-09,10:47 PM,71715,13.079,True,Client Services
146,Patricia,Female,11/25/1992,2:24 AM,95322,4.150,False,Product
149,NaN,Female,8/17/2014,2:00 PM,86230,8.578,NaN,Distribution
150,Sean,Male,05-04-96,8:59 PM,135490,19.934,False,Marketing
152,Ruth,Female,8/19/1999,4:03 AM,129297,8.067,True,Client Services
154,Rebecca,Female,11/15/1980,4:13 AM,85730,5.359,True,Product
155,Marie,Female,3/16/2003,12:12 AM,104058,17.695,True,Business Development
157,NaN,Female,7/27/2005,8:32 AM,79536,14.443,NaN,Product
158,Norma,Female,2/28/1999,8:45 PM,114412,8.756,True,Marketing
160,Kathy,Female,3/18/2000,7:26 PM,149563,16.991,True,Finance
163,Terry,Male,09-03-90,9:15 PM,52226,19.135,False,Client Services
164,Mary,Female,8/13/1999,1:03 AM,134645,18.197,False,Business Development
165,NaN,Female,3/23/2014,1:28 PM,59148,9.061,NaN,Legal
166,NaN,Female,07-09-91,6:52 PM,42341,7.014,NaN,Sales
169,Michelle,Female,11-04-96,9:34 PM,53754,5.455,True,Product
170,Irene,Female,1/29/1992,11:36 AM,133772,19.020,True,Sales
172,Sara,Female,9/23/1991,6:17 PM,97058,9.402,False,Finance
173,Lillian,Female,12/21/2008,6:51 PM,85446,3.959,True,Engineering
178,Jane,Female,09-03-97,2:01 AM,144474,17.648,False,Product
179,Jessica,Female,10/23/1995,5:53 AM,68759,19.343,True,Finance
182,Lillian,Female,6/19/1999,4:44 PM,123940,12.184,True,Business Development
185,Sandra,Female,1/19/1983,7:25 AM,42090,8.842,True,Legal
186,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales
190,Carol,Female,3/19/1996,3:39 AM,57783,9.129,False,Finance
191,Lois,Female,10/18/2013,4:51 PM,36946,6.652,False,Engineering
193,Rebecca,Female,2/18/1995,6:50 AM,109259,4.443,True,Legal
194,Irene,Female,1/30/2004,8:25 PM,131038,8.996,False,Distribution
196,Steven,Male,11-10-85,10:53 AM,62719,19.127,False,Client Services
197,Carolyn,Female,11-06-12,3:51 AM,69268,3.031,False,Client Services
198,Maria,Female,12/27/1990,9:57 PM,36067,9.640,True,Product
201,Kimberly,Female,7/15/1997,5:57 AM,36643,7.953,False,Marketing
203,Diana,Female,01-04-13,7:53 AM,103521,2.784,True,Business Development
206,Patricia,Female,12-06-12,4:01 AM,114079,8.399,True,Client Services
207,Katherine,Female,11/14/1999,8:15 AM,57531,1.767,False,Client Services
209,Emily,Female,9/20/2007,11:25 AM,89434,11.295,False,Engineering
210,Ruth,Female,08-12-86,7:29 PM,44639,9.148,True,Legal
211,Linda,Female,6/24/2006,12:04 PM,110967,19.612,True,Human Resources
212,Lisa,Female,11-02-09,9:42 AM,115387,1.821,False,Client Services
213,Evelyn,Female,5/24/1980,11:10 PM,81673,15.364,True,Engineering
214,Julie,Female,7/23/1989,1:52 PM,109588,3.550,False,Engineering
215,Mary,Female,5/30/2009,11:41 PM,92544,3.800,False,Client Services
220,NaN,Female,6/17/1991,12:49 PM,71945,5.560,NaN,Marketing
224,Sarah,Female,9/14/1995,7:50 AM,87298,2.311,False,Distribution
226,Kathy,Female,4/19/1995,12:46 AM,50905,9.404,True,Finance
231,Diane,Female,4/18/1993,3:22 AM,64084,17.018,False,Product
232,Marilyn,Female,04-04-97,9:28 PM,147663,10.263,False,Human Resources
233,Kathryn,Female,02-04-04,1:47 PM,73935,14.752,False,Sales
234,Irene,Female,02-04-82,5:26 PM,40837,12.182,True,Client Services
235,Norma,Female,02-11-15,11:44 PM,94393,3.643,True,Engineering
236,Laura,Female,04-02-06,1:57 PM,42087,2.624,False,Product
237,Cheryl,Female,9/23/2008,2:57 AM,52080,9.375,False,Legal
240,Phyllis,NaN,4/21/1984,7:05 PM,94088,19.107,False,Distribution
249,Betty,Female,06-12-02,3:59 AM,104896,19.550,True,Business Development
255,Denise,Female,3/20/2009,7:57 AM,115118,5.108,False,Human Resources
256,Debra,Female,3/13/1998,11:16 PM,48696,4.750,False,Legal
260,Gloria,Female,3/27/2007,1:44 AM,90730,2.491,False,Distribution
261,Marie,Female,08-06-95,1:58 PM,100308,13.677,False,Product
262,Anne,Female,7/16/1986,2:08 PM,69134,3.723,True,Engineering
264,Stephanie,Female,3/24/1983,11:15 AM,50141,13.218,True,Human Resources
266,NaN,Female,08-05-09,8:14 AM,115145,14.063,NaN,Distribution
268,Irene,Female,03-03-82,8:26 AM,56526,5.810,True,Finance
269,NaN,Female,08-02-92,8:35 PM,145316,18.517,NaN,Human Resources
275,Debra,Female,2/22/1994,10:25 PM,104250,18.456,True,Business Development
276,Christine,Female,07-03-89,4:01 AM,94345,11.996,False,Finance
277,Brenda,NaN,5/29/1991,6:32 AM,82439,19.062,False,Sales
278,Betty,Female,6/28/2005,6:03 PM,51613,12.984,False,Distribution
279,Ruby,Female,11-08-00,7:35 PM,105946,1.139,False,Business Development
284,Brenda,Female,10-06-05,9:33 PM,141521,4.337,False,Client Services
285,Judy,Female,9/16/1997,12:10 AM,65931,2.304,False,Human Resources
287,Lois,Female,11-09-11,7:06 AM,147183,9.999,True,Client Services
289,Jessica,Female,9/27/1985,1:35 PM,75145,6.388,True,Legal
291,Tammy,Female,11-11-84,10:30 AM,132839,17.463,True,Client Services
292,Anne,Female,03-07-00,6:45 AM,44537,18.284,True,Client Services
294,Virginia,Female,10/20/1999,6:23 AM,46905,19.154,False,Distribution
299,Emily,Female,1/13/1988,6:42 AM,36711,19.028,True,Human Resources
305,Margaret,Female,02-06-93,1:05 PM,125220,3.733,False,Marketing
307,Marilyn,Female,9/26/1981,2:23 AM,86386,2.937,False,Distribution
308,Cheryl,Female,09-08-09,10:16 AM,81308,2.196,True,Legal
313,Judy,Female,07-01-91,2:33 AM,109510,13.457,True,Legal
316,Marie,Female,10-03-13,8:05 PM,123711,10.966,False,Product
317,Kathy,Female,12/18/2013,3:09 PM,132381,8.340,False,Business Development
319,Jacqueline,Female,11/25/1981,3:01 PM,145988,18.243,False,Marketing
320,NaN,Female,07-08-08,11:40 PM,62960,14.356,NaN,Sales
321,Julie,Female,3/23/1986,9:26 AM,56926,7.507,False,Sales
323,Linda,Female,12/16/1990,2:20 AM,115658,3.041,True,Sales
324,Ruby,Female,12-10-88,8:27 PM,76707,6.031,False,Business Development
331,Evelyn,Female,09-03-83,1:58 PM,36759,17.269,True,Marketing
333,Shirley,Female,06-08-86,2:25 AM,110061,7.494,False,Client Services
335,Robert,Male,11/18/2014,5:00 AM,85799,19.930,False,Finance
342,Marie,Female,10/20/2011,10:09 PM,62666,10.247,False,Product
347,Lori,Female,3/31/1988,10:59 PM,95389,14.223,False,Sales
348,Philip,Male,08-02-89,11:21 AM,129968,19.897,False,Finance
349,Phyllis,Female,11/24/2005,11:57 PM,140347,8.723,False,Sales
351,Cynthia,Female,12-03-12,11:03 PM,74287,10.751,False,Sales
354,Elizabeth,Female,11-10-05,4:56 AM,106406,1.782,True,Legal
355,Andrea,Female,9/14/2003,10:30 PM,115913,12.121,False,Legal
356,Judy,Female,02-01-90,3:32 PM,38092,5.668,False,Distribution
359,Sarah,Female,5/22/1994,7:06 AM,64207,7.824,True,Client Services
360,Susan,Female,9/25/2004,1:30 AM,80688,18.892,True,Sales
361,Margaret,Female,05-05-14,6:01 AM,55044,4.078,False,Sales
368,Marilyn,Female,12/17/1982,12:10 PM,147183,8.748,False,Business Development
369,Mary,Female,10/18/2009,6:32 PM,87721,12.484,False,Product
370,Linda,Female,7/15/2009,10:12 PM,144001,2.194,False,Business Development
372,Albert,Male,02-01-97,4:20 PM,67827,19.717,True,Engineering
374,NaN,Female,12/31/2006,11:02 PM,81444,3.171,NaN,Distribution
379,NaN,Female,9/18/2002,12:39 PM,118906,4.537,NaN,Marketing
382,NaN,Female,4/18/1996,3:57 PM,107024,12.182,NaN,NaN
385,Debra,Female,1/19/2010,8:48 AM,70492,8.895,False,Client Services
386,Phyllis,Female,1/15/1995,5:27 AM,125881,16.697,False,Sales
387,Robert,Male,10/29/1994,4:26 AM,123294,19.894,False,Client Services
388,Gloria,Female,9/19/1989,7:40 PM,131045,11.312,True,Product
391,Marilyn,Female,8/15/1989,9:14 AM,140502,9.989,True,Sales
394,Robin,Female,01-08-98,2:12 AM,111163,5.025,True,Product
395,Kathy,Female,11/25/2001,9:55 PM,93753,7.094,True,Sales
396,Rose,Female,07-06-02,3:57 PM,63494,19.385,True,Human Resources
398,Doris,Female,7/29/1992,6:40 PM,85215,7.425,True,Human Resources
399,Kathryn,Female,06-09-88,9:29 AM,86439,7.799,False,Finance
401,Norma,Female,4/16/1996,5:40 AM,38872,9.302,True,Business Development
403,Craig,Male,02-08-84,4:45 AM,113506,19.642,False,Marketing
405,Sharon,Female,03-09-14,4:39 PM,91522,7.564,False,Finance
406,Mary,Female,8/22/2010,8:03 AM,42214,17.538,True,Business Development
409,Jeremy,Male,5/29/1994,6:24 AM,47885,19.276,True,Human Resources
412,Jacqueline,Female,02-11-07,2:01 AM,66604,14.609,False,Legal
418,Julia,Female,03-02-82,12:52 PM,36403,2.664,True,Finance
419,Dorothy,Female,11-05-13,10:50 PM,140136,3.120,True,Business Development
420,Justin,Male,5/22/1986,6:30 AM,121508,19.334,True,Finance
423,Deborah,Female,11/25/1980,4:33 AM,46953,17.436,False,Client Services
425,Alice,Female,05-02-86,1:50 AM,51395,2.378,True,Finance
429,Rose,Female,5/28/2015,8:40 AM,149903,5.630,False,Human Resources
430,Andrea,Female,10-01-10,11:54 AM,79123,19.422,False,Distribution
433,Wanda,Female,7/20/2008,1:44 PM,65362,7.132,True,Legal
434,Joyce,Female,02-07-95,7:38 AM,50701,14.227,True,NaN
436,Kathryn,Female,8/29/2007,6:10 AM,53061,11.864,True,Finance
437,Denise,Female,3/18/2001,12:02 AM,36697,11.196,True,Sales
441,Louise,Female,5/13/2003,9:47 AM,46666,1.886,True,Business Development
442,Julie,Female,4/23/1998,5:52 AM,73437,2.518,True,Finance
443,Kathy,Female,05-08-87,6:19 PM,86318,18.492,True,Sales
446,Cheryl,Female,8/16/1994,8:33 AM,67150,15.850,True,Marketing
449,Beverly,Female,11/30/2005,2:57 AM,107163,3.665,True,Human Resources
450,Willie,Male,8/22/2009,1:03 PM,55038,19.691,False,Legal
451,Terry,NaN,7/15/2016,12:29 AM,140002,19.490,True,Marketing
453,Annie,Female,12/19/1994,6:19 AM,40119,4.338,True,Human Resources
455,Ruth,Female,10/24/2000,4:13 AM,69579,18.029,True,Human Resources
457,Patricia,Female,01-09-15,4:16 AM,121232,16.624,False,Legal
460,Tina,Female,1/17/2005,9:11 AM,88276,14.248,False,Legal
465,Helen,Female,10/31/1997,2:43 AM,52875,4.188,False,Legal
467,Amy,Female,6/19/2002,3:06 AM,122897,8.222,True,Engineering
468,Janice,Female,6/28/1997,1:48 PM,136032,10.696,True,Marketing
471,Sharon,Female,03-12-02,6:32 AM,147635,14.693,False,Human Resources
475,Stephanie,Female,11/26/1992,12:54 AM,122121,7.937,True,Engineering
476,Kathy,Female,10/25/1996,12:59 PM,143541,8.461,False,Human Resources
480,Amy,Female,3/30/2008,10:54 PM,106249,15.967,False,Sales
481,NaN,Female,4/27/2013,6:40 AM,93847,1.085,NaN,Business Development
483,NaN,Female,4/26/1992,8:01 PM,115436,3.099,NaN,Human Resources
485,Ashley,Female,8/15/1997,9:48 PM,142415,1.985,True,Finance
487,Cheryl,Female,12-03-14,9:27 AM,71751,15.918,False,Business Development
488,Robert,Male,03-11-07,11:20 AM,135882,19.944,False,Legal
489,Sharon,Female,07-01-11,9:50 AM,46007,19.731,True,Client Services
490,Judith,Female,11/23/2007,1:22 PM,117055,7.461,False,Marketing
494,Barbara,Female,3/21/2002,8:02 AM,47322,7.250,True,Sales
498,Diana,Female,6/13/1994,4:21 PM,41831,4.548,False,Business Development
500,Christine,Female,02-01-03,1:11 PM,72613,11.126,False,Legal
502,Sarah,Female,11-03-80,2:47 PM,37259,1.763,False,Client Services
504,NaN,Female,6/24/2014,10:05 AM,38275,10.494,NaN,Distribution
509,Ann,Female,11-04-84,12:17 PM,90719,6.220,False,Business Development
512,Wanda,Female,04-06-93,3:11 AM,78883,19.695,False,NaN
513,Jimmy,Male,11/19/2013,7:29 PM,63549,19.624,False,NaN
516,Gloria,Female,04-12-92,8:26 PM,66224,15.979,True,Legal
517,Ruth,Female,12-12-96,10:07 AM,97915,3.997,True,Human Resources
518,Diana,Female,1/19/1995,12:37 AM,86883,18.003,True,Product
522,Catherine,Female,8/31/2013,7:24 PM,58047,14.858,True,Distribution
523,Diane,Female,07-05-82,4:56 PM,124889,15.026,True,Sales
526,Barbara,Female,3/22/2004,8:11 AM,144677,8.696,False,Finance
530,Kathleen,Female,6/13/2014,9:16 AM,35575,14.595,False,Distribution
531,Virginia,Female,05-02-10,9:10 PM,123649,10.154,True,Marketing
532,Lisa,Female,2/26/2005,6:33 PM,38078,10.280,True,Product
535,Louise,Female,9/18/1981,5:47 AM,91462,8.205,False,Marketing
537,Cynthia,Female,9/14/1991,1:08 PM,51633,13.472,True,Business Development
540,NaN,Female,12-02-09,3:30 AM,84746,4.820,NaN,Finance
541,Ruby,Female,05-01-99,3:36 AM,147362,7.851,True,Engineering
542,Amanda,Female,08-01-04,1:32 PM,80803,14.077,True,Distribution
543,Anna,Female,4/15/2008,2:34 PM,117293,2.366,False,Client Services
547,Evelyn,Female,9/22/1998,7:55 PM,51525,10.366,False,Finance
548,Janice,Female,01-02-84,9:06 PM,41190,3.311,True,Sales
549,Sara,Female,2/25/1980,10:50 PM,75484,3.186,False,Finance
551,Philip,Male,7/18/1985,6:36 AM,122319,19.122,False,Engineering
552,Barbara,Female,09-02-91,3:41 PM,127297,11.905,True,Product
553,Amanda,Female,06-07-02,7:46 AM,109290,13.853,False,Engineering
555,Anne,Female,10/26/1996,8:09 PM,71930,18.451,True,Product
557,Jane,Female,06-01-94,8:39 AM,42424,18.115,False,Distribution
558,Linda,Female,8/18/1985,4:34 AM,51431,13.295,False,Engineering
559,Ashley,Female,11/17/1999,9:18 PM,120675,6.510,False,Human Resources
561,Kathleen,Female,9/20/1996,3:45 PM,71430,8.572,False,Engineering
565,Marilyn,Female,08-09-06,11:24 AM,87145,17.330,False,Human Resources
567,NaN,Female,04-01-80,8:04 PM,48141,12.605,NaN,NaN
568,Susan,Female,4/18/1986,9:31 AM,90829,19.142,False,Marketing
569,Ruby,Female,07-07-80,3:42 AM,101262,6.773,False,Client Services
570,Kelly,Female,8/16/1996,3:09 AM,41427,1.431,False,Product
573,Kimberly,Female,12/30/1981,4:51 AM,81800,5.435,True,NaN
574,NaN,Female,1/13/2009,1:01 PM,118736,7.421,NaN,Client Services
578,Amanda,Female,3/17/1982,11:46 PM,107111,1.438,True,Product
583,Diane,Female,02-02-88,6:14 PM,49501,13.506,False,Business Development
585,Shirley,Female,4/16/1988,11:09 AM,132156,2.754,False,Marketing
586,Rose,Female,10/30/2004,4:34 PM,56961,7.585,False,Marketing
587,Cheryl,Female,7/23/1982,6:28 AM,98841,8.945,True,Client Services
588,Cynthia,Female,5/23/1980,3:19 AM,78226,2.419,False,Human Resources
589,Sandra,Female,4/24/1995,7:14 PM,116931,9.657,True,Human Resources
590,Andrea,Female,10/30/1994,11:23 AM,87575,13.346,True,Business Development
591,Rachel,Female,4/22/1988,12:01 PM,110924,7.808,False,Distribution
593,Marie,Female,11/23/2000,5:06 AM,125574,4.644,False,Sales
595,Nancy,Female,05-07-85,10:20 PM,121006,3.512,True,Finance
597,Teresa,Female,6/24/1987,7:37 PM,69740,8.294,False,Distribution
598,Frances,Female,7/21/2001,2:34 AM,91996,11.506,False,Product
599,NaN,Female,10-11-90,10:57 PM,98385,10.925,NaN,Human Resources
605,Rose,Female,5/20/1982,9:14 AM,97691,2.142,False,Client Services
606,Mildred,Female,2/21/1981,3:30 AM,47266,10.256,False,Client Services
608,NaN,Female,10/24/1993,5:17 PM,116236,17.274,NaN,Engineering
616,Kimberly,Female,12-06-86,2:23 PM,37916,12.929,True,Distribution
617,Kathy,Female,1/14/2001,5:11 AM,45682,1.451,True,Marketing
619,Beverly,Female,10/22/1990,2:45 PM,59070,19.064,True,Engineering
622,Irene,Female,6/23/2005,11:03 AM,89780,8.999,True,Sales
623,Irene,Female,11/29/2006,2:14 PM,125018,9.601,True,Legal
625,Cynthia,Female,6/29/2015,6:38 AM,82408,8.701,True,Marketing
626,NaN,Female,4/13/1997,8:03 AM,131755,2.930,NaN,NaN
627,Anne,Female,11/21/1984,12:30 PM,128305,16.636,False,Marketing
629,Debra,Female,03-12-83,12:19 PM,74911,19.513,False,Marketing
632,Rebecca,Female,2/23/1990,3:21 PM,134673,6.878,False,Engineering
633,Andrea,Female,11/17/2011,2:37 PM,123591,6.500,True,Engineering
634,Carl,Male,3/30/1987,5:59 PM,75598,19.289,False,NaN
636,Marilyn,Female,07-02-84,4:06 PM,92430,2.924,False,Engineering
638,Frances,Female,11-12-96,6:08 PM,112467,1.433,False,Business Development
639,Amanda,NaN,08-11-91,2:15 PM,46665,19.391,True,Client Services
640,Kathleen,Female,8/28/2004,10:49 AM,42553,3.756,True,Distribution
641,Amanda,Female,1/25/1995,5:06 AM,102081,5.203,False,Sales
644,Katherine,Female,8/13/1996,12:21 AM,149908,18.912,False,Finance
646,Elizabeth,Female,2/21/2010,7:02 AM,79145,19.780,False,Finance
649,Ruth,Female,2/17/2004,5:38 AM,59969,14.064,True,Finance

In [59]:
## Sample the data

In [87]:
sub_df = df.sample(10)

In [89]:
# to write the output file

sub_df.to_csv("sample_output.csv")

In [90]:
sub_df.to_excel("sample_output.xlsx")

In [92]:
sub_df=sub_df[["Gender","Bonus %","Team"]]

In [94]:
sub_df.shape

(10, 3)

In [95]:
sub_df.head()

    Gender  Bonus %             Team
293   Male    9.653        Marketing
175   Male    1.451      Engineering
417    NaN    9.047  Human Resources
69     NaN    4.382          Finance
328   Male    5.319          Finance

## Sorting

In [101]:
# by default --> ascending order

sub_df.sort_values(by = "Bonus %")

    Gender  Bonus %             Team
175   Male    1.451      Engineering
296    NaN    3.180            Sales
69     NaN    4.382          Finance
328   Male    5.319          Finance
244   Male    8.866  Client Services
417    NaN    9.047  Human Resources
293   Male    9.653        Marketing
704   Male   11.211     Distribution
102   Male   12.159  Client Services
24    Male   13.873  Client Services

In [103]:
# by default --> ascending order

sub_df.sort_values("Bonus %",ascending=False)

    Gender  Bonus %             Team
24    Male   13.873  Client Services
102   Male   12.159  Client Services
704   Male   11.211     Distribution
293   Male    9.653        Marketing
417    NaN    9.047  Human Resources
244   Male    8.866  Client Services
328   Male    5.319          Finance
69     NaN    4.382          Finance
296    NaN    3.180            Sales
175   Male    1.451      Engineering

In [105]:
sub_df.sort_values(["Bonus %","Team"],ascending=[True,False])

    Gender  Bonus %             Team
175   Male    1.451      Engineering
296    NaN    3.180            Sales
69     NaN    4.382          Finance
328   Male    5.319          Finance
244   Male    8.866  Client Services
417    NaN    9.047  Human Resources
293   Male    9.653        Marketing
704   Male   11.211     Distribution
102   Male   12.159  Client Services
24    Male   13.873  Client Services

## Group By 
## important fuctiion

## It is used to see the aggregated results on the dataframe

In [106]:
for i in range(1,13):
    print(i, round(df[df["Salary"]==i]["Team"].mean(),2))

1 nan
2 nan
3 nan
4 nan
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan

In [110]:
df.groupby("Salary")["Bonus %"].mean()
#mnth : Grouping Column
#temp : Aggregating Column
#mean : Aggregating Function

Salary
35013     14.8790
35061      5.1280
35095      8.3790
35203     18.0400
35381     11.7490
35477     18.1780
35575     14.5950
35633      3.9470
35802     12.3910
35884     17.6670
36067      9.6400
36403      2.6640
36643      7.9530
36697     11.1960
36711     19.0280
36749     19.7540
36759     17.2690
36837     14.6600
36844      5.5740
36927     18.7690
36946      6.6520
37005      7.6450
37076     18.5760
37259      1.7630
37385      8.2260
37598      7.7570
37748      9.0470
37812      3.1780
37888     13.4700
37916     12.9290
37919     11.4490
37984      2.0210
38041     18.4280
38078     10.2800
38092      5.6680
38275     10.4940
38344      3.7940
38375      8.9990
38712      3.6570
38872      9.3020
38989      7.0170
39335     10.6640
39371      4.0680
39833      9.6310
40119      4.3380
40121      6.2930
40297      6.1850
40341     17.5780
40451     16.0440
40837     12.1820
41054     12.2990
41126     14.0090
41190      3.3110
41230      6.6110
41238      8.2190
41334      6.2190
41426     14.5430
41427      1.4310
41428     14.3720
41449      4.7070
41453     10.0840
41549      3.9500
41643      4.6590
41808     19.2390
41831      4.5480
41928      5.4780
42025      3.3190
42087      2.6240
42090      8.8420
42146      3.0460
42153      8.4540
42214     17.5380
42296     16.9220
42341      7.0140
42392     19.6750
42424     18.1150
42553      3.7560
42676     15.5170
42748      9.7650
43026     14.1660
43050     11.6710
43252     18.8920
43312      8.2180
43354     13.9460
43414      7.5630
43455     13.0400
43542     19.6870
43586     12.6590
43694      3.7870
44021     10.2860
44486     17.3080
44537     18.2840
44639      9.1480
44836      2.6570
44857     13.2660
45094      5.8500
45150     12.0750
45181      3.4910
45223      8.8790
45267      3.9420
45418     10.1620
45682      1.4510
45724      1.0220
45906     11.5980
46007     19.7310
46080      9.6350
46233      8.8620
46240      6.9760
46378      9.1270
46478     16.5520
46602      1.0270
46665     19.3910
46666      1.8860
46750     11.3670
46829      5.1900
46875     12.9420
46905     19.1540
46930     18.7020
46953     17.4360
47079      2.6170
47176     10.7360
47232     17.8620
47266     10.2560
47322      7.2500
47369     14.8220
47529      2.7120
47605     14.9550
47638     11.2090
47647     18.7870
47885     19.2760
48046      7.7370
48109     14.9950
48141     12.6050
48354     19.5010
48668     11.7160
48696      4.7500
48866      4.2710
49101     11.9000
49325      2.0710
49339      1.6950
49368     14.2260
49473     12.4630
49501     13.5060
49538      9.8280
49542      1.6790
49665     18.3380
50141     13.2180
50167      2.3620
50366      9.8620
50369     18.9000
50426     18.5360
50455     16.2480
50529     17.2630
50645     11.1190
50701     14.2270
50905      9.4040
51065     16.8070
51070     13.8060
51082     11.9550
51178      9.7350
51395      2.3780
51430      6.4600
51431     13.2950
51525     10.3660
51613     12.9840
51633     13.4720
51667      6.3390
51685     17.4450
51821      1.1970
51923     13.6230
52080      9.3750
52119     11.3430
52226     19.1350
52620     13.7730
52730     12.5250
52875      4.1880
52970      4.5130
53061     11.8640
53335      9.1920
53692      4.7850
53754      5.4550
53954     19.0750
54033     15.5280
54043      3.8330
54058      5.1820
54585      4.1660
54941      3.2210
55038     19.6910
55044      4.0780
55281      4.9350
55394      3.1800
56450     19.0400
56526      5.8100
56580      8.4110
56926      7.5070
56961      7.5850
56993     18.6230
57266     14.0770
57286      5.0250
57292      6.0100
57300     18.0150
57325     17.1790
57427      9.5570
57531      1.7670
57783      9.1290
57811      8.9410
57871      4.0200
58047     14.8580
58112     19.4140
58129      1.9520
58248      3.9140
58295     14.6030
58327     17.0950
58357      7.9690
58423     10.8330
58478      6.5250
58520     16.2310
58563     12.0620
58698      6.8110
58755      5.0970
58789      5.4610
59070     19.0640
59148      9.0610
59277     10.2000
59414      1.2560
59678     10.8950
59680     15.2110
59728     11.2260
59862      3.2690
59937     12.0450
59943      1.4320
59969     14.0640
59970     12.8010
60003      9.6240
60263      2.7090
60361      7.0990
60388     17.8850
60411     12.0480
60500     11.9850
60866     13.1010
61117      2.8440
61181     16.5590
61310     12.4280
61602     11.8490
61933      4.1700
61999      6.4660
62096     17.0290
62161      8.1300
62371     15.7700
62454      3.4590
62666     10.2470
62719     19.1270
62913     18.2410
62960     14.3560
63046     10.4110
63103     11.3780
63126     18.4240
63241     15.1320
63395     11.4110
63494     19.3850
63549     19.6240
63571     15.3970
63888     18.1150
64084     17.0180
64088      6.1550
64164     17.6120
64172     10.8940
64207      7.8240
64363      4.0230
64579     15.2660
64714      4.9340
64715     15.1070
65078      3.0950
65168     11.5130
65251     11.2110
65362      7.1320
65476     10.0120
65482     18.0890
65673      1.1870
65931      2.3040
66029      3.3450
66047     18.6740
66067     10.9570
66077      5.8090
66146     11.1780
66224     15.9790
66521      5.8300
66582     11.3080
66604     14.6090
66757     18.0990
66775      2.1580
66819      6.6390
66820      9.0000
66851     11.2790
67150     15.8500
67165     13.0010
67471      2.7280
67656     16.4550
67780      9.5400
67789     17.1050
67811     12.6990
67827     19.7170
68028      7.8690
68164     18.3930
68230      8.0470
68501     14.3160
68680     16.5650
68759     19.3430
69111     14.6250
69112      7.5880
69134      3.7230
69244      6.2200
69267      5.8900
69268      3.0310
69297      1.2680
69579     18.0290
69740      8.2940
69906      4.8440
69989     10.9850
70248      9.6600
70367     18.2660
70492      8.8950
70635      2.1470
70817     17.1380
70990     15.9010
71276      5.0270
71383      2.0970
71430      8.5720
71520     13.2480
71642      1.4960
71715     13.0790
71749     15.9310
71751     15.9180
71853      8.0370
71896      4.2320
71930     18.4510
71945      5.5600
71958      5.2720
71975      9.7700
72002     13.1780
72145     13.4480
72257     13.0230
72613     11.1260
72670      1.4810
72893      9.5550
72979      5.6600
73105      6.0830
73354     18.3570
73437      2.5180
73524      5.2070
73587      9.7690
73706     18.5300
73749     19.3320
73789     14.8410
73935     14.7520
74086      5.7780
74104     17.6800
74129     18.2250
74287     10.7510
74640     18.6410
74669      1.1130
74911     19.5130
75145      6.3880
75147     17.3980
75150     12.1820
75181      6.0600
75415     19.1320
75423      5.3680
75484      3.1860
75498      6.5370
75598     19.2890
75607      4.2990
75661      1.0790
75825      7.8390
76076      5.3190
76078      2.4010
76189     18.9880
76381     11.1590
76394      5.4370
76409      7.0080
76485      9.2120
76707      6.0310
77287     13.0000
77327     11.5800
77544     12.4470
77834     18.7710
77933     13.1320
78226      2.4190
78351     15.2210
78417      3.0670
78883     19.6950
78891      7.9270
79047     18.7840
79123     19.4220
79145     19.7800
79443     14.6370
79459      7.7760
79529      7.0080
79536     14.4430
79582      3.8730
79796      9.8510
79906     18.0210
80399     12.2540
80633     16.3060
80688     18.8920
80740     19.3050
80803     14.0770
80838      8.1150
81014      1.8940
81077      2.1170
81183     17.0660
81206     19.9080
81215      8.4000
81308      2.1960
81444      3.1710
81673     15.3640
81800      5.4350
81839     12.0720
81919     15.1180
82401      7.2520
82408      8.7010
82439     19.0620
82726     16.3040
82744     19.1110
82782      4.3660
82871     17.9990
82873      1.8690
82884      6.8370
83072      7.5110
83112      4.0830
83159      9.5500
83341      1.0150
83658      6.5130
83677      8.9990
83706      6.9600
83809     12.9220
83895     17.9710
84232     15.7040
84546     10.4890
84672      3.9600
84692      6.6170
84693      6.9760
84746      4.8200
84810     15.7940
84834     14.3300
84885     15.4020
85074      1.8440
85182     16.6750
85213      2.3860
85215      7.4250
85446      3.9590
85550     11.5930
85668      1.9090
85700      1.2150
85718     13.3260
85730      5.3590
85789      9.7120
85799     19.9300
85858     19.4750
85871      9.1600
86150      3.9970
86230      8.5780
86318     18.4920
86326     10.7170
86386      2.9370
86439      7.7990
86564     11.8790
86615      3.4120
86676      6.6280
86723     14.8420
86818     14.3010
86883     18.0030
87103      5.6650
87145     17.3300
87298      2.3110
87575     13.3460
87713     18.8630
87715      2.6750
87721     12.4840
87760     14.9870
88010     13.8860
88086     19.3870
88276     14.2480
88657     12.7520
88733      1.9320
89227      3.9960
89258     15.5850
89434     11.2950
89443     17.9400
89661      8.5250
89700      2.2770
89780      8.9990
89786     14.4220
89831     13.0470
89854      7.2270
90187     14.7640
90285     13.5910
90370      7.3690
90427      2.0100
90429      4.4500
90556     15.7490
90582      4.7090
90719      6.2200
90730      2.4910
90816     18.8160
90829     19.1420
90998      8.3820
91109     17.4990
91124     12.9860
91133      5.1400
91344      4.0350
91406      5.6810
91411      8.6390
91462     13.4545
91522      7.5640
91712      8.5670
91719     11.5830
91996     11.5060
92242     15.4070
92430      2.9240
92436     12.4670
92544      3.8000
92587      8.4750
92799      2.7820
93022      9.1460
93201     11.7120
93302      9.0480
93368      2.8800
93581      6.0830
93712     17.4260
93753      7.0940
93847      1.0850
93901     17.8210
93997     18.0930
94088     19.1070
94231     17.5170
94345     11.9960
94393      3.6430
94493     13.4430
94963     19.6260
94976     13.8300
95003      5.1970
95198      2.0750
95296     10.1460
95322      4.1500
95327     15.1200
95389     14.2230
95570     18.5230
95728      6.7520
95734     19.0960
95866     19.3880
96111     15.5920
96250     10.0560
96329      2.4690
96511      9.3310
96610      2.0970
96633      4.9900
96649      3.4530
96795     14.8370
96914      1.4210
96941     10.0480
96978     13.8650
97058      9.4020
97308      6.9450
97364      3.5950
97370     10.4580
97443     13.6570
97480     11.5180
97490      5.4600
97566      2.1470
97635     10.4130
97691      2.1420
97915      3.9970
97950     13.8730
98233      2.5180
98295      7.6170
98385     10.9250
98393     11.3930
98406      7.9430
98753     16.4430
98811      7.4870
98841      8.9450
98858      3.5250
98865     10.6280
98874      4.4790
99150      6.0070
99283      2.6650
99326     16.4750
99747      6.1680
100238     3.8870
100308    13.6770
100341     6.6620
100612    13.6450
100705    16.9610
100765    10.9820
100863     4.3820
100888    12.4900
100949    13.8130
101004     1.3890
101036     2.8260
101262     6.7730
101457     6.6620
101914     1.9050
101941     3.4500
102081     5.2030
102488    17.6530
102508    12.6370
102555     3.6720
102577    12.0260
102589    17.9520
102626    15.8430
102652    14.0850
102697     3.2830
102839    10.3850
102841     3.3690
103050     3.0500
103235     9.5540
103386    11.4510
103405    15.9100
103495    17.2900
103521     2.7840
103557    16.0140
103684    18.6540
103854     4.9240
103877     6.3220
103902    12.1590
104014     7.0770
104058    17.6950
104250    18.4560
104496    14.7710
104749    11.3640
104815     3.3800
104840    15.6530
104896    19.5500
104897     5.1180
105062     1.5630
105066    17.3430
105573     5.2680
105681    19.5720
105689    13.3200
105946     1.1390
106115     3.7420
106249    15.9670
106310     4.0300
106317     2.2350
106362     8.9650
106406     1.7820
106428    10.8670
106472     6.4990
106562     4.0000
106862     3.6990
106947    15.8660
106995    15.7230
107024    12.1820
107050    12.7370
107111     1.4380
107163     3.6650
107281     1.6120
107351     5.3290
107391     1.2600
107816    18.7510
108127    15.8580
108581     9.6340
108946    12.2110
109095     9.4940
109259     4.4430
109260     2.6500
109290    13.8530
109324    19.4880
109411     9.4940
109510    13.4570
109517     5.1460
109564     3.8450
109588     3.5500
109831     5.8310
109980     8.8600
110061     7.4940
110169    13.8920
110194    14.7270
110306    16.8430
110485     7.9950
110924     7.8080
110967    19.6120
111043     5.9660
111163     5.0250
111249    10.5740
111371    15.0810
111376     2.6730
111468     2.5800
111580    10.9820
111737     6.4140
111786     3.5920
111858     1.6010
112117     6.3380
112238     6.0300
112467     1.4330
112548     4.6640
112769    11.6250
112807    17.4920
112975     9.6990
113060     2.8460
113129    17.3710
113425    11.9070
113506    19.6420
113554    18.0180
113590     3.0550
113592    17.1080
113732    10.3910
113760    12.8660
113850     1.8540
114079     8.3990
114244    16.6900
114334     9.6690
114356     7.1230
114360    17.7990
114412     8.7560
114767     3.7110
114796     6.7960
114797     5.9650
114896    13.8230
115057     2.0890
115118     5.1080
115145    14.0630
115149    11.9340
115163    10.1250
115194     5.8610
115280     9.1530
115387     1.8210
115436     3.0990
115566     6.7160
115582    15.3430
115658     3.0410
115711     8.0120
115814     4.9900
115913    12.1210
116236    17.2740
116693    13.8350
116931     9.6570
117055     7.4610
117293     2.3660
117787    10.4850
118037    13.4920
118043     7.2660
118172    16.1940
118369     7.6960
118431    12.7720
118733     9.6530
118736     7.4210
118753     8.1620
118780     9.0960
118840    14.5090
118906     4.5370
119009    12.5060
119082    16.1800
119266     6.9110
119667     1.1480
119735    18.7400
120204     9.5570
120444     7.7680
120672    19.4670
120675     6.5100
120941     3.6940
121006     3.5120
121068    12.7570
121160    10.4180
121232    16.6240
121250     4.3630
121333    15.2950
121357    18.8450
121477    17.4400
121508    19.3340
121604     1.9230
121723    18.6450
121797    16.9230
121816    10.6150
121918    15.8350
122121     7.9370
122173     7.7970
122319    19.1220
122340     6.4170
122367     5.2180
122717    12.4520
122762     9.5640
122897     8.2220
122920     5.3200
122971    14.6180
123144    16.2610
123294    19.8940
123409     7.7830
123591     6.5000
123621    19.7670
123649    10.1540
123711    10.9660
123811     7.6640
123876     4.2250
123940    12.1840
123963    15.7450
124008    13.4640
124365     8.4570
124441    16.3530
124486    10.1660
124488    14.8370
124566     5.9490
124655    14.2720
124889    15.0260
125018     9.6010
125033     4.8870
125104    12.3450
125220     3.7330
125250     2.6720
125298     3.0190
125382    13.6130
125418     8.0640
125556     7.9960
125574     4.6440
125792     5.0420
125881    16.6970
126010    19.6010
126120     1.0200
126232     6.1910
126310     5.4130
126924     1.5520
126956    18.3960
127118    11.1760
127297    11.9050
127654    16.4390
127813     5.9610
128031    15.8570
128036    18.8240
128042     2.0300
128175    18.4730
128305    16.6360
128540    15.9410
128771     8.3090
129148    15.1930
129297     8.0670
129460    13.6570
129663    15.5740
129712    11.0580
129949    10.1690
129968    19.8970
130276    16.0840
130577    12.7910
130581    16.7360
130590    11.8580
130620     7.0300
131038     8.9960
131045    11.3120
131131    11.6820
131423     8.9570
131513     1.8760
131604     7.3530
131755     2.9300
131943    14.2490
131952    12.0900
132084    10.0060
132156     2.7540
132175     2.2800
132327    19.2640
132373    10.5270
132381     8.3400
132483    16.6550
132505    13.5920
132839    17.4630
132940    19.0820
133033    12.2000
133366    12.2920
133472    16.9410
133772    19.0200
133943     8.9400
133980    12.3960
134048     6.8180
134120     6.8420
134148     8.8330
134408     3.5600
134505    11.0510
134598    11.6990
134610     6.1470
134645    18.1970
134673     6.8780
134988    13.9260
135118    15.1080
135119     7.8870
135352     7.9860
135369     4.3800
135490    19.9340
135758    14.7820
135882    19.9440
135990    14.3440
136032    10.6960
136602    10.4290
136604     6.1600
136655     9.8010
136681     3.6550
136709    10.3310
136984     8.9320
137126    15.6020
137144    10.0810
137171     5.5740
137314     4.5420
137359    11.1050
137386     8.6110
137661     4.8050
137840     9.7050
137954     4.1950
137979     5.2660
138598    14.7370
138705     9.3400
138807     1.4000
138925     9.8010
139284    11.3900
139570    15.8040
139754    12.7400
139791    16.9680
139852     7.5240
139917    11.4660
139959     8.9920
140002    19.4900
140013     8.6890
140136     3.1200
140303    17.0700
140347     8.7230
140371    10.6200
140444     3.7710
140502     9.9890
140558     5.0840
140810     9.1770
140850    18.8550
140885     1.1130
141069     4.9030
141305     9.8490
141311     5.4780
141335    15.4270
141439     3.7990
141498     4.1350
141521     4.3370
141932     1.0170
141958     9.0780
142032    12.5990
142178    17.9840
142208    11.2040
142321     1.7370
142373     2.4620
142410    11.0480
142415     1.9850
142561     8.8660
142868     6.3180
142935    13.1980
143499    17.4950
143541     8.4610
143638     9.6620
144001     2.1940
144082     1.6200
144187    11.4160
144474    17.6480
144677     8.6960
144701    16.3230
144709    10.0690
144887     8.2760
145001    19.8500
145146     7.4820
145274    16.3790
145316    18.5170
145329     7.1000
145357     3.4590
145988    18.4640
146129     5.6870
146141     3.6450
146589     4.9050
146651     1.4510
146670    10.7630
146812     1.9650
146907    11.7380
147113    16.1350
147183     9.3735
147309     1.7020
147362     7.8510
147417    11.6260
147635    14.6930
147663    10.2630
147842    16.1580
148115     6.5390
148225     1.8410
148291     6.0020
148339    11.4790
148857     8.7380
148941    11.5170
148985    19.2800
149105    13.7070
149456     3.5330
149563    16.9910
149654     1.8250
149684     7.8640
149903     5.6300
149908    18.9120
Name: Bonus %, dtype: float64

In [114]:
df.groupby("Team")[["Salary"]].mean()

                            Salary
Team
Business Development  91866.316832
Client Services       88224.424528
Distribution          88500.466667
Engineering           94269.195652
Finance               92219.480392
Human Resources       90944.527473
Legal                 89303.613636
Marketing             90435.591837
Product               88665.505263
Sales                 92173.436170

In [115]:
df.groupby("Bonus %")[["Salary"]].median()

           Salary
Bonus %
1.015     83341.0
1.017    141932.0
1.020    126120.0
1.022     45724.0
1.027     46602.0
1.079     75661.0
1.085     93847.0
1.113    107777.0
1.139    105946.0
1.148    119667.0
1.187     65673.0
1.197     51821.0
1.215     85700.0
1.256     59414.0
1.260    107391.0
1.268     69297.0
1.389    101004.0
1.400    138807.0
1.421     96914.0
1.431     41427.0
1.432     59943.0
1.433    112467.0
1.438    107111.0
1.451     96166.5
1.481     72670.0
1.496     71642.0
1.552    126924.0
1.563    105062.0
1.601    111858.0
1.612    107281.0
1.620    144082.0
1.679     49542.0
1.695     49339.0
1.702    147309.0
1.737    142321.0
1.763     37259.0
1.767     57531.0
1.782    106406.0
1.821    115387.0
1.825    149654.0
1.841    148225.0
1.844     85074.0
1.854    113850.0
1.869     82873.0
1.876    131513.0
1.886     46666.0
1.894     81014.0
1.905    101914.0
1.909     85668.0
1.923    121604.0
1.932     88733.0
1.952     58129.0
1.965    146812.0
1.985    142415.0
2.010     90427.0
2.021     37984.0
2.030    128042.0
2.071     49325.0
2.075     95198.0
2.089    115057.0
2.097     83996.5
2.117     81077.0
2.142     97691.0
2.147     84100.5
2.158     66775.0
2.194    144001.0
2.196     81308.0
2.235    106317.0
2.277     89700.0
2.280    132175.0
2.304     65931.0
2.311     87298.0
2.362     50167.0
2.366    117293.0
2.378     51395.0
2.386     85213.0
2.401     76078.0
2.419     78226.0
2.462    142373.0
2.469     96329.0
2.491     90730.0
2.518     85835.0
2.580    111468.0
2.617     47079.0
2.624     42087.0
2.650    109260.0
2.657     44836.0
2.664     36403.0
2.665     99283.0
2.672    125250.0
2.673    111376.0
2.675     87715.0
2.709     60263.0
2.712     47529.0
2.728     67471.0
2.754    132156.0
2.782     92799.0
2.784    103521.0
2.826    101036.0
2.844     61117.0
2.846    113060.0
2.880     93368.0
2.924     92430.0
2.930    131755.0
2.937     86386.0
3.019    125298.0
3.031     69268.0
3.041    115658.0
3.046     42146.0
3.050    103050.0
3.055    113590.0
3.067     78417.0
3.095     65078.0
3.099    115436.0
3.120    140136.0
3.171     81444.0
3.178     37812.0
3.180     55394.0
3.186     75484.0
3.221     54941.0
3.269     59862.0
3.283    102697.0
3.311     41190.0
3.319     42025.0
3.345     66029.0
3.369    102841.0
3.380    104815.0
3.412     86615.0
3.450    101941.0
3.453     96649.0
3.459    103905.5
3.491     45181.0
3.512    121006.0
3.525     98858.0
3.533    149456.0
3.550    109588.0
3.560    134408.0
3.592    111786.0
3.595     97364.0
3.643     94393.0
3.645    146141.0
3.655    136681.0
3.657     38712.0
3.665    107163.0
3.672    102555.0
3.694    120941.0
3.699    106862.0
3.711    114767.0
3.723     69134.0
3.733    125220.0
3.742    106115.0
3.756     42553.0
3.771    140444.0
3.787     43694.0
3.794     38344.0
3.799    141439.0
3.800     92544.0
3.833     54043.0
3.845    109564.0
3.873     79582.0
3.887    100238.0
3.914     58248.0
3.942     45267.0
3.947     35633.0
3.950     41549.0
3.959     85446.0
3.960     84672.0
3.996     89227.0
3.997     92032.5
4.000    106562.0
4.020     57871.0
4.023     64363.0
4.030    106310.0
4.035     91344.0
4.068     39371.0
4.078     55044.0
4.083     83112.0
4.135    141498.0
4.150     95322.0
4.166     54585.0
4.170     61933.0
4.188     52875.0
4.195    137954.0
4.225    123876.0
4.232     71896.0
4.271     48866.0
4.299     75607.0
4.337    141521.0
4.338     40119.0
4.363    121250.0
4.366     82782.0
4.380    135369.0
4.382    100863.0
4.443    109259.0
4.450     90429.0
4.479     98874.0
4.513     52970.0
4.537    118906.0
4.542    137314.0
4.548     41831.0
4.644    125574.0
4.659     41643.0
4.664    112548.0
4.707     41449.0
4.709     90582.0
4.750     48696.0
4.785     53692.0
4.805    137661.0
4.820     84746.0
4.844     69906.0
4.887    125033.0
4.903    141069.0
4.905    146589.0
4.924    103854.0
4.934     64714.0
4.935     55281.0
4.990    106223.5
5.025     84224.5
5.027     71276.0
5.042    125792.0
5.084    140558.0
5.097     58755.0
5.108    115118.0
5.118    104897.0
5.128     35061.0
5.140     91133.0
5.146    109517.0
5.182     54058.0
5.190     46829.0
5.197     95003.0
5.203    102081.0
5.207     73524.0
5.218    122367.0
5.266    137979.0
5.268    105573.0
5.272     71958.0
5.319     76076.0
5.320    122920.0
5.329    107351.0
5.359     85730.0
5.368     75423.0
5.413    126310.0
5.435     81800.0
5.437     76394.0
5.455     53754.0
5.460     97490.0
5.461     58789.0
5.478     91619.5
5.560     71945.0
5.574     87007.5
5.630    149903.0
5.660     72979.0
5.665     87103.0
5.668     38092.0
5.681     91406.0
5.687    146129.0
5.778     74086.0
5.809     66077.0
5.810     56526.0
5.830     66521.0
5.831    109831.0
5.850     45094.0
5.861    115194.0
5.890     69267.0
5.949    124566.0
5.961    127813.0
5.965    114797.0
5.966    111043.0
6.002    148291.0
6.007     99150.0
6.010     57292.0
6.030    112238.0
6.031     76707.0
6.060     75181.0
6.081     86676.0
6.083     83343.0
6.147    134610.0
6.155     64088.0
6.160    136604.0
6.168     99747.0
6.185     40297.0
6.191    126232.0
6.219     41334.0
6.220     79981.5
6.293     40121.0
6.318    142868.0
6.322    103877.0
6.338    112117.0
6.339     51667.0
6.388     75145.0
6.414    111737.0
6.417    122340.0
6.460     51430.0
6.466     61999.0
6.499    106472.0
6.500    123591.0
6.510    120675.0
6.513     83658.0
6.525     58478.0
6.537     75498.0
6.539    148115.0
6.611     41230.0
6.617     84692.0
6.639     66819.0
6.652     36946.0
6.662    100899.0
6.716    115566.0
6.752     95728.0
6.773    101262.0
6.796    114796.0
6.811     58698.0
6.818    134048.0
6.837     82884.0
6.842    134120.0
6.878    134673.0
6.911    119266.0
6.945     97308.0
6.960     83706.0
6.976     65466.5
7.008     77969.0
7.014     42341.0
7.017     38989.0
7.030    130620.0
7.077    104014.0
7.094     93753.0
7.099     60361.0
7.100    145329.0
7.123    114356.0
7.132     65362.0
7.175     86676.0
7.227     89854.0
7.250     47322.0
7.252     82401.0
7.266    118043.0
7.353    131604.0
7.369     90370.0
7.421    118736.0
7.425     85215.0
7.461    117055.0
7.482    145146.0
7.487     98811.0
7.494    110061.0
7.507     56926.0
7.511     83072.0
7.524    139852.0
7.563     43414.0
7.564     91522.0
7.585     56961.0
7.588     69112.0
7.617     98295.0
7.645     37005.0
7.664    123811.0
7.696    118369.0
7.737     48046.0
7.757     37598.0
7.768    120444.0
7.776     79459.0
7.783    123409.0
7.797    122173.0
7.799     86439.0
7.808    110924.0
7.824     64207.0
7.839     75825.0
7.843    121160.0
7.851    147362.0
7.864    149684.0
7.869     68028.0
7.887    135119.0
7.927     78891.0
7.937    122121.0
7.943     98406.0
7.953     36643.0
7.969     58357.0
7.986    135352.0
7.995    110485.0
7.996    125556.0
8.012    115711.0
8.037     71853.0
8.047     68230.0
8.064    125418.0
8.067    129297.0
8.115     80838.0
8.130     62161.0
8.162    118753.0
8.205     91462.0
8.218     43312.0
8.219     41238.0
8.222    122897.0
8.226     37385.0
8.276    144887.0
8.294     69740.0
8.309    128771.0
8.340    132381.0
8.379     35095.0
8.382     90998.0
8.399    114079.0
8.400     81215.0
8.411     56580.0
8.454     42153.0
8.457    124365.0
8.461    143541.0
8.475     92587.0
8.525     89661.0
8.567     91712.0
8.572     71430.0
8.578     86230.0
8.611    137386.0
8.639     91411.0
8.689    140013.0
8.696    144677.0
8.701     82408.0
8.723    140347.0
8.738    148857.0
8.748    147183.0
8.756    114412.0
8.833    134148.0
8.842     42090.0
8.860    109980.0
8.862     46233.0
8.866    142561.0
8.879     45223.0
8.895     70492.0
8.932    136984.0
8.940    133943.0
8.941     57811.0
8.945     98841.0
8.957    131423.0
8.965    106362.0
8.992    139959.0
8.996    131038.0
8.999     83677.0
9.000     66820.0
9.047     37748.0
9.048     93302.0
9.061     59148.0
9.078    141958.0
9.096    118780.0
9.127     46378.0
9.129     57783.0
9.146     93022.0
9.148     44639.0
9.153    115280.0
9.160     85871.0
9.177    140810.0
9.192     53335.0
9.212     76485.0
9.302     38872.0
9.331     96511.0
9.340    138705.0
9.375     52080.0
9.402     97058.0
9.404     50905.0
9.494    109253.0
9.540     67780.0
9.550     83159.0
9.554    103235.0
9.555     72893.0
9.557     88815.5
9.564    122762.0
9.601    125018.0
9.624     60003.0
9.631     39833.0
9.634    108581.0
9.635     46080.0
9.640     36067.0
9.653    118733.0
9.657    116931.0
9.660     70248.0
9.662    143638.0
9.669    114334.0
9.699    112975.0
9.705    137840.0
9.712     85789.0
9.735     51178.0
9.765     42748.0
9.769     73587.0
9.770     71975.0
9.801    137790.0
9.828     49538.0
9.849    141305.0
9.851     79796.0
9.862     50366.0
9.989    140502.0
9.999    147183.0
10.006   132084.0
10.012    65476.0
10.048    96941.0
10.056    96250.0
10.069   144709.0
10.081   137144.0
10.084    41453.0
10.125   115163.0
10.146    95296.0
10.154   123649.0
10.162    45418.0
10.166   124486.0
10.169   129949.0
10.200    59277.0
10.247    62666.0
10.256    47266.0
10.263   147663.0
10.280    38078.0
10.286    44021.0
10.331   136709.0
10.366    51525.0
10.385   102839.0
10.391   113732.0
10.411    63046.0
10.413    97635.0
10.429   136602.0
10.458    97370.0
10.485   117787.0
10.489    84546.0
10.494    38275.0
10.527   132373.0
10.574   111249.0
10.615   121816.0
10.620   140371.0
10.628    98865.0
10.664    39335.0
10.696   136032.0
10.717    86326.0
10.736    47176.0
10.751    74287.0
10.763   146670.0
10.833    58423.0
10.867   106428.0
10.894    64172.0
10.895    59678.0
10.925    98385.0
10.957    66067.0
10.966   123711.0
10.982   106172.5
10.985    69989.0
11.048   142410.0
11.051   134505.0
11.058   129712.0
11.105   137359.0
11.119    50645.0
11.126    72613.0
11.159    76381.0
11.176   127118.0
11.178    66146.0
11.196    36697.0
11.204   142208.0
11.209    47638.0
11.211    65251.0
11.226    59728.0
11.279    66851.0
11.295    89434.0
11.308    66582.0
11.312   131045.0
11.343    52119.0
11.364   104749.0
11.367    46750.0
11.378    63103.0
11.390   139284.0
11.393    98393.0
11.411    63395.0
11.416   144187.0
11.449    37919.0
11.451   103386.0
11.466   139917.0
11.479   148339.0
11.506    91996.0
11.513    65168.0
11.517   148941.0
11.518    97480.0
11.580    77327.0
11.583    91719.0
11.593    85550.0
11.598    45906.0
11.625   112769.0
11.626   147417.0
11.671    43050.0
11.682   131131.0
11.699   134598.0
11.712    93201.0
11.716    48668.0
11.738   146907.0
11.749    35381.0
11.849    61602.0
11.858   130590.0
11.864    53061.0
11.879    86564.0
11.900    49101.0
11.905   127297.0
11.907   113425.0
11.934   115149.0
11.955    51082.0
11.985    60500.0
11.996    94345.0
12.026   102577.0
12.045    59937.0
12.048    60411.0
12.062    58563.0
12.072    81839.0
12.075    45150.0
12.090   131952.0
12.121   115913.0
12.159   103902.0
12.182    75150.0
12.184   123940.0
12.200   133033.0
12.211   108946.0
12.254    80399.0
12.292   133366.0
12.299    41054.0
12.345   125104.0
12.391    35802.0
12.396   133980.0
12.428    61310.0
12.447    77544.0
12.452   122717.0
12.463    49473.0
12.467    92436.0
12.484    87721.0
12.490   100888.0
12.506   119009.0
12.525    52730.0
12.599   142032.0
12.605    48141.0
12.637   102508.0
12.659    43586.0
12.699    67811.0
12.737   107050.0
12.740   139754.0
12.752    88657.0
12.757   121068.0
12.772   118431.0
12.791   130577.0
12.801    59970.0
12.866   113760.0
12.922    83809.0
12.929    37916.0
12.942    46875.0
12.984    51613.0
12.986    91124.0
12.993   121160.0
13.000    77287.0
13.001    67165.0
13.023    72257.0
13.040    43455.0
13.047    89831.0
13.079    71715.0
13.101    60866.0
13.132    77933.0
13.178    72002.0
13.198   142935.0
13.218    50141.0
13.248    71520.0
13.266    44857.0
13.295    51431.0
13.320   105689.0
13.326    85718.0
13.346    87575.0
13.443    94493.0
13.448    72145.0
13.457   109510.0
13.464   124008.0
13.470    37888.0
13.472    51633.0
13.492   118037.0
13.506    49501.0
13.591    90285.0
13.592   132505.0
13.613   125382.0
13.623    51923.0
13.645   100612.0
13.657   113451.5
13.677   100308.0
13.707   149105.0
13.773    52620.0
13.806    51070.0
13.813   100949.0
13.823   114896.0
13.830    94976.0
13.835   116693.0
13.853   109290.0
13.865    96978.0
13.873    97950.0
13.886    88010.0
13.892   110169.0
13.926   134988.0
13.946    43354.0
14.009    41126.0
14.063   115145.0
14.064    59969.0
14.077    69034.5
14.085   102652.0
14.166    43026.0
14.223    95389.0
14.226    49368.0
14.227    50701.0
14.248    88276.0
14.249   131943.0
14.272   124655.0
14.301    86818.0
14.316    68501.0
14.330    84834.0
14.344   135990.0
14.356    62960.0
14.372    41428.0
14.422    89786.0
14.443    79536.0
14.509   118840.0
14.543    41426.0
14.595    35575.0
14.603    58295.0
14.609    66604.0
14.618   122971.0
14.625    69111.0
14.637    79443.0
14.660    36837.0
14.693   147635.0
14.727   110194.0
14.737   138598.0
14.752    73935.0
14.764    90187.0
14.771   104496.0
14.782   135758.0
14.822    47369.0
14.837   110641.5
14.841    73789.0
14.842    86723.0
14.858    58047.0
14.879    35013.0
14.955    47605.0
14.987    87760.0
14.995    48109.0
15.026   124889.0
15.081   111371.0
15.107    64715.0
15.108   135118.0
15.118    81919.0
15.120    95327.0
15.132    63241.0
15.193   129148.0
15.211    59680.0
15.221    78351.0
15.266    64579.0
15.295   121333.0
15.343   115582.0
15.364    81673.0
15.397    63571.0
15.402    84885.0
15.407    92242.0
15.427   141335.0
15.517    42676.0
15.528    54033.0
15.574   129663.0
15.585    89258.0
15.592    96111.0
15.602   137126.0
15.653   104840.0
15.704    84232.0
15.723   106995.0
15.745   123963.0
15.749    90556.0
15.770    62371.0
15.794    84810.0
15.804   139570.0
15.835   121918.0
15.843   102626.0
15.850    67150.0
15.857   128031.0
15.858   108127.0
15.866   106947.0
15.901    70990.0
15.910   103405.0
15.918    71751.0
15.931    71749.0
15.941   128540.0
15.967   106249.0
15.979    66224.0
16.014   103557.0
16.044    40451.0
16.084   130276.0
16.135   147113.0
16.158   147842.0
16.180   119082.0
16.194   118172.0
16.231    58520.0
16.248    50455.0
16.261   123144.0
16.304    82726.0
16.306    80633.0
16.323   144701.0
16.353   124441.0
16.379   145274.0
16.439   127654.0
16.443    98753.0
16.455    67656.0
16.475    99326.0
16.552    46478.0
16.559    61181.0
16.565    68680.0
16.624   121232.0
16.636   128305.0
16.655   132483.0
16.675    85182.0
16.690   114244.0
16.697   125881.0
16.736   130581.0
16.807    51065.0
16.843   110306.0
16.922    42296.0
16.923   121797.0
16.941   133472.0
16.961   100705.0
16.968   139791.0
16.991   149563.0
17.018    64084.0
17.029    62096.0
17.066    81183.0
17.070   140303.0
17.095    58327.0
17.105    67789.0
17.108   113592.0
17.138    70817.0
17.179    57325.0
17.263    50529.0
17.269    36759.0
17.274   116236.0
17.290   103495.0
17.308    44486.0
17.330    87145.0
17.343   105066.0
17.371   113129.0
17.398    75147.0
17.426    93712.0
17.436    46953.0
17.440   121477.0
17.445    51685.0
17.463   132839.0
17.492   112807.0
17.495   143499.0
17.499    91109.0
17.517    94231.0
17.538    42214.0
17.578    40341.0
17.612    64164.0
17.648   144474.0
17.653   102488.0
17.667    35884.0
17.680    74104.0
17.695   104058.0
17.799   114360.0
17.821    93901.0
17.862    47232.0
17.885    60388.0
17.940    89443.0
17.952   102589.0
17.971    83895.0
17.984   142178.0
17.999    82871.0
18.003    86883.0
18.015    57300.0
18.018   113554.0
18.021    79906.0
18.029    69579.0
18.040    35203.0
18.089    65482.0
18.093    93997.0
18.099    66757.0
18.115    53156.0
18.178    35477.0
18.197   134645.0
18.225    74129.0
18.241    62913.0
18.243   145988.0
18.266    70367.0
18.284    44537.0
18.338    49665.0
18.357    73354.0
18.393    68164.0
18.396   126956.0
18.424    63126.0
18.428    38041.0
18.451    71930.0
18.456   104250.0
18.473   128175.0
18.492    86318.0
18.517   145316.0
18.523    95570.0
18.530    73706.0
18.536    50426.0
18.576    37076.0
18.623    56993.0
18.641    74640.0
18.645   121723.0
18.654   103684.0
18.674    66047.0
18.685   145988.0
18.702    46930.0
18.704    91462.0
18.740   119735.0
18.751   107816.0
18.769    36927.0
18.771    77834.0
18.784    79047.0
18.787    47647.0
18.816    90816.0
18.824   128036.0
18.845   121357.0
18.855   140850.0
18.863    87713.0
18.892    61970.0
18.900    50369.0
18.912   149908.0
18.988    76189.0
19.020   133772.0
19.028    36711.0
19.040    56450.0
19.062    82439.0
19.064    59070.0
19.075    53954.0
19.082   132940.0
19.096    95734.0
19.107    94088.0
19.111    82744.0
19.122   122319.0
19.127    62719.0
19.132    75415.0
19.135    52226.0
19.142    90829.0
19.154    46905.0
19.239    41808.0
19.264   132327.0
19.276    47885.0
19.280   148985.0
19.289    75598.0
19.305    80740.0
19.332    73749.0
19.334   121508.0
19.343    68759.0
19.385    63494.0
19.387    88086.0
19.388    95866.0
19.391    46665.0
19.414    58112.0
19.422    79123.0
19.467   120672.0
19.475    85858.0
19.488   109324.0
19.490   140002.0
19.501    48354.0
19.513    74911.0
19.550   104896.0
19.572   105681.0
19.601   126010.0
19.612   110967.0
19.624    63549.0
19.626    94963.0
19.642   113506.0
19.675    42392.0
19.687    43542.0
19.691    55038.0
19.695    78883.0
19.717    67827.0
19.731    46007.0
19.754    36749.0
19.767   123621.0
19.780    79145.0
19.850   145001.0
19.894   123294.0
19.897   129968.0
19.908    81206.0
19.930    85799.0
19.934   135490.0
19.944   135882.0

In [117]:
d={"Salary":["max","min","mean"],"Bonus %":["median","std"]}
df.groupby("Salary").agg(d)

        Salary                    Bonus %
           max     min      mean   median       std
Salary
35013    35013   35013   35013.0  14.8790       NaN
35061    35061   35061   35061.0   5.1280       NaN
35095    35095   35095   35095.0   8.3790       NaN
35203    35203   35203   35203.0  18.0400       NaN
35381    35381   35381   35381.0  11.7490       NaN
35477    35477   35477   35477.0  18.1780       NaN
35575    35575   35575   35575.0  14.5950       NaN
35633    35633   35633   35633.0   3.9470       NaN
35802    35802   35802   35802.0  12.3910       NaN
35884    35884   35884   35884.0  17.6670       NaN
36067    36067   36067   36067.0   9.6400       NaN
36403    36403   36403   36403.0   2.6640       NaN
36643    36643   36643   36643.0   7.9530       NaN
36697    36697   36697   36697.0  11.1960       NaN
36711    36711   36711   36711.0  19.0280       NaN
36749    36749   36749   36749.0  19.7540       NaN
36759    36759   36759   36759.0  17.2690       NaN
36837    36837   36837   36837.0  14.6600       NaN
36844    36844   36844   36844.0   5.5740       NaN
36927    36927   36927   36927.0  18.7690       NaN
36946    36946   36946   36946.0   6.6520       NaN
37005    37005   37005   37005.0   7.6450       NaN
37076    37076   37076   37076.0  18.5760       NaN
37259    37259   37259   37259.0   1.7630       NaN
37385    37385   37385   37385.0   8.2260       NaN
37598    37598   37598   37598.0   7.7570       NaN
37748    37748   37748   37748.0   9.0470       NaN
37812    37812   37812   37812.0   3.1780       NaN
37888    37888   37888   37888.0  13.4700       NaN
37916    37916   37916   37916.0  12.9290       NaN
37919    37919   37919   37919.0  11.4490       NaN
37984    37984   37984   37984.0   2.0210       NaN
38041    38041   38041   38041.0  18.4280       NaN
38078    38078   38078   38078.0  10.2800       NaN
38092    38092   38092   38092.0   5.6680       NaN
38275    38275   38275   38275.0  10.4940       NaN
38344    38344   38344   38344.0   3.7940       NaN
38375    38375   38375   38375.0   8.9990       NaN
38712    38712   38712   38712.0   3.6570       NaN
38872    38872   38872   38872.0   9.3020       NaN
38989    38989   38989   38989.0   7.0170       NaN
39335    39335   39335   39335.0  10.6640       NaN
39371    39371   39371   39371.0   4.0680       NaN
39833    39833   39833   39833.0   9.6310       NaN
40119    40119   40119   40119.0   4.3380       NaN
40121    40121   40121   40121.0   6.2930       NaN
40297    40297   40297   40297.0   6.1850       NaN
40341    40341   40341   40341.0  17.5780       NaN
40451    40451   40451   40451.0  16.0440       NaN
40837    40837   40837   40837.0  12.1820       NaN
41054    41054   41054   41054.0  12.2990       NaN
41126    41126   41126   41126.0  14.0090       NaN
41190    41190   41190   41190.0   3.3110       NaN
41230    41230   41230   41230.0   6.6110       NaN
41238    41238   41238   41238.0   8.2190       NaN
41334    41334   41334   41334.0   6.2190       NaN
41426    41426   41426   41426.0  14.5430       NaN
41427    41427   41427   41427.0   1.4310       NaN
41428    41428   41428   41428.0  14.3720       NaN
41449    41449   41449   41449.0   4.7070       NaN
41453    41453   41453   41453.0  10.0840       NaN
41549    41549   41549   41549.0   3.9500       NaN
41643    41643   41643   41643.0   4.6590       NaN
41808    41808   41808   41808.0  19.2390       NaN
41831    41831   41831   41831.0   4.5480       NaN
41928    41928   41928   41928.0   5.4780       NaN
42025    42025   42025   42025.0   3.3190       NaN
42087    42087   42087   42087.0   2.6240       NaN
42090    42090   42090   42090.0   8.8420       NaN
42146    42146   42146   42146.0   3.0460       NaN
42153    42153   42153   42153.0   8.4540       NaN
42214    42214   42214   42214.0  17.5380       NaN
42296    42296   42296   42296.0  16.9220       NaN
42341    42341   42341   42341.0   7.0140       NaN
42392    42392   42392   42392.0  19.6750       NaN
42424    42424   42424   42424.0  18.1150       NaN
42553    42553   42553   42553.0   3.7560       NaN
42676    42676   42676   42676.0  15.5170       NaN
42748    42748   42748   42748.0   9.7650       NaN
43026    43026   43026   43026.0  14.1660       NaN
43050    43050   43050   43050.0  11.6710       NaN
43252    43252   43252   43252.0  18.8920       NaN
43312    43312   43312   43312.0   8.2180       NaN
43354    43354   43354   43354.0  13.9460       NaN
43414    43414   43414   43414.0   7.5630       NaN
43455    43455   43455   43455.0  13.0400       NaN
43542    43542   43542   43542.0  19.6870       NaN
43586    43586   43586   43586.0  12.6590       NaN
43694    43694   43694   43694.0   3.7870       NaN
44021    44021   44021   44021.0  10.2860       NaN
44486    44486   44486   44486.0  17.3080       NaN
44537    44537   44537   44537.0  18.2840       NaN
44639    44639   44639   44639.0   9.1480       NaN
44836    44836   44836   44836.0   2.6570       NaN
44857    44857   44857   44857.0  13.2660       NaN
45094    45094   45094   45094.0   5.8500       NaN
45150    45150   45150   45150.0  12.0750       NaN
45181    45181   45181   45181.0   3.4910       NaN
45223    45223   45223   45223.0   8.8790       NaN
45267    45267   45267   45267.0   3.9420       NaN
45418    45418   45418   45418.0  10.1620       NaN
45682    45682   45682   45682.0   1.4510       NaN
45724    45724   45724   45724.0   1.0220       NaN
45906    45906   45906   45906.0  11.5980       NaN
46007    46007   46007   46007.0  19.7310       NaN
46080    46080   46080   46080.0   9.6350       NaN
46233    46233   46233   46233.0   8.8620       NaN
46240    46240   46240   46240.0   6.9760       NaN
46378    46378   46378   46378.0   9.1270       NaN
46478    46478   46478   46478.0  16.5520       NaN
46602    46602   46602   46602.0   1.0270       NaN
46665    46665   46665   46665.0  19.3910       NaN
46666    46666   46666   46666.0   1.8860       NaN
46750    46750   46750   46750.0  11.3670       NaN
46829    46829   46829   46829.0   5.1900       NaN
46875    46875   46875   46875.0  12.9420       NaN
46905    46905   46905   46905.0  19.1540       NaN
46930    46930   46930   46930.0  18.7020       NaN
46953    46953   46953   46953.0  17.4360       NaN
47079    47079   47079   47079.0   2.6170       NaN
47176    47176   47176   47176.0  10.7360       NaN
47232    47232   47232   47232.0  17.8620       NaN
47266    47266   47266   47266.0  10.2560       NaN
47322    47322   47322   47322.0   7.2500       NaN
47369    47369   47369   47369.0  14.8220       NaN
47529    47529   47529   47529.0   2.7120       NaN
47605    47605   47605   47605.0  14.9550       NaN
47638    47638   47638   47638.0  11.2090       NaN
47647    47647   47647   47647.0  18.7870       NaN
47885    47885   47885   47885.0  19.2760       NaN
48046    48046   48046   48046.0   7.7370       NaN
48109    48109   48109   48109.0  14.9950       NaN
48141    48141   48141   48141.0  12.6050       NaN
48354    48354   48354   48354.0  19.5010       NaN
48668    48668   48668   48668.0  11.7160       NaN
48696    48696   48696   48696.0   4.7500       NaN
48866    48866   48866   48866.0   4.2710       NaN
49101    49101   49101   49101.0  11.9000       NaN
49325    49325   49325   49325.0   2.0710       NaN
49339    49339   49339   49339.0   1.6950       NaN
49368    49368   49368   49368.0  14.2260       NaN
49473    49473   49473   49473.0  12.4630       NaN
49501    49501   49501   49501.0  13.5060       NaN
49538    49538   49538   49538.0   9.8280       NaN
49542    49542   49542   49542.0   1.6790       NaN
49665    49665   49665   49665.0  18.3380       NaN
50141    50141   50141   50141.0  13.2180       NaN
50167    50167   50167   50167.0   2.3620       NaN
50366    50366   50366   50366.0   9.8620       NaN
50369    50369   50369   50369.0  18.9000       NaN
50426    50426   50426   50426.0  18.5360       NaN
50455    50455   50455   50455.0  16.2480       NaN
50529    50529   50529   50529.0  17.2630       NaN
50645    50645   50645   50645.0  11.1190       NaN
50701    50701   50701   50701.0  14.2270       NaN
50905    50905   50905   50905.0   9.4040       NaN
51065    51065   51065   51065.0  16.8070       NaN
51070    51070   51070   51070.0  13.8060       NaN
51082    51082   51082   51082.0  11.9550       NaN
51178    51178   51178   51178.0   9.7350       NaN
51395    51395   51395   51395.0   2.3780       NaN
51430    51430   51430   51430.0   6.4600       NaN
51431    51431   51431   51431.0  13.2950       NaN
51525    51525   51525   51525.0  10.3660       NaN
51613    51613   51613   51613.0  12.9840       NaN
51633    51633   51633   51633.0  13.4720       NaN
51667    51667   51667   51667.0   6.3390       NaN
51685    51685   51685   51685.0  17.4450       NaN
51821    51821   51821   51821.0   1.1970       NaN
51923    51923   51923   51923.0  13.6230       NaN
52080    52080   52080   52080.0   9.3750       NaN
52119    52119   52119   52119.0  11.3430       NaN
52226    52226   52226   52226.0  19.1350       NaN
52620    52620   52620   52620.0  13.7730       NaN
52730    52730   52730   52730.0  12.5250       NaN
52875    52875   52875   52875.0   4.1880       NaN
52970    52970   52970   52970.0   4.5130       NaN
53061    53061   53061   53061.0  11.8640       NaN
53335    53335   53335   53335.0   9.1920       NaN
53692    53692   53692   53692.0   4.7850       NaN
53754    53754   53754   53754.0   5.4550       NaN
53954    53954   53954   53954.0  19.0750       NaN
54033    54033   54033   54033.0  15.5280       NaN
54043    54043   54043   54043.0   3.8330       NaN
54058    54058   54058   54058.0   5.1820       NaN
54585    54585   54585   54585.0   4.1660       NaN
54941    54941   54941   54941.0   3.2210       NaN
55038    55038   55038   55038.0  19.6910       NaN
55044    55044   55044   55044.0   4.0780       NaN
55281    55281   55281   55281.0   4.9350       NaN
55394    55394   55394   55394.0   3.1800       NaN
56450    56450   56450   56450.0  19.0400       NaN
56526    56526   56526   56526.0   5.8100       NaN
56580    56580   56580   56580.0   8.4110       NaN
56926    56926   56926   56926.0   7.5070       NaN
56961    56961   56961   56961.0   7.5850       NaN
56993    56993   56993   56993.0  18.6230       NaN
57266    57266   57266   57266.0  14.0770       NaN
57286    57286   57286   57286.0   5.0250       NaN
57292    57292   57292   57292.0   6.0100       NaN
57300    57300   57300   57300.0  18.0150       NaN
57325    57325   57325   57325.0  17.1790       NaN
57427    57427   57427   57427.0   9.5570       NaN
57531    57531   57531   57531.0   1.7670       NaN
57783    57783   57783   57783.0   9.1290       NaN
57811    57811   57811   57811.0   8.9410       NaN
57871    57871   57871   57871.0   4.0200       NaN
58047    58047   58047   58047.0  14.8580       NaN
58112    58112   58112   58112.0  19.4140       NaN
58129    58129   58129   58129.0   1.9520       NaN
58248    58248   58248   58248.0   3.9140       NaN
58295    58295   58295   58295.0  14.6030       NaN
58327    58327   58327   58327.0  17.0950       NaN
58357    58357   58357   58357.0   7.9690       NaN
58423    58423   58423   58423.0  10.8330       NaN
58478    58478   58478   58478.0   6.5250       NaN
58520    58520   58520   58520.0  16.2310       NaN
58563    58563   58563   58563.0  12.0620       NaN
58698    58698   58698   58698.0   6.8110       NaN
58755    58755   58755   58755.0   5.0970       NaN
58789    58789   58789   58789.0   5.4610       NaN
59070    59070   59070   59070.0  19.0640       NaN
59148    59148   59148   59148.0   9.0610       NaN
59277    59277   59277   59277.0  10.2000       NaN
59414    59414   59414   59414.0   1.2560       NaN
59678    59678   59678   59678.0  10.8950       NaN
59680    59680   59680   59680.0  15.2110       NaN
59728    59728   59728   59728.0  11.2260       NaN
59862    59862   59862   59862.0   3.2690       NaN
59937    59937   59937   59937.0  12.0450       NaN
59943    59943   59943   59943.0   1.4320       NaN
59969    59969   59969   59969.0  14.0640       NaN
59970    59970   59970   59970.0  12.8010       NaN
60003    60003   60003   60003.0   9.6240       NaN
60263    60263   60263   60263.0   2.7090       NaN
60361    60361   60361   60361.0   7.0990       NaN
60388    60388   60388   60388.0  17.8850       NaN
60411    60411   60411   60411.0  12.0480       NaN
60500    60500   60500   60500.0  11.9850       NaN
60866    60866   60866   60866.0  13.1010       NaN
61117    61117   61117   61117.0   2.8440       NaN
61181    61181   61181   61181.0  16.5590       NaN
61310    61310   61310   61310.0  12.4280       NaN
61602    61602   61602   61602.0  11.8490       NaN
61933    61933   61933   61933.0   4.1700       NaN
61999    61999   61999   61999.0   6.4660       NaN
62096    62096   62096   62096.0  17.0290       NaN
62161    62161   62161   62161.0   8.1300       NaN
62371    62371   62371   62371.0  15.7700       NaN
62454    62454   62454   62454.0   3.4590       NaN
62666    62666   62666   62666.0  10.2470       NaN
62719    62719   62719   62719.0  19.1270       NaN
62913    62913   62913   62913.0  18.2410       NaN
62960    62960   62960   62960.0  14.3560       NaN
63046    63046   63046   63046.0  10.4110       NaN
63103    63103   63103   63103.0  11.3780       NaN
63126    63126   63126   63126.0  18.4240       NaN
63241    63241   63241   63241.0  15.1320       NaN
63395    63395   63395   63395.0  11.4110       NaN
63494    63494   63494   63494.0  19.3850       NaN
63549    63549   63549   63549.0  19.6240       NaN
63571    63571   63571   63571.0  15.3970       NaN
63888    63888   63888   63888.0  18.1150       NaN
64084    64084   64084   64084.0  17.0180       NaN
64088    64088   64088   64088.0   6.1550       NaN
64164    64164   64164   64164.0  17.6120       NaN
64172    64172   64172   64172.0  10.8940       NaN
64207    64207   64207   64207.0   7.8240       NaN
64363    64363   64363   64363.0   4.0230       NaN
64579    64579   64579   64579.0  15.2660       NaN
64714    64714   64714   64714.0   4.9340       NaN
64715    64715   64715   64715.0  15.1070       NaN
65078    65078   65078   65078.0   3.0950       NaN
65168    65168   65168   65168.0  11.5130       NaN
65251    65251   65251   65251.0  11.2110       NaN
65362    65362   65362   65362.0   7.1320       NaN
65476    65476   65476   65476.0  10.0120       NaN
65482    65482   65482   65482.0  18.0890       NaN
65673    65673   65673   65673.0   1.1870       NaN
65931    65931   65931   65931.0   2.3040       NaN
66029    66029   66029   66029.0   3.3450       NaN
66047    66047   66047   66047.0  18.6740       NaN
66067    66067   66067   66067.0  10.9570       NaN
66077    66077   66077   66077.0   5.8090       NaN
66146    66146   66146   66146.0  11.1780       NaN
66224    66224   66224   66224.0  15.9790       NaN
66521    66521   66521   66521.0   5.8300       NaN
66582    66582   66582   66582.0  11.3080       NaN
66604    66604   66604   66604.0  14.6090       NaN
66757    66757   66757   66757.0  18.0990       NaN
66775    66775   66775   66775.0   2.1580       NaN
66819    66819   66819   66819.0   6.6390       NaN
66820    66820   66820   66820.0   9.0000       NaN
66851    66851   66851   66851.0  11.2790       NaN
67150    67150   67150   67150.0  15.8500       NaN
67165    67165   67165   67165.0  13.0010       NaN
67471    67471   67471   67471.0   2.7280       NaN
67656    67656   67656   67656.0  16.4550       NaN
67780    67780   67780   67780.0   9.5400       NaN
67789    67789   67789   67789.0  17.1050       NaN
67811    67811   67811   67811.0  12.6990       NaN
67827    67827   67827   67827.0  19.7170       NaN
68028    68028   68028   68028.0   7.8690       NaN
68164    68164   68164   68164.0  18.3930       NaN
68230    68230   68230   68230.0   8.0470       NaN
68501    68501   68501   68501.0  14.3160       NaN
68680    68680   68680   68680.0  16.5650       NaN
68759    68759   68759   68759.0  19.3430       NaN
69111    69111   69111   69111.0  14.6250       NaN
69112    69112   69112   69112.0   7.5880       NaN
69134    69134   69134   69134.0   3.7230       NaN
69244    69244   69244   69244.0   6.2200       NaN
69267    69267   69267   69267.0   5.8900       NaN
69268    69268   69268   69268.0   3.0310       NaN
69297    69297   69297   69297.0   1.2680       NaN
69579    69579   69579   69579.0  18.0290       NaN
69740    69740   69740   69740.0   8.2940       NaN
69906    69906   69906   69906.0   4.8440       NaN
69989    69989   69989   69989.0  10.9850       NaN
70248    70248   70248   70248.0   9.6600       NaN
70367    70367   70367   70367.0  18.2660       NaN
70492    70492   70492   70492.0   8.8950       NaN
70635    70635   70635   70635.0   2.1470       NaN
70817    70817   70817   70817.0  17.1380       NaN
70990    70990   70990   70990.0  15.9010       NaN
71276    71276   71276   71276.0   5.0270       NaN
71383    71383   71383   71383.0   2.0970       NaN
71430    71430   71430   71430.0   8.5720       NaN
71520    71520   71520   71520.0  13.2480       NaN
71642    71642   71642   71642.0   1.4960       NaN
71715    71715   71715   71715.0  13.0790       NaN
71749    71749   71749   71749.0  15.9310       NaN
71751    71751   71751   71751.0  15.9180       NaN
71853    71853   71853   71853.0   8.0370       NaN
71896    71896   71896   71896.0   4.2320       NaN
71930    71930   71930   71930.0  18.4510       NaN
71945    71945   71945   71945.0   5.5600       NaN
71958    71958   71958   71958.0   5.2720       NaN
71975    71975   71975   71975.0   9.7700       NaN
72002    72002   72002   72002.0  13.1780       NaN
72145    72145   72145   72145.0  13.4480       NaN
72257    72257   72257   72257.0  13.0230       NaN
72613    72613   72613   72613.0  11.1260       NaN
72670    72670   72670   72670.0   1.4810       NaN
72893    72893   72893   72893.0   9.5550       NaN
72979    72979   72979   72979.0   5.6600       NaN
73105    73105   73105   73105.0   6.0830       NaN
73354    73354   73354   73354.0  18.3570       NaN
73437    73437   73437   73437.0   2.5180       NaN
73524    73524   73524   73524.0   5.2070       NaN
73587    73587   73587   73587.0   9.7690       NaN
73706    73706   73706   73706.0  18.5300       NaN
73749    73749   73749   73749.0  19.3320       NaN
73789    73789   73789   73789.0  14.8410       NaN
73935    73935   73935   73935.0  14.7520       NaN
74086    74086   74086   74086.0   5.7780       NaN
74104    74104   74104   74104.0  17.6800       NaN
74129    74129   74129   74129.0  18.2250       NaN
74287    74287   74287   74287.0  10.7510       NaN
74640    74640   74640   74640.0  18.6410       NaN
74669    74669   74669   74669.0   1.1130       NaN
74911    74911   74911   74911.0  19.5130       NaN
75145    75145   75145   75145.0   6.3880       NaN
75147    75147   75147   75147.0  17.3980       NaN
75150    75150   75150   75150.0  12.1820       NaN
75181    75181   75181   75181.0   6.0600       NaN
75415    75415   75415   75415.0  19.1320       NaN
75423    75423   75423   75423.0   5.3680       NaN
75484    75484   75484   75484.0   3.1860       NaN
75498    75498   75498   75498.0   6.5370       NaN
75598    75598   75598   75598.0  19.2890       NaN
75607    75607   75607   75607.0   4.2990       NaN
75661    75661   75661   75661.0   1.0790       NaN
75825    75825   75825   75825.0   7.8390       NaN
76076    76076   76076   76076.0   5.3190       NaN
76078    76078   76078   76078.0   2.4010       NaN
76189    76189   76189   76189.0  18.9880       NaN
76381    76381   76381   76381.0  11.1590       NaN
76394    76394   76394   76394.0   5.4370       NaN
76409    76409   76409   76409.0   7.0080       NaN
76485    76485   76485   76485.0   9.2120       NaN
76707    76707   76707   76707.0   6.0310       NaN

In [118]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-93,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [120]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-93,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,08-08-02,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,08-12-80,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12-01-80,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,06-05-16,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12-07-86,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,09-05-95,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,03-08-12,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,07-01-92,10:08 PM,97950,13.873,False,Client Services
25,NaN,Male,10-08-12,1:12 AM,37076,18.576,NaN,Client Services
26,Craig,Male,2/27/2000,7:45 AM,37598,7.757,True,Marketing
27,Scott,NaN,07-11-91,6:58 PM,122367,5.218,False,Legal
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services
29,Benjamin,Male,1/26/2005,10:06 PM,79529,7.008,True,Legal
30,Christina,Female,08-06-02,1:19 PM,118780,9.096,True,Engineering
31,Joyce,NaN,2/20/2005,2:40 PM,88657,12.752,False,Product
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN
33,Jean,Female,12/18/1993,9:07 AM,119082,16.180,False,Business Development
34,Jerry,Male,01-10-04,12:56 PM,95734,19.096,False,Client Services
35,Theresa,Female,10-10-06,1:12 AM,85182,16.675,False,Sales
36,Rachel,Female,2/16/2009,8:47 PM,142032,12.599,False,Business Development
37,Linda,Female,10/19/1981,8:49 PM,57427,9.557,True,Client Services
38,Stephanie,Female,9/13/1986,1:52 AM,36844,5.574,True,Business Development
39,NaN,Male,1/29/2016,2:33 AM,122173,7.797,NaN,Client Services
40,Michael,Male,10-10-08,11:25 AM,99283,2.665,True,Distribution
41,Christine,NaN,6/28/2015,1:08 AM,66582,11.308,True,Business Development
42,Beverly,Female,09-09-98,8:26 PM,121918,15.835,False,Legal
43,Marilyn,Female,12-07-80,3:16 AM,73524,5.207,True,Marketing
44,Cynthia,Female,11/16/1988,6:54 PM,145146,7.482,True,Product
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
47,Kathy,Female,6/22/2005,4:51 AM,66820,9.000,True,Client Services
48,Clarence,Male,3/26/1996,5:57 AM,93581,6.083,True,Business Development
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales
50,Nancy,Female,9/23/2000,8:05 AM,94976,13.830,True,Engineering
51,NaN,NaN,12/17/2011,8:29 AM,41126,14.009,NaN,Sales
52,Todd,Male,2/18/1990,2:41 AM,49339,1.695,True,Human Resources
53,Alan,NaN,03-03-14,1:28 PM,40341,17.578,True,Finance
54,Sara,Female,8/15/2007,9:23 AM,83677,8.999,False,Engineering
55,Karen,Female,11/30/1999,7:46 AM,102488,17.653,True,Product
56,Carl,Male,05-03-06,5:55 PM,130276,16.084,True,Finance
57,Henry,Male,6/26/1996,1:44 AM,64715,15.107,True,Human Resources
58,Theresa,Female,04-11-10,7:18 AM,72670,1.481,True,Engineering
59,Irene,Female,05-07-97,9:32 AM,66851,11.279,False,Engineering
60,Paula,NaN,11/23/2005,2:01 PM,48866,4.271,False,Distribution
61,Denise,Female,11-06-01,12:03 PM,106862,3.699,False,Business Development
62,NaN,Female,06-12-07,5:25 PM,58112,19.414,NaN,Marketing
63,Matthew,Male,01-02-13,10:33 PM,35203,18.040,False,Human Resources
64,Kathleen,NaN,04-11-90,6:46 PM,77834,18.771,False,Business Development
65,Steve,Male,11-11-09,11:44 PM,61310,12.428,True,Distribution
66,Nancy,Female,12/15/2012,11:57 PM,125250,2.672,True,Business Development
67,Rachel,Female,8/16/1999,6:53 AM,51178,9.735,True,Finance
68,Jose,Male,10/30/2004,1:39 PM,84834,14.330,True,Finance
69,Irene,NaN,7/14/2015,4:31 PM,100863,4.382,True,Finance
70,Todd,NaN,06-10-03,2:26 PM,84692,6.617,False,Client Services
71,Johnny,Male,11-06-09,4:23 PM,118172,16.194,True,Sales
72,Bobby,Male,05-07-07,10:01 AM,54043,3.833,False,Product
73,Frances,Female,04-04-99,4:19 PM,90582,4.709,True,Sales
74,Thomas,Male,06-04-95,2:24 PM,62096,17.029,False,Marketing
75,Bonnie,Female,07-02-91,1:27 AM,104897,5.118,True,Human Resources
76,Margaret,Female,09-10-88,12:42 PM,131604,7.353,True,Distribution
77,Charles,Male,9/14/2004,8:13 PM,107391,1.260,True,Marketing
78,Robin,Female,06-04-83,3:15 PM,114797,5.965,True,Sales
79,Bonnie,Female,11/13/1988,3:30 PM,115814,4.990,False,Product
80,Gerald,NaN,3/17/1995,12:50 AM,137126,15.602,True,Sales
81,Christopher,Male,3/30/2008,10:52 AM,47369,14.822,False,Legal
82,Steven,Male,3/30/1980,9:20 PM,35095,8.379,True,Client Services
83,Shawn,Male,9/23/2005,2:55 AM,148115,6.539,True,Finance
84,Doris,Female,8/20/2004,5:51 AM,83072,7.511,False,Finance
85,Jeremy,Male,02-01-08,8:50 AM,100238,3.887,True,Client Services
86,Annie,NaN,9/29/2007,12:11 AM,103495,17.290,True,Business Development
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
88,Donna,Female,11/27/1991,1:59 PM,64088,6.155,True,Legal
89,Janice,Female,03-12-16,12:40 AM,51082,11.955,False,Legal
90,Janice,NaN,8/21/1997,5:12 AM,91719,11.583,True,Legal
91,James,NaN,1/26/2005,11:00 PM,128771,8.309,False,NaN
92,Linda,Female,5/25/2000,5:45 PM,119009,12.506,True,Business Development
93,Virginia,NaN,05-07-94,5:58 PM,111858,1.601,True,Legal
94,Harry,Male,8/26/1981,3:16 PM,130620,7.030,False,Legal
95,Heather,Female,07-11-98,2:17 PM,43026,14.166,False,Client Services
96,Cynthia,Female,3/21/1994,8:34 AM,142321,1.737,False,Finance
97,Laura,NaN,7/19/2014,9:23 PM,140371,10.620,True,Marketing
98,Tina,Female,6/16/2016,7:47 PM,100705,16.961,True,Marketing
99,Harold,Male,01-02-85,9:40 PM,77544,12.447,False,Business Development
100,Melissa,Female,6/21/2005,6:33 AM,48109,14.995,False,Finance
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
102,Jack,Male,01-12-97,5:51 AM,103902,12.159,False,Client Services
103,Phyllis,Female,10-11-96,9:30 PM,136984,8.932,True,Finance
104,John,Male,12/23/1989,7:01 AM,80740,19.305,False,Marketing
105,Kathy,Female,03-09-96,4:33 AM,91712,8.567,False,Finance
106,Paul,Male,08-04-93,7:25 PM,42146,3.046,False,Legal
107,Steven,Male,4/23/2013,10:12 PM,68680,16.565,False,Legal
108,Russell,NaN,05-05-88,7:57 AM,133980,12.396,True,Legal
109,Christopher,Male,4/22/2000,10:15 AM,37919,11.449,False,NaN
110,Shirley,Female,6/20/2001,10:39 PM,147113,16.135,False,Legal
111,Bonnie,Female,12/17/1999,3:12 PM,42153,8.454,True,Business Development
112,Willie,Male,11/27/2003,6:21 AM,64363,4.023,False,Marketing
113,Tina,Female,06-12-09,7:16 AM,114767,3.711,True,Engineering
114,Ashley,Female,08-04-02,11:00 AM,58698,6.811,True,Business Development
115,Pamela,Female,07-01-82,6:51 AM,54585,4.166,False,Product
116,NaN,Male,6/22/1991,8:58 PM,76189,18.988,NaN,Legal
117,Steven,Male,03-01-95,3:03 PM,109095,9.494,False,Finance
118,Andrea,Female,01-12-12,5:43 AM,120204,9.557,False,Business Development
119,Paul,Male,06-03-08,3:05 PM,41054,12.299,False,Marketing
120,Peter,Male,11/17/1994,6:15 PM,84885,15.402,False,Business Development
121,Kathleen,NaN,05-09-16,8:55 AM,119735,18.740,False,Product
122,Christina,Female,4/13/2012,2:04 PM,110169,13.892,True,Engineering
123,Helen,Female,11/29/2001,2:30 AM,73789,14.841,True,Product
124,Marilyn,Female,11/16/1983,8:29 AM,76078,2.401,True,Product
125,Patricia,Female,09-01-03,6:46 AM,49368,14.226,False,Human Resources
126,Michelle,Female,3/30/1984,6:43 PM,57325,17.179,True,Human Resources
127,William,Male,9/29/2002,4:09 PM,66521,5.830,False,Human Resources
128,Kenneth,Male,8/25/1987,9:16 PM,127654,16.439,True,Client Services
129,Antonio,Male,10/25/1988,1:50 PM,60866,13.101,True,Business Development
130,Shirley,Female,05-01-84,1:15 PM,41334,6.219,True,Human Resources
131,Rebecca,Female,07-10-92,12:23 AM,94231,17.517,False,Product
132,Carlos,Male,01-04-95,7:02 AM,146670,10.763,False,Human Resources
133,Lois,Female,12/25/1987,4:16 PM,106317,2.235,True,Client Services
134,Carolyn,Female,04-09-11,5:38 AM,109260,2.650,True,Business Development
135,Gloria,Female,6/29/2007,5:34 AM,134148,8.833,True,Legal
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
137,Adam,Male,5/21/2011,1:45 AM,95327,15.120,False,Distribution
138,Ashley,Female,5/25/2006,11:30 AM,112238,6.030,True,Engineering
139,NaN,Female,10-03-90,1:08 AM,132373,10.527,NaN,NaN
140,Shirley,Female,2/28/1981,1:23 PM,113850,1.854,False,Marketing
141,Adam,Male,12/24/1990,8:57 PM,110194,14.727,True,Product
142,Elizabeth,Female,10-09-03,5:53 PM,146129,5.687,False,Finance
143,Teresa,NaN,1/28/2016,10:55 AM,140013,8.689,True,Engineering
144,Nicole,NaN,03-05-82,2:28 PM,122717,12.452,False,Sales
145,Jennifer,Female,04-04-09,10:47 PM,71715,13.079,True,Client Services
146,Patricia,Female,11/25/1992,2:24 AM,95322,4.150,False,Product
147,Philip,Male,7/17/2008,1:30 PM,89227,3.996,False,Legal
148,Patrick,NaN,7/14/1991,2:24 AM,124488,14.837,True,Sales
149,NaN,Female,8/17/2014,2:00 PM,86230,8.578,NaN,Distribution
150,Sean,Male,05-04-96,8:59 PM,135490,19.934,False,Marketing
151,Brandon,NaN,11-03-97,8:17 PM,121333,15.295,False,Business Development
152,Ruth,Female,8/19/1999,4:03 AM,129297,8.067,True,Client Services
153,Victor,NaN,03-10-11,8:40 PM,84546,10.489,True,Finance
154,Rebecca,Female,11/15/1980,4:13 AM,85730,5.359,True,Product
155,Marie,Female,3/16/2003,12:12 AM,104058,17.695,True,Business Development
156,Howard,Male,4/27/1992,1:10 AM,105062,1.563,False,Human Resources
157,NaN,Female,7/27/2005,8:32 AM,79536,14.443,NaN,Product
158,Norma,Female,2/28/1999,8:45 PM,114412,8.756,True,Marketing
159,James,NaN,11/22/1983,10:52 PM,68501,14.316,False,Marketing
160,Kathy,Female,3/18/2000,7:26 PM,149563,16.991,True,Finance
161,Marilyn,NaN,8/22/1999,9:09 AM,103386,11.451,False,Distribution
162,Arthur,Male,4/13/1998,11:28 AM,89786,14.422,True,Legal
163,Terry,Male,09-03-90,9:15 PM,52226,19.135,False,Client Services
164,Mary,Female,8/13/1999,1:03 AM,134645,18.197,False,Business Development
165,NaN,Female,3/23/2014,1:28 PM,59148,9.061,NaN,Legal
166,NaN,Female,07-09-91,6:52 PM,42341,7.014,NaN,Sales
167,Christopher,Male,12/24/2011,12:22 PM,142178,17.984,True,Sales
168,Peter,NaN,09-03-87,5:59 PM,38989,7.017,True,Marketing
169,Michelle,Female,11-04-96,9:34 PM,53754,5.455,True,Product
170,Irene,Female,1/29/1992,11:36 AM,133772,19.020,True,Sales
171,Patrick,Male,8/17/2007,3:16 AM,143499,17.495,True,Engineering
172,Sara,Female,9/23/1991,6:17 PM,97058,9.402,False,Finance
173,Lillian,Female,12/21/2008,6:51 PM,85446,3.959,True,Engineering
174,NaN,NaN,9/18/2007,6:59 PM,40297,6.185,NaN,Client Services
175,Willie,Male,2/17/1998,8:20 PM,146651,1.451,True,Engineering
176,Victor,Male,01-08-03,1:02 PM,124486,10.166,False,Product
177,Wayne,Male,04-07-12,8:00 AM,102652,14.085,True,Distribution
178,Jane,Female,09-03-97,2:01 AM,144474,17.648,False,Product
179,Jessica,Female,10/23/1995,5:53 AM,68759,19.343,True,Finance
180,Mark,Male,04-12-08,5:40 PM,57286,5.025,True,Business Development
181,Randy,Male,11/14/1999,12:12 PM,58129,1.952,True,Distribution
182,Lillian,Female,6/19/1999,4:44 PM,123940,12.184,True,Business Development
183,Ruth,NaN,5/18/1999,5:56 AM,98233,2.518,True,Distribution
184,Jerry,Male,12/18/2003,6:46 AM,140810,9.177,True,Client Services
185,Sandra,Female,1/19/1983,7:25 AM,42090,8.842,True,Legal
186,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales
187,Roger,Male,11/19/2004,3:55 PM,51430,6.460,False,Marketing
188,Charles,Male,10/14/2000,9:40 PM,71749,15.931,False,Legal
189,Clarence,Male,05-02-98,3:16 AM,85700,1.215,False,Sales
190,Carol,Female,3/19/1996,3:39 AM,57783,9.129,False,Finance
191,Lois,Female,10/18/2013,4:51 PM,36946,6.652,False,Engineering
192,Barbara,NaN,05-03-03,7:32 PM,99326,16.475,True,Legal
193,Rebecca,Female,2/18/1995,6:50 AM,109259,4.443,True,Legal
194,Irene,Female,1/30/2004,8:25 PM,131038,8.996,False,Distribution
195,Ronald,Male,4/30/2014,2:19 PM,121068,12.757,True,Product
196,Steven,Male,11-10-85,10:53 AM,62719,19.127,False,Client Services
197,Carolyn,Female,11-06-12,3:51 AM,69268,3.031,False,Client Services
198,Maria,Female,12/27/1990,9:57 PM,36067,9.640,True,Product
199,Jonathan,Male,7/17/2009,8:15 AM,130581,16.736,True,NaN
200,Gary,Male,08-12-87,12:04 AM,89661,8.525,False,Finance
201,Kimberly,Female,7/15/1997,5:57 AM,36643,7.953,False,Marketing
202,Roger,Male,11-08-82,2:32 AM,140558,5.084,True,Sales
203,Diana,Female,01-04-13,7:53 AM,103521,2.784,True,Business Development
204,Willie,Male,06-06-06,9:45 AM,55281,4.935,True,Marketing
205,Brandon,Male,3/27/2006,5:54 PM,115711,8.012,True,Finance
206,Patricia,Female,12-06-12,4:01 AM,114079,8.399,True,Client Services
207,Katherine,Female,11/14/1999,8:15 AM,57531,1.767,False,Client Services
208,Jonathan,Male,10-12-87,2:59 AM,141069,4.903,False,Human Resources
209,Emily,Female,9/20/2007,11:25 AM,89434,11.295,False,Engineering
210,Ruth,Female,08-12-86,7:29 PM,44639,9.148,True,Legal
211,Linda,Female,6/24/2006,12:04 PM,110967,19.612,True,Human Resources
212,Lisa,Female,11-02-09,9:42 AM,115387,1.821,False,Client Services
213,Evelyn,Female,5/24/1980,11:10 PM,81673,15.364,True,Engineering
214,Julie,Female,7/23/1989,1:52 PM,109588,3.550,False,Engineering
215,Mary,Female,5/30/2009,11:41 PM,92544,3.800,False,Client Services
216,Matthew,Male,7/31/2013,8:04 AM,142373,2.462,False,Marketing
217,Douglas,Male,09-03-99,4:00 PM,83341,1.015,True,Client Services
218,Gregory,NaN,6/15/1992,5:08 AM,98865,10.628,True,Finance
219,Billy,Male,3/13/1995,12:05 PM,120444,7.768,True,Finance
220,NaN,Female,6/17/1991,12:49 PM,71945,5.560,NaN,Marketing
221,Gregory,Male,1/29/2000,6:01 AM,109564,3.845,False,Legal
222,Jason,Male,10/17/1999,10:09 PM,78417,3.067,False,Finance
223,Daniel,Male,4/30/2010,3:48 AM,106947,15.866,True,Legal
224,Sarah,Female,9/14/1995,7:50 AM,87298,2.311,False,Distribution
225,Harry,Male,10-01-15,7:47 PM,64579,15.266,True,Sales
226,Kathy,Female,4/19/1995,12:46 AM,50905,9.404,True,Finance
227,Todd,Male,4/13/1999,10:31 AM,59728,11.226,True,Client Services
228,Bobby,Male,9/23/1994,1:29 AM,51685,17.445,True,Engineering
229,Jeremy,Male,06-08-00,12:15 AM,49542,1.679,True,Distribution
230,George,NaN,2/24/1988,11:29 AM,38375,8.999,False,Legal
231,Diane,Female,4/18/1993,3:22 AM,64084,17.018,False,Product
232,Marilyn,Female,04-04-97,9:28 PM,147663,10.263,False,Human Resources
233,Kathryn,Female,02-04-04,1:47 PM,73935,14.752,False,Sales
234,Irene,Female,02-04-82,5:26 PM,40837,12.182,True,Client Services
235,Norma,Female,02-11-15,11:44 PM,94393,3.643,True,Engineering
236,Laura,Female,04-02-06,1:57 PM,42087,2.624,False,Product
237,Cheryl,Female,9/23/2008,2:57 AM,52080,9.375,False,Legal
238,Kevin,Male,3/25/1982,7:31 AM,35061,5.128,False,Legal
239,Lillian,NaN,05-12-16,3:43 PM,64164,17.612,False,Human Resources
240,Phyllis,NaN,4/21/1984,7:05 PM,94088,19.107,False,Distribution
241,Walter,Male,07-06-83,11:54 PM,127813,5.961,False,Finance
242,Robert,Male,10/27/1990,7:15 PM,38041,18.428,True,Engineering
243,Jimmy,Male,10-07-86,5:53 PM,126310,5.413,True,Product
244,Clarence,Male,10-08-96,12:53 PM,142561,8.866,False,Client Services
245,Victor,Male,04-11-91,7:44 AM,70817,17.138,False,Engineering
246,Fred,NaN,12-02-84,2:03 PM,59937,12.045,True,Human Resources
247,Brenda,NaN,7/27/2010,11:07 PM,106115,3.742,True,Product
248,Justin,Male,12-06-92,5:58 PM,82782,4.366,True,Distribution
249,Betty,Female,06-12-02,3:59 AM,104896,19.550,True,Business Development
250,Randy,NaN,02-06-86,3:04 PM,133943,8.940,True,Sales
251,Sharon,NaN,03-01-90,3:46 AM,83658,6.513,False,Business Development
252,Ralph,Male,11-11-04,1:35 AM,71896,4.232,True,Marketing
253,NaN,NaN,4/28/2003,3:01 AM,113732,10.391,NaN,Sales
254,Edward,Male,5/27/1985,10:13 PM,110485,7.995,False,Client Services
255,Denise,Female,3/20/2009,7:57 AM,115118,5.108,False,Human Resources
256,Debra,Female,3/13/1998,11:16 PM,48696,4.750,False,Legal
257,NaN,Male,11/25/1999,6:16 AM,42676,15.517,NaN,Sales
258,Michael,Male,1/24/2002,3:04 AM,43586,12.659,False,NaN
259,Henry,Male,02-06-95,8:34 AM,89258,15.585,True,Human Resources
260,Gloria,Female,3/27/2007,1:44 AM,90730,2.491,False,Distribution
261,Marie,Female,08-06-95,1:58 PM,100308,13.677,False,Product
262,Anne,Female,7/16/1986,2:08 PM,69134,3.723,True,Engineering
263,Sarah,NaN,11/21/1985,1:08 PM,58295,14.603,True,Engineering
264,Stephanie,Female,3/24/1983,11:15 AM,50141,13.218,True,Human Resources
265,Roy,Male,9/23/2004,1:31 PM,101941,3.450,False,Client Services
266,NaN,Female,08-05-09,8:14 AM,115145,14.063,NaN,Distribution
267,NaN,Male,02-04-05,1:01 PM,40451,16.044,NaN,Distribution
268,Irene,Female,03-03-82,8:26 AM,56526,5.810,True,Finance
269,NaN,Female,08-02-92,8:35 PM,145316,18.517,NaN,Human Resources
270,Thomas,Male,04-06-11,1:04 PM,103235,9.554,True,Human Resources
271,Frank,NaN,11/20/2001,10:18 AM,58563,12.062,True,Marketing
272,Fred,Male,2/20/1980,2:25 AM,74129,18.225,False,Product
273,Nicholas,Male,04-12-94,8:21 PM,74669,1.113,True,Product
274,Howard,Male,10-05-82,7:22 AM,97490,5.460,True,Marketing
275,Debra,Female,2/22/1994,10:25 PM,104250,18.456,True,Business Development
276,Christine,Female,07-03-89,4:01 AM,94345,11.996,False,Finance
277,Brenda,NaN,5/29/1991,6:32 AM,82439,19.062,False,Sales
278,Betty,Female,6/28/2005,6:03 PM,51613,12.984,False,Distribution
279,Ruby,Female,11-08-00,7:35 PM,105946,1.139,False,Business Development
280,Kevin,Male,07-12-97,2:07 AM,46080,9.635,False,Business Development
281,Arthur,Male,01-01-14,7:46 PM,134610,6.147,True,Human Resources
282,Carl,NaN,02-07-14,3:57 AM,125104,12.345,False,Client Services
283,Todd,Male,03-11-09,3:43 AM,107281,1.612,True,Engineering
284,Brenda,Female,10-06-05,9:33 PM,141521,4.337,False,Client Services
285,Judy,Female,9/16/1997,12:10 AM,65931,2.304,False,Human Resources
286,Todd,Male,02-02-84,10:13 AM,69989,10.985,True,Finance
287,Lois,Female,11-09-11,7:06 AM,147183,9.999,True,Client Services
288,Walter,NaN,12/21/1999,10:33 PM,66757,18.099,False,Distribution
289,Jessica,Female,9/27/1985,1:35 PM,75145,6.388,True,Legal
290,Jeremy,Male,6/14/1988,6:20 PM,129460,13.657,True,NaN
291,Tammy,Female,11-11-84,10:30 AM,132839,17.463,True,Client Services
292,Anne,Female,03-07-00,6:45 AM,44537,18.284,True,Client Services
293,Jesse,Male,10/25/1999,3:35 PM,118733,9.653,False,Marketing
294,Virginia,Female,10/20/1999,6:23 AM,46905,19.154,False,Distribution
295,Jesse,Male,03-02-81,7:26 PM,79582,3.873,False,Legal
296,Jeremy,NaN,11-10-96,1:49 PM,55394,3.180,True,Sales
297,Daniel,Male,9/15/2007,10:16 PM,123811,7.664,True,Human Resources
298,Patrick,NaN,8/30/2004,11:43 AM,137314,4.542,True,Marketing
299,Emily,Female,1/13/1988,6:42 AM,36711,19.028,True,Human Resources
300,Alan,Male,6/26/1988,3:54 AM,111786,3.592,True,Engineering
301,James,Male,07-11-15,8:52 PM,72257,13.023,False,Engineering
302,Adam,Male,07-05-07,11:59 AM,71276,5.027,True,Human Resources
303,Joan,NaN,7/25/1980,12:22 PM,38712,3.657,False,Client Services
304,Jeremy,Male,08-12-81,12:05 AM,46930,18.702,True,Finance
305,Margaret,Female,02-06-93,1:05 PM,125220,3.733,False,Marketing
306,Mark,Male,04-01-84,1:21 PM,121477,17.440,True,Business Development
307,Marilyn,Female,9/26/1981,2:23 AM,86386,2.937,False,Distribution
308,Cheryl,Female,09-08-09,10:16 AM,81308,2.196,True,Legal
309,Benjamin,Male,09-11-84,6:37 AM,84810,15.794,False,Marketing
310,Harold,Male,2/20/1990,11:00 PM,66775,2.158,True,Legal
311,Ernest,NaN,1/18/2002,1:51 AM,72145,13.448,True,Finance
312,Gerald,Male,4/16/2001,10:09 PM,121604,1.923,True,Sales

In [119]:
df.loc[2:5]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal

In [88]:
df=df.set_index("instant")

In [89]:
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [122]:
df.loc[2:5]
# index from dataframe

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal

In [121]:
df.iloc[2:5]
# position based indexing

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [92]:
df=df.set_index("dteday")

In [93]:
df.head()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,
01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [94]:
df.loc["01-01-2018"]

season          1.000000
yr              0.000000
mnth            1.000000
holiday         0.000000
weekday         1.000000
workingday      1.000000
weathersit      2.000000
temp           14.110847
atemp          18.181250
hum            80.583300
windspeed      10.749882
casual        331.000000
registered    654.000000
cnt           985.000000
Name: 01-01-2018, dtype: float64

In [95]:
df.iloc[2:5]

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,
03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [97]:
df.loc[df["temp"].idxmin()]

season          1.000000
yr              0.000000
mnth            1.000000
holiday         0.000000
weekday         1.000000
workingday      1.000000
weathersit      1.000000
temp            2.424346
atemp           3.953480
hum            40.000000
windspeed      11.521990
casual         93.000000
registered    888.000000
cnt           981.000000
Name: 22-01-2018, dtype: float64

In [98]:
df.isna().any()

season        False
yr            False
mnth          False
holiday       False
weekday       False
workingday    False
weathersit    False
temp          False
atemp         False
hum           False
windspeed     False
casual        False
registered    False
cnt           False
dtype: bool

In [99]:
df.loc[:,df.isna().any()]
#:--> all rows,df.isna().any() --> column name along with boolean series basis they have any missing value or not

Empty DataFrame
Columns: []
Index: [01-01-2018, 02-01-2018, 03-01-2018, 04-01-2018, 05-01-2018, 06-01-2018, 07-01-2018, 08-01-2018, 09-01-2018, 10-01-2018, 11-01-2018, 12-01-2018, 13-01-2018, 14-01-2018, 15-01-2018, 16-01-2018, 17-01-2018, 18-01-2018, 19-01-2018, 20-01-2018, 21-01-2018, 22-01-2018, 23-01-2018, 24-01-2018, 25-01-2018, 26-01-2018, 27-01-2018, 28-01-2018, 29-01-2018, 30-01-2018, 31-01-2018, 01-02-2018, 02-02-2018, 03-02-2018, 04-02-2018, 05-02-2018, 06-02-2018, 07-02-2018, 08-02-2018, 09-02-2018, 10-02-2018, 11-02-2018, 12-02-2018, 13-02-2018, 14-02-2018, 15-02-2018, 16-02-2018, 17-02-2018, 18-02-2018, 19-02-2018, 20-02-2018, 21-02-2018, 22-02-2018, 23-02-2018, 24-02-2018, 25-02-2018, 26-02-2018, 27-02-2018, 28-02-2018, 01-03-2018, 02-03-2018, 03-03-2018, 04-03-2018, 05-03-2018, 06-03-2018, 07-03-2018, 08-03-2018, 09-03-2018, 10-03-2018, 11-03-2018, 12-03-2018, 13-03-2018, 14-03-2018, 15-03-2018, 16-03-2018, 17-03-2018, 18-03-2018, 19-03-2018, 20-03-2018, 21-03-2018, 22-03-2018, 23-03-2018, 24-03-2018, 25-03-2018, 26-03-2018, 27-03-2018, 28-03-2018, 29-03-2018, 30-03-2018, 31-03-2018, 01-04-2018, 02-04-2018, 03-04-2018, 04-04-2018, 05-04-2018, 06-04-2018, 07-04-2018, 08-04-2018, 09-04-2018, 10-04-2018, ...]

In [103]:
df.iloc[0]["temp"]

14.110847